### ISSUE TITLE
Move boundary event from sub-process to task gives exception

### ISSUE THREAD

**Issue by nevries** [camunda/camunda-modeler#905] opened 2018-09-04 06:43 UTC
<img width="750" alt="bildschirmfoto 2018-09-04 um 08 36 52" src="https://user-images.githubusercontent.com/31620219/45014350-89128580-b01e-11e8-8f7d-d4531ab78fcc.png">

See screenshot, I tried to drag the error event attached to the sub-process to the boundary of the inner service task, which gives me:

```
Error: unexpected dockingDirection: <undefined>
    at getDockingPoint (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:110713:9)
    at connectRectangles (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:110367:22)
    at repairConnection (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:110429:25)
    at BpmnLayouter.layoutConnection (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:35786:107)
    at LayoutConnectionHandler.execute (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:102008:41)
    at file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:92075:31
    at CommandStack._atomicDo (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:92038:5)
    at CommandStack._internalExecute (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:92069:8)
    at CommandStack.execute (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:91825:8)
    at Modeling.layoutConnection (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:101010:22)  [error]
Error: unexpected dockingDirection: <undefined>
    at getDockingPoint (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:110713:9)
    at connectRectangles (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:110367:22)
    at repairConnection (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:110429:25)
    at BpmnLayouter.layoutConnection (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:35786:107)
    at LayoutConnectionHandler.execute (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:102008:41)
    at file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:92075:31
    at CommandStack._atomicDo (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:92038:5)
    at CommandStack._internalExecute (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:92069:8)
    at CommandStack.execute (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:91825:8)
    at Modeling.layoutConnection (file:///Applications/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:101010:22)  [error]
```

Unfortunately, I cannot reproduce it in smaller example.

**Comment by nikku** [comment] 2018-09-04 06:45
Please share the exact diagram contents (SubProcess + Boundary Event + Task) so that we're able to reproduce the issue.

Additionally, please provide us with the Camunda Modeler version you're using.

**Comment by nevries** [comment] 2018-09-04 06:47
Modeler 2.0.0

Sorry, exact diagram contents are gone, hoped stacktrace would be sufficient. BTW, it was a rendering issue only, the BPMN-contents were ok (re-open Modeler showed all as expected).

**Comment by nikku** [comment] 2018-09-04 06:50
Unfortunately I'm not able to reproduce this issue using the latest version of bpmn-js (packed into the Camunda Modeler). A great help for us is if you could provide relevant parts of a diagram you're able to reproduce the issue with.

Based on my testing (and the inability to reproduce this issue) it seems like you found a rare edge case which is hard to fix without a reliable way to reproduce it.

**Comment by nikku** [comment] 2018-09-04 06:53
It appears to me as if the diagram was previously broken, too: As shown in the stack trace, the editor attempts to layout a connection. However, there is no connection attached to the boundary event.

**Comment by nevries** [comment] 2018-09-04 06:57
There was a connection to the lower right end event which went away on my first dragging attempt. It sure was an edge case since I cannot reproduce it either. If it happens again, I will try to save all necessary infos.

**Comment by nikku** [comment] 2018-12-04 12:19
Closing as _cannot reproduce_. 

We are happy to re-open this one, if you provide us with a test case that allows us to reproduce the issue.

**Closed** 2018-12-04 12:18 UTC
Labels: backlog, bug
