### ISSUE TITLE
Cannot save diagram in XML view

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1876] opened 2020-07-11 10:39 UTC
__Describe the Bug__

when pasting stuff to a bpmn diagram in the xml view, I cannot use the keyboard shortcut ctrl + s in order to save the file

__Steps to Reproduce__

1. switch to xml view
2. paste something into the bpmn diagram --> e.g. <bpmn:message id="messageOne" name="Message_one" />
3. save the diagram by using the keyboard shortcur

__Expected Behavior__

save the diagram

__Environment__

- OS: Linux Mint 19.3 Cinnamon
- Camunda Modeler Version: 4.1.0

**Comment by philippfromme** [comment] 2020-07-13 06:49
I can reproduce this using Camunda Modeler v4.1.0 on Windows 10.

**Comment by pinussilvestrus** [comment] 2020-07-13 07:13
I can't reproduce this using Camunda Modeler v4.1.0 on macoS 10.15. CMD + S works fine for me, even after pasting stuff

**Comment by MaxTru** [comment] 2020-08-10 13:02
I can't reproduce this using Camunda Modeler v4.1.1 on Arch Manjaro Linux KDE

**Comment by barmac** [comment] 2021-09-10 09:57
@hari-parasuraman approached me regarding this. We can both reproduce it in 4.10.0.

1. Switch to XML view.
2. Change tab and type something in the properties panel.
3. Switch back to the previous tab (the one with the XML view).
4. File cannot be saved unless you try to close it.

https://user-images.githubusercontent.com/28307541/132836402-629fe57c-0d99-478a-9b15-154e8d8532ec.mp4

**Comment by barmac** [comment] 2022-11-08 15:21
Closed via https://github.com/camunda/camunda-modeler/pull/3244

**Closed by barmac** 2022-11-08 15:21 UTC
Labels: bug, spring cleaning
