### ISSUE TITLE
Scrolling causes UI craziness: OSX 10.12.6

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#817] opened 2018-06-01 17:05 UTC
Mac OS, 10.12.6
Modeler: 1.15.1

![screen shot 2018-06-01 at 1 03 34 pm](https://user-images.githubusercontent.com/1994838/40853503-4961b04a-659c-11e8-82f3-b87ac03195ad.png)

Makes the modeler essentially useless.

Scroll with the trackpad (2 fingers)

![screen shot 2018-06-01 at 1 05 19 pm](https://user-images.githubusercontent.com/1994838/40853556-841a65f6-659c-11e8-8336-dab81bfd416d.png)
![screen shot 2018-06-01 at 1 05 28 pm](https://user-images.githubusercontent.com/1994838/40853558-85192140-659c-11e8-8f0d-45c50d72ddf4.png)

**Comment by felix-mueller** [comment] 2018-06-03 17:40
I cannot reproduce this on MacOS 10.13.2 and Modeler 1.15.1
Looks very weird though

**Comment by nikku** [comment] 2018-06-04 08:22
As it looks like this is an issue with Mac OS 10.12.x.

As a workaround please continue to use `v1.14.x` on that older Mac OS version.

**Comment by StephenOTT** [comment] 2018-06-28 14:40
@nikku is this likely to get fix in the near future?

**Comment by nikku** [comment] 2018-06-28 17:59
Unfortunately not. As [mentioned above](https://github.com/camunda/camunda-modeler/issues/817#issuecomment-394273174) this appears to be an issue with MacOS Sierra and the latest version of Electron we use under the hood. 

Please stick to `v1.14.x` until things get fixed upstream on the Electron side.

**Comment by StephenOTT** [comment] 2018-06-28 18:00
@nikku you have identified this as a specific electron bug? and not just a modeler's implementation of electron?

**Comment by nikku** [comment] 2018-06-28 18:02
Likely related to https://github.com/electron/electron/issues/13252.

**Comment by StephenOTT** [comment] 2018-06-28 18:33
@nikku thanks

**Comment by nikku** [comment] 2018-08-21 16:42
This is odd. Reported to work on MacOS 10.13.4 and 10.13.2. 

I can try if I get the latest MacOS installed on my test machine.

**Comment by StephenOTT** [comment] 2018-08-21 16:47
possible its a hardware issue as well: Using Macbook Air 13-inch, Mid 2011 which is using Intel HD Graphics 3000 384 MB

Could be something to do with the Intel HD 3000

**Comment by felix-mueller** [comment] 2018-08-21 17:32
I use: Intel Iris Pro 1536 MB, MacBook Pro (Retina, 15-inch, Mid 2015), 10.13.2 and no issues.

**Comment by HarmPrinsDEX** [comment] 2018-10-09 13:05
I had the same problem on High Sierra, but using version 1.14 solves it.

**Comment by nikku** [comment] 2018-10-17 14:12
We are at Electron@3 in our latest nightly. Could you @StephenOTT check whether the artifacts still occur? Download the nightly from [here](https://camunda.org/release/camunda-modeler/nightly/).

**Comment by HarmPrinsDEX** [comment] 2018-10-17 16:01
Hi Nico,

It works fine now.

Met vriendelijke groet / kind regards,

Harm Prins
(+31) 6 434 97449
harm.prins@dataexplorers.nl
www.dataexplorers.nl

**Comment by nikku** [comment] 2018-10-17 17:29
Fixed via https://github.com/camunda/camunda-modeler/commit/d2e91cf583f79002dd3538d84aa4c3aacf1ecad9.

**Comment by StephenOTT** [comment] 2018-10-17 17:33
Seems to still be broken.

![screen shot 2018-10-17 at 1 32 45 pm](https://user-images.githubusercontent.com/1994838/47105195-3fb67800-d211-11e8-8fb0-4fa0c324aac0.png)

**Comment by StephenOTT** [comment] 2019-01-18 18:14
This appears to be fixed in atleast 2.2.4.

Can be closed if you wish.

**Closed** 2019-01-18 22:46 UTC
Labels: backlog, bug, platform:Darwin
