### ISSUE TITLE
External change update cannot be canceled

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1188] opened 2019-02-11 12:36 UTC
__Describe the Bug__

The external change dialog cannot be canceled right now:

![bug](https://user-images.githubusercontent.com/58601/52563354-712b0300-2e01-11e9-9abf-bc0a46672640.gif)

__Steps to Reproduce__

* Open diagram in editor
* Externally change diagram
* When asked whether to update choose `Cancel`

__Expected Behavior__

* Dialog does not appear unless file is changed externally again

__Environment__

Please complete the following information:

 - OS: Linux (may apply to others, too)
 - Camunda Modeler Version: `v3.0.0-0`

**Comment by pinussilvestrus** [comment] 2019-02-12 08:05
The fact that I can't reproduce it on MacOS leads me to the opinion that it fallbacks to misleading describes in https://github.com/camunda/camunda-modeler/pull/1150. After the user pressed on cancel, the `mainWindow#focus` event got triggered again, which does not get locked from our new `executeOnce` method, since canceling already ends the lock.

**Comment by pinussilvestrus** [comment] 2019-02-26 10:06
One solution would be to wait a moment after the dialog's got canceled. This will prevent the window from creating a new dialog since it would still run inside the `executeOnce` function. @nikku What do you think?

**Comment by pinussilvestrus** [comment] 2019-02-26 10:28
On the latest [nightly build](https://camunda.org/release/camunda-modeler/nightly/) I was not able to reproduce it. However, it seems to be still there on Linux.

**Comment by nikku** [comment] 2019-02-26 14:57
It turns out that there were a few things broken in the external file changed department:

* regardless of whether the user accepts or cancels the reload we should persist the last-modified (so that the user is not bothered with repeating update notifications)
* if the user pressed cancel there was no indication that the file displayed is not the one on disk

I presume the issue only surfaced on Linux, as the focus sequence is different on Mac + Windows.

PR https://github.com/camunda/camunda-modeler/pull/1277 fixes the issue and adds proper unsaved notification if the user cancels the update.

**Comment by pinussilvestrus** [comment] 2019-02-27 08:35
Closed via #1277.

**Closed by pinussilvestrus** 2019-02-27 08:35 UTC
Labels: bug, platform:Linux, ready
