### ISSUE TITLE
Camunda typing bug

### ISSUE THREAD

**Issue by wiltswim** [camunda/camunda-modeler#3715] opened 2023-07-07 11:57 UTC
### Describe the bug

When typing in Camunda I encounter errors. It doesn't occur when you type 1 character per second or longer. It occurs within documentation field or labels. (we do not use the other fields, so I can't say anything about that)
It happened to multiple users within our environment. We work on an online desktop (Citrix). It only occurs in Camunda, not other applications.

### Steps to reproduce

- When typing in the middle of a text, the cursor suddenly jumps to the end of the text. 
- When typing, some characters are not registrered. For instance, when I would type 'pizzeria', Camunda only registrated 'piera'.

### Expected behavior

No jumping in text.
All text is registrated.

## Camunda Modeler system information
 * Version: 5.0.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: <no active Tab or no execution platform set>

**Comment by nikku** [comment] 2023-07-07 12:01
Could you share a screen capture that shows how this occurs? Could you also file your context details? Is 5.0.0 the Modeler version you use? Could you trial the latest version in that case, too?

**Comment by wiltswim** [comment] 2023-07-07 12:09
Usually this occurs when having a workshop with other individuals on board. We never recorded this issue.
Next time this occurs I will make sure to record it.

We are using 5.0.0. What is the newest version?

Met vriendelijke groet,

Wim Wilts
Business Process designer Medior
***@***.***

[TKP]

Postbus 501  9700 AM Groningen
Europaweg 27  9723 AS Groningen
tkppensioen.nl<https://www.tkppensioen.nl>

Van: Nico Rehwaldt ***@***.***>
Verzonden: vrijdag 7 juli 2023 14:01
Aan: camunda/camunda-modeler ***@***.***>
CC: Wilts, Wim ***@***.***>; Author ***@***.***>
Onderwerp: Re: [camunda/camunda-modeler] Camunda typing bug (Issue #3715)


Could you share a screen capture that shows how this occurs? Could you also file your context details? Is 5.0.0 the Modeler version you use? Could you trial the latest version in that case, too?

**Comment by barmac** [comment] 2023-07-11 08:14
Please try out 5.12.1: https://downloads.camunda.cloud/release/camunda-modeler/5.12.1/

**Comment by nikku** [comment] 2023-07-19 21:13
Please try to record this, if possible.

Some applications like Zoom are known to break (slow down) user input to the point where it may be discarted, too.

**Comment by nikku** [comment] 2023-07-19 21:13
Closing this issue as _cannot reproduce_.

**Closed by nikku** 2023-07-19 21:13 UTC
Labels: bug, needs more information
