### ISSUE TITLE
Problems editing labels of collapsed pools

### ISSUE THREAD

**Issue by gimbel** [camunda/camunda-modeler#245] opened 2016-04-05 09:54 UTC
reproduce:
- create new BPMN diagram
- add pool and morph to collapsed pool
- double click on pool and add label and confirm with Enter
- select pool with mouse and drag somewhere

problem:
- label editing box stays visible after pressing enter
- dragging is broken and pool stays selected after drop

**Comment by nikku** [comment] 2016-04-07 10:52
Duplicate of #174.

Leaving it open because of better steps to reproduce.

**Comment by vladimirskatusenoks** [comment] 2016-04-15 14:08
Depends on [properties panel fix](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/174).

**Comment by gimbel** [comment] 2016-04-26 08:45
I am still able to reproduce problems (working with windows 64 bit edition nightly from 26th April)

**Comment by vkatushenok** [comment] 2016-04-26 10:26
Need to apply similar fix on top of bpmn-io/bpmn-js-properties-panel#175 changes.

**Closed** 2016-04-28 10:04 UTC
Labels: bug, needs review
