### ISSUE TITLE
Support 2-finger-scroll on touch pad

### ISSUE THREAD

**Issue by oscheller1** [camunda/camunda-modeler#688] opened 2017-10-23 07:13 UTC
It would be a welcome change if the macOS modeler supported 2-finger-scrolling both vertically and horizontally without the need to press Cmd or Shift (i.e. make it standard OS behavior). Also currently when scrolling vertically with Cmd + 2-finger-scroll, it scrolls in the "natural" (i.e. touch screen) direction, which is the wrong one of many users. This is also true for horizontal scrolling. There should be an option to change the scrolling direction.

Current behavior: `Cmd + 2-finger-scroll-to-top` = Document scrolls DOWN
Current behavior: `2-finger-scroll-to-top` = Document zooms in
Current behavior: `2-finger-pinch` = Document zooms in

Desired behavior:`2-finger-scroll-to-top` = Document scrolls UP
Desired behavior:`2-finger-pinch` = Document zooms in

I.e. make the Mac touchpad behave like it does in the rest of the operating system

**Comment by nikku** [comment] 2017-10-23 12:42
This is a duplicate of https://github.com/camunda/camunda-modeler/issues/629.

We'll look into this in future versions of the Camunda Modeler. Thanks for your valuable feedback.

**Closed by nikku** 2017-10-23 12:42 UTC
