### ISSUE TITLE
Unable to copy activities, sequence flows etc. to new process model

### ISSUE THREAD

**Issue by MichaelPruefer** [camunda/camunda-modeler#716] opened 2018-01-17 13:21 UTC
Steps to reproduce:
* Open existing bpm
* select some items with the lasso tool and copy them ("ctrl + c")
* press "ctrl + t" for new bpmn diagram
* press "ctrl + v" in the new diagram

current behavior:
* only call-activities and end-events are copied

expected behavior:
* all selected items are copied into new diagram
  * including sequence flows, gateways, activities etc.

Modeler Version: 1.11.3

**Comment by nikku** [comment] 2018-01-17 14:34
Works for me:

![copy](https://user-images.githubusercontent.com/58601/35047952-e2800e04-fb9b-11e7-87bd-411fc13adf3f.gif)

Please provide us with an example process that we can use to reproduce your issue.

Thanks!

**Comment by MichaelPruefer** [comment] 2018-01-17 15:07
Attached a bpmn example
[exportArcheMB.zip](https://github.com/camunda/camunda-modeler/files/1639427/exportArcheMB.zip)

If you select and copy only from the upper lane then not all items are copied to the destination diagram

Selected items:
![github716-1](https://user-images.githubusercontent.com/217915/35049447-54fa5756-fba0-11e7-912b-d256fbdfbd6d.png)
Paste result:
![github716-2](https://user-images.githubusercontent.com/217915/35049480-7410631a-fba0-11e7-81a5-1491df2986e9.png)

**Comment by nikku** [comment] 2018-01-18 10:21
There exists [a bug](https://github.com/bpmn-io/bpmn-js/issues/751) that prevents the Service Task, configured with `type="external"` from being copy + pasted.

This gets addressed once https://github.com/bpmn-io/bpmn-js/issues/751 is fixed and released.

**Comment by nikku** [comment] 2018-01-18 18:05
Will be part of next Camunda Modeler release.

**Closed** 2018-01-18 18:05 UTC
