### ISSUE TITLE
File -> New File opens two tabs at once

### ISSUE THREAD

**Issue by benjschneider** [camunda/camunda-modeler#1620] opened 2019-12-02 12:53 UTC
__Describe the Bug__

If a tab is already open and I choose to add another diagram via `File -> New File`, the editor opens two tabs at once. Expected behaviour would be just one new tab.

__Steps to Reproduce__

1. Have a tab open in Modeler
2. Select `File -> New File`and choose any diagram type
3. Two new tabs appear

__Expected Behavior__

Only one new tab opens.

__Environment__

- OS: MacOS 10.14.6
- Camunda Modeler Version: 3.5.0.4749

**Comment by nikku** [comment] 2019-12-02 13:06
Thanks for your report.

I cannot reproduce this on Linux so it looks like this may be a MacOS specific issue.

**Comment by nikku** [comment] 2019-12-02 13:06
@barmac Can you have a look?

**Comment by barmac** [comment] 2019-12-02 13:46
I cannot reproduce it on MacOS, sorry.

**Comment by pinussilvestrus** [comment] 2019-12-09 07:37
@benjschneider can you provide any more details which might help us to reproduce your problem? Or did you find out yourself what went wrong?

**Comment by philippfromme** [comment] 2019-12-09 14:32
Cannot reproduce on Windows either.

**Comment by barmac** [comment] 2019-12-09 14:34
I discussed this issue with @benjschneider today and he told me that he couldn't reproduce it afterwards. I am closing this.

**Closed by barmac** 2019-12-09 14:34 UTC
Labels: bug, cannot reproduce, platform:Darwin
