### ISSUE TITLE
Dropdown in properties panel does not work

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-modeler#4441] opened 2024-08-02 07:02 UTC
### Describe the bug

Some elements in the properties panel require the selection of properties from a dropdown.

Opening these dropdowns does not work.

See attached video.

https://github.com/user-attachments/assets/fc09fc62-82fe-4cc5-9123-4da7439e8a26

### Steps to reproduce

1. go to an element that has a dropdown in its properties
2. open the properties panel
3. click on a dropdown to open it
4. the dropdown is marked, but not opened

### Expected behavior

The dropdown opens

### Environment

- OS: MacOS Sonoma 14.5
- Camunda Modeler Version: 5.25.0
- Execution Platform: Camunda 7, Camunda 8
- Installed plug-ins: no plugins

### Additional context

Slack thread: https://camunda.slack.com/archives/C0693F1NFK5/p1722522530058939

**Comment by barmac** [comment] 2024-08-02 08:21
I cannot reproduce it on my machine. Unless we find a way to do it, it's unlikely we do anything about this issue.

Can you still reproduce it on the nightly build? https://downloads.camunda.cloud/release/camunda-modeler/nightly/

**Comment by jonathanlukas** [comment] 2024-08-02 11:24
@barmac I cannot even run the nighly build: 
<img width="266" alt="image" src="https://github.com/user-attachments/assets/4b8a8e53-719b-454f-acd8-d467f38e12f1">

**Comment by jonathanlukas** [comment] 2024-08-02 11:40
Ok, it seems that something the modeler caches in the `Library/Application Support/camunda-modeler` dir breaks it. I fixed it by:
* close the modeler
* save the `resources` dir somewhere else
* remove the whole content of the directory
* move the `resources` back
* start the modeler

**Comment by barmac** [comment] 2024-08-02 11:57
> @barmac I cannot even run the nighly build: <img alt="image" width="266" src="https://private-user-images.githubusercontent.com/81753891/354578618-4b8a8e53-719b-454f-acd8-d467f38e12f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTk2MjgsIm5iZiI6MTcyMjU5OTMyOCwicGF0aCI6Ii84MTc1Mzg5MS8zNTQ1Nzg2MTgtNGI4YThlNTMtNzE5Yi00NTRmLWFjZDgtZDQ2N2YzOGUxMmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDExNDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NGVlZjQzNDg0MzFkZjliMjVjZjQ1ZDI4NjZmNzkxMDQ5NGM1NDgzZWRhMGEyNGQxNDVkMGEzN2E3NWE2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h9W9L8kGCIL_X7llTkjYYjY_b92MdAgdPfjwOZNEnZs">

Please try right click the file and then select "Open".

**Comment by barmac** [comment] 2024-08-02 11:58
Since neither of us can now reproduce this issue, I am closing it. Feel free to comment if it happens again.

**Closed by barmac** 2024-08-02 11:58 UTC
Labels: bug

**Comment by barmac** [comment] 2024-08-21 09:27
We were able to reproduce this issue with the steps shared in https://github.com/camunda/camunda-modeler/issues/4467. I will keep it closed though as otherwise I'd need to close https://github.com/camunda/camunda-modeler/issues/4467 as duplicate.

**Comment by nikku** [comment] 2024-08-21 22:38
Fixed via https://github.com/camunda/camunda-modeler/pull/4471.
