### ISSUE TITLE
Sometimes I cannot properly align elements in my diagram

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#2558] opened 2021-11-11 12:22 UTC
__Describe the Bug__

Quoting from the feedback I received from one of our customers:

> Sometimes it's hard to align the elements together when you move parts of the process. I have to take the other elements connecting to the respective sequence flow and align them to the one that I cannot align.

The issue occurs randomly and I was not able to reproduce it, but I will try to describe it below.

__Steps to Reproduce__

Given the following process:

![Screenshot 2021-11-11 at 13 13 54](https://user-images.githubusercontent.com/25924333/141296563-eefe84cd-be3e-4eed-a035-11c8a32f3e2b.png)

1. I want to align the start event with the rest of the process
2. then I move the start event up and down,
3. but I cannot get a straight line for the sequence flow number 1

The only workaround that I have is to try to align the task and then the end event to the start event to get a straight line or recreate the sequence flow.

__Expected Behavior__

I should always be able to align one element with the rest of the process.

__Environment__
I don't have the necessary information about the environment.
- OS: [...]
- Camunda Modeler Version: [...]
- Execution Platform: [...]
- Installed plug-ins: [...]

**Comment by barmac** [comment] 2021-11-23 08:45
Thanks for reporting. I cannot reproduce it either. Can you please ask the person reporting to provide a capture of the bug?

**Comment by nikku** [comment] 2021-11-24 10:25
Closing this one as _cannot reproduce_. Happy to re-open if we get into the situation where we can reproduce it.

**Closed by nikku** 2021-11-24 10:25 UTC
Labels: bug, help wanted, cannot reproduce
