### ISSUE TITLE
React error when closing deployment overlay

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#4656] opened 2024-11-01 10:49 UTC
### Describe the bug

When closing the deplyoment overlay by opening another overlay there's a `Can't perform a React state update on an unmounted component.` error.

![electron_zZuvUceBIS](https://github.com/user-attachments/assets/a6447b17-29b2-4631-b8f4-aa6b6ea06b1a)

### Steps to reproduce

1. Open deployment overlay
2. Open different overlay
3. `Can't perform a React state update on an unmounted component.` error

### Expected behavior

No error.

### Environment

- Camunda Modeler Version: 5.29

**Comment by nikku** [comment] 2024-11-01 10:53
Moving to `ready`. We should not have random errors within our code base / developer logs.

**Comment by abdul99ahad** [comment] 2024-11-11 15:31
Can not reproduce this. am I missing something here? 

![Nov-11-2024 20-28-44](https://github.com/user-attachments/assets/22a1620a-350f-4bbd-8a8f-3b8762a4f730)

**Comment by philippfromme** [comment] 2024-11-12 13:24
I can still reproduce it by opening the deployment overlay and then without closing it opening the update overlay. This is the error:

![image](https://github.com/user-attachments/assets/8ed5edb8-535f-45ec-a4b8-f6b45c121780)

**Comment by abdul99ahad** [comment] 2024-11-12 14:00
> I can still reproduce it by opening the deployment overlay and then without closing it opening the update overlay. This is the error:
> 
> ![image](https://private-user-images.githubusercontent.com/7633572/385300483-8ed5edb8-535f-45ec-a4b8-f6b45c121780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjAyNzgsIm5iZiI6MTczMTQxOTk3OCwicGF0aCI6Ii83NjMzNTcyLzM4NTMwMDQ4My04ZWQ1ZWRiOC01MzVmLTQ1ZWMtYTRiOC1mNmI0NWMxMjE3ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMTM1OTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE0NTc4YjViZmQ0MmQyNzY0YWFmZjg2YzA3Y2Q2OTMyZTI3YTZmMjEyZTY5YmRlYzVjOWIyMDhiZDFmZTNmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9aVQH-GQTybYgqocnXFrtrO8BC52vjb-tY4SfEEDE_4)

Could this be Windows specific issue? not really sure. @barmac can you please confirm?

**Comment by barmac** [comment] 2024-11-12 14:16
I cannot reproduce it on `main` anymore.

**Comment by abdul99ahad** [comment] 2024-11-18 11:00
What approach should we take for this issue? Should we close it for now, or are there additional details or steps we should investigate further?

cc: @nikku

**Comment by barmac** [comment] 2024-11-18 11:15
@philippfromme can you still reproduce the issue? Right now you are the only one. Otherwise I'd close the issue.

**Comment by nikku** [comment] 2024-11-18 11:45
Let's close as _cannot reproduce_ and await further feedback.

**Closed by nikku** 2024-11-18 11:45 UTC
Labels: bug, in progress
