### ISSUE TITLE
Groups are closed when properties panel is resized

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3601] opened 2023-05-09 13:45 UTC
### Describe the bug

Given a group is open, when I resize the properties panel, the group is closed.

https://github.com/camunda/camunda-modeler/assets/28307541/ba89b717-d539-49bf-94aa-f930d7e630a9

### Steps to reproduce

1. Open a group
2. Resize properties panel
3. Group is closed

### Expected behavior

Group should remain open.

### Environment

- OS: MacOS
- Camunda Modeler Version: 5.11.0
- Execution Platform: any
- Installed plug-ins: [...]

### Additional context

This is a regression.

**Comment by marstamm** [comment] 2023-05-09 14:09
Root cause: with [08fead9](https://github.com/camunda/camunda-modeler/pull/3592/commits/08fead9c94502e8a5d27655c9e9ba19ca9159733) we pass the layout from `PropertiesContainer` to the PropertiesPanel and override the current layout.

Unfortunately, the layout provided by the `PropertiesContainer` Component only contains size information and does not modify the actual layout, thus closing all Groups

**Comment by marstamm** [comment] 2023-05-09 14:37
**Proposed Solution**

Do not make assumptions about the layout provided by the child components. The individual properties are merged on App level. Instead, react to it when the prop changes.

We do need to JSON compare the config options to not create an infinite loop when we send the update to the Properties panel and this change gets reported back the chain.

This solution depends on https://github.com/camunda/camunda-modeler/issues/3597

**Closed** 2023-05-30 15:26 UTC
Labels: bug, in progress, properties panel
