### ISSUE TITLE
Diagram marked dirty after direct editing text annotation without change

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#858] opened 2018-07-24 08:37 UTC
When direct editing a text annotation and completing (ENTER or click outside) without change diagram will me marked dirty.

Hint: Even without a change there will always be a modeling operation after directEditing.complete since the size of the text annotation could have changed through resizing.

![2018-07-24_10-34-37](https://user-images.githubusercontent.com/7633572/43126518-3639e05e-8f2d-11e8-8b83-882bb8fecd47.gif)

---

Referenced in [`SUPPORT-4642`](https://app.camunda.com/jira/browse/SUPPORT-4642)

Depends on https://github.com/bpmn-io/diagram-js-direct-editing/issues/9

**Comment by nikku** [comment] 2019-03-06 12:09
This is the intended behavior right now and requires a fix via https://github.com/bpmn-io/diagram-js-direct-editing/issues/9.

**Comment by gustavjf** [comment] 2019-04-08 09:03
Closed via https://github.com/camunda/camunda-modeler/commit/1c020abca3111b7947ac991affa55b47d473d44a

**Closed by gustavjf** 2019-04-08 09:03 UTC
Labels: bug, channel:support, good first issue, modeling, ready

**Comment by nikku** [comment] 2019-04-26 13:18
Released as [`v3.1.0`](https://github.com/camunda/camunda-modeler/releases/tag/v3.1.0)
