### ISSUE TITLE
Spacing Tool refuses to make space

### ISSUE THREAD

**Issue by sebwarnke** [camunda/camunda-modeler#1652] opened 2020-01-08 10:57 UTC
__Describe the Bug__

I tried to make some space in the diagram attached. But some how it did not work from the position I dragged the model from. A bit farther in the left spacing worked again.

![Kapture 2020-01-08 at 11 50 18](https://user-images.githubusercontent.com/26740468/71972717-8117b680-320d-11ea-9d5d-4a141f6d9def.gif)

[project-renewal.bpmn.txt](https://github.com/camunda/camunda-modeler/files/4034898/project-renewal.bpmn.txt)

__Environment__

- OS: MacOS Catalina
- Camunda Modeler Version: 3.5.0

---

Related to #1371

**Comment by nikku** [comment] 2020-01-09 19:56
This is due to the fact that the text annotation (cf. screencast) would be resized to a negative width.
A fix implemented 2016 prevents resizing from working all together in this case. It is not a bug but a feature, so to say.

Can you think of an alternative behavior that is more intuitive in this edge case?

**Comment by philippfromme** [comment] 2020-01-14 15:14
My expectation would be that the operation is not rejected and elements are resized to their minimum size. Compare that to how resizing single shapes works:

![14-01-_2020_16-12-30](https://user-images.githubusercontent.com/7633572/72356021-cdb93100-36e8-11ea-9a7a-200fc1cd5db5.gif)

As soon as I move the mouse past the minimum size the preview indicates that the shape will resize to its minimum size.

**Comment by philippfromme** [comment] 2020-01-17 15:43
Possible solution that I've been working on:

![space-tool-2](https://user-images.githubusercontent.com/7633572/72624415-369de480-3947-11ea-8002-08291c57ac6a.gif)

**Comment by sebwarnke** [comment] 2020-01-20 14:42
sorry for the delay in my answer. i really like the proposals by @philippfromme

**Comment by sebwarnke** [comment] 2020-01-20 14:44
maybe we could highlight the limitting edge so that it gets even more clear why a user cannot space further.

**Comment by slizenko** [comment] 2020-03-09 13:28
Gents, please see #1372 
If it will be addressed, the problem described here will go.

**Comment by philippfromme** [comment] 2020-03-09 13:29
@slizenko How are these two issues related?

**Comment by slizenko** [comment] 2020-03-09 13:46
@philippfromme, why spacing tool should resize annotation?
Because it is resizable as pool or swimlane?
If spacing tool will treat annotation box as task box (unresizable), then no problem.

**Comment by nikku** [comment] 2020-03-09 13:49
@slizenko Please link the correct issue. The one you linked is about segmentation faults and clearly _not_ related.

**Comment by slizenko** [comment] 2020-03-09 13:51
my fault, sorry, correct link is #1371 not 1372.

**Comment by philippfromme** [comment] 2020-04-02 13:10
Closed via https://github.com/camunda/camunda-modeler/issues/1368

**Closed by philippfromme** 2020-04-02 13:10 UTC
Labels: backlog, bug

**Comment by KS1080** [comment] 2023-11-11 20:18
Hello, I have a similar problem with Camunda Modeler for Desktop Windows 64 bit, when I try to click the cross disappears....

**Comment by nikku** [comment] 2023-11-12 22:16
@KS1080 Please open a new bug report, including the concrete steps to reproduce your issue, best with a screen capture or a diagram you can share. Thanks.
