### ISSUE TITLE
Transparent screen is dispayed for a very short while before the values are populated in any dropdown.

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2910] opened 2022-04-08 11:48 UTC
__Describe the Bug__

Try to open up any dropdown we could see a transparent screen for a very short time before the values are populated.

__Steps to Reproduce__

1. click on a any dropdown in the modeler.
2. We could see a transparent screen for a very short time before the values are populated.

I could not make a screen cast  as the transparent screen appears only for a second but it is visible in every dropdown of the application. 

__Expected Behavior__

Clear the transparent screen before values are populated in the dropdown.

__Environment__

- OS: [Windows 10]
- Camunda Modeler Version: [5.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]

**Comment by pinussilvestrus** [comment] 2022-04-08 13:24
I can't reproduce it on macOS, so it's maybe related to OS-related native form element styles. To prevent this, we could consider [having unified form elements](https://github.com/camunda/camunda-modeler/issues/2460), that look and behave the same on any OS (and prevent unexpected, OS-specific behaviors).

Can we somehow reproduce this behavior on other OS (Linux and Windows)? /cc @MaxTru @marstamm @Skaiir @philippfromme

**Comment by marstamm** [comment] 2022-04-08 13:26
Can't reproduce on Linux either. But if it is just very brief, I might just be to blind to see it

**Comment by marstamm** [comment] 2022-04-26 07:08
Closing as we can't reproduce it. Please reopen the ticket if you still feel it is valid

**Closed by marstamm** 2022-04-26 07:08 UTC
Labels: bug, help wanted, cannot reproduce
