### ISSUE TITLE
Bug: Exporting to a image

### ISSUE THREAD

**Issue by rbatllet** [camunda/camunda-modeler#425] opened 2016-10-11 10:31 UTC
If you export a component with a default flow, the default flow is not showed in the image (PNG or JPG) anymore.

In the Camunda modeler:
![screen shot 2016-10-11 at 12 27 29](https://cloud.githubusercontent.com/assets/3993987/19267271/28860990-8fae-11e6-8dcf-0d8ea472c7dd.png)

The exported PNG image:

![screen shot 2016-10-11 at 12 30 11](https://cloud.githubusercontent.com/assets/3993987/19267335/80db2a58-8fae-11e6-88a0-5b733e0688ec.png)

[diagram.zip](https://github.com/camunda/camunda-modeler/files/521579/diagram.zip)

**Comment by nikku** [comment] 2016-10-11 11:11
Duplicate of https://github.com/camunda/camunda-modeler/issues/250

**Closed by nikku** 2016-10-11 11:11 UTC
Labels: duplicate
