### ISSUE TITLE
Check for update on 4.7.0 says that no update is available (which is wrong)

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2377] opened 2021-07-20 08:09 UTC
__Describe the Bug__

After reading the blogpost announcing version 4.9.0 of the modeler, I want to upgrade my 4.7.0 installation.

Running the "Check for Updates" option from the Help menue, it states: "You are running the latest version".

__Steps to Reproduce__

1. Run Camunda Modeler 4.7.0
2. Wait until 4.9.0 is announced
3. Open Help -> Check for Updates

__Expected Behavior__

A dialogue opens with a link where to download the version 4.9.0 or the download starts automatically or after confirming.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.7.0
- Execution Platform: Camunda Platform
- Installed plug-ins: Cloud Connect, Token Simulation, BPMN Linter, Transaction Boundaries, Camunda Property Info, Tooltip Plugin

**Comment by nikku** [comment] 2021-07-20 12:12
This is a known issue and duplicate of https://github.com/camunda/camunda-modeler/issues/2263 I believe.

Could you verify that?

**Comment by ingorichtsmeier** [comment] 2021-07-20 12:33
yes, it is.

**Closed** 2021-07-20 12:33 UTC
Labels: bug, duplicate
