### ISSUE TITLE
Warning "unknown attribute <background-color>"

### ISSUE THREAD

**Issue by hinneLinks** [camunda/camunda-modeler#2599] opened 2021-11-30 14:19 UTC
__Describe the Bug__

Coloring the named Paths after a Gateway, saving the Model and reopen It, creates a Warning:

`[ FILE_PATH ] unknown attribute <background-color> [ warning ]`

Its not just the Warning, our automated Unittests using these Models fail, because of the created "background-color"-Attributes. See full atttached Stacktrace: [bug-background-color-camunda-bpm-unittest.txt](https://github.com/camunda/camunda-modeler/files/7626425/bug-background-color-camunda-bpm-unittest.txt)

`* cvc-complex-type.3.2.2: Attribut 'background-color' darf nicht in Element 'bpmndi:BPMNEdge' vorkommen. | resource process/Process.bpmn | line 215 | column 170
`

__Steps to Reproduce__

1. Create a simple Model  with named Paths on a Gatway (see [test diagram](https://github.com/camunda/camunda-modeler/files/7648671/color-test.bpmn.txt))
2. Select every Element with STRG + A (including the Outgoing Paths of the first Gateway) and give them a Color
3. Save the File
4. Reopen the file, now the Log opens with two Warnings, both related to the outgoing Paths of the Gateway
`[ FILE_PATH ] unknown attribute <background-color> [ warning ]
[ FILE_PATH ] unknown attribute <background-color> [ warning ]`

__Expected Behavior__

No Warnings (e.g. no invalid elements) are created when saving and reopening a File with colored Elements.
Models created by Camunda-Modeler run without Parsing-Errors in Camunda-Unittest and Engine.

__Environment__
I tried both 4.11.1 und 4.10.0 Versions of Camunda-Modeler
- OS: Windows 10
- Camunda Modeler Version: [4.11.1, 4.10.0]
- Execution Platform: [Camunda Enterprise Platform 7.15.6]
- Installed plug-ins: [4.11.1: None, 4.10.0: BPMN Linter,  Camunda Property Infos, Tooltip Plugin, Transaction Boundaries]

p.s.: If necessary/Helpful i could also create an Jira-Ticket at jira.camunda.com since we are an enterprise customer for the Engine.
pps: This Bug Might be related to #2452 but we are only using Camunda Modeler to edit our Models.

**Comment by nikku** [comment] 2021-11-30 14:33
Thanks for your bug report. We'll have a look and get back to you soon.

**Comment by smbea** [comment] 2021-12-03 10:15
I believe the problem is in the XML. The XML file of the diagrams you provided contain a `background-color` for paths. Since paths are just edges, they only support `border-color` and **not** `background-color`. The Modeler doesn't add this property to paths, so it could have originated by directly editing the XML file.

This can be confirmed by copying and pasting the diagram provided (not the XML file) to a brand new BPMN file, color it and save it -> then this **error message should not appear.**

Let us know if still encounter problems with this.

**Comment by smbea** [comment] 2021-12-03 10:35
Thank you for your contribution. I was able to reproduce the issue. We'll look into this.

**Comment by nikku** [comment] 2021-12-03 19:33
Closed via https://github.com/bpmn-io/bpmn-js/commit/3a96864a9708653962472b4ee9e4d7a23d7b7c4c.

**Closed** 2022-01-27 10:32 UTC
Labels: bug, needs review
