### ISSUE TITLE
Pattern validation should be applied only on non-FEEL values

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4140] opened 2024-02-19 12:46 UTC
### Describe the bug

Given my template can take either a static value or a FEEL expression, I want to prevent users from providing an invalid value via pattern. However, right now my pattern has to allow values starting with `=` to disable pattern errors for FEEL expression.

### Steps to reproduce

1. Use this template:

```json
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "Pattern",
  "id": "test",
  "version": 3,
  "description": "Test pattern",
  "appliesTo": [
    "bpmn:Task"
  ],
  "elementType": {
    "value": "bpmn:ServiceTask"
  },
  "properties": [
    {
      "label": "pattern test",
      "constraints": {
        "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
      },
      "binding": {
        "property": "type",
        "name": "patternProperty",
        "type": "zeebe:property"
      },
      "type": "Text",
      "language": "feel",
      "feel": "optional"
    }
  ]
}
```

2. Try to enter any expression

![image](https://github.com/camunda/camunda-modeler/assets/28307541/d82042c7-e26d-44a8-b1ac-66a03192cec6)

### Expected behavior

* [ ] Pattern validation works only for static values.
* [ ] We consider if _any other validations_ only make sense for static inputs and adjust them accordingly

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

[SUPPORT-20595](https://jira.camunda.com/browse/SUPPORT-20595)

**Comment by nikku** [comment] 2024-02-19 20:03
This is a recurring issue, and our feedback is: We validate the value, and as such you have to design your pattern to allow `^(=|static pattern of your choice$)`.

**Comment by barmac** [comment] 2024-02-20 08:30
Would you say then that it's `wontfix`?

**Comment by nikku** [comment] 2024-02-21 13:19
Let's consider the end-user perspective:

* Right now `pattern` and other validations are applied on the raw field values, and as such can be used to validate FEEL expressions (ought to be dynamic), too.
* Shall `pattern` and any other validations only available to static values? If so, let's consistently follow up with that.
* Alternatively keep things as is and consider `pattern` validation a feature.

My tendency is that we want to apply `pattern` to _static_ inputs only. This simplifies their lives. We'd need to properly document this, and implement this behavior.

**Comment by barmac** [comment] 2024-02-23 09:46
Thanks Nico for your input. What I understood from this is that the issue is valid, and I'll put it into the backlog since it's not critical.

**Comment by jonathanlukas** [comment] 2024-07-25 07:11
My further feedback here: As a generated connector template uses the `@Pattern` validation, the pattern should be applied to the actual value at least.

@sbuettner how did you resolve this in your connectors?

**Comment by jarekdanielak** [comment] 2024-07-25 08:08
Moving it to Ready. The problem is defined and should be fixed.

**Comment by sbuettner** [comment] 2024-07-25 08:47
@jonathanlukas We are struggling with this as well and are working on a "hack" to have a better experience when writing patterns in our element template generator. 

I agree that validating FEEL expressions with regex patterns is not very useful. Maybe we can improve the validation logic here to exclude FEEL expressions from being validated by patterns at all as they require runtime validation anyway.

**Comment by nikku** [comment] 2024-07-25 09:14
Thanks for chiming in @sbuettner. We moved this to ready and will probe "not validating feel expressions". 

Userland should be unaffected by this change (expressions right now are forgiving) _unless_, for the rare case where they _actually_ validate the pattern a FEEL expression uses.

**Closed** 2024-08-22 09:58 UTC
Labels: bug, needs review, channel:support, element templates, spring cleaning
