### ISSUE TITLE
ESLint couldn't find the plugin "eslint-plugin-bpmn-io".

### ISSUE THREAD

**Issue by AlexeyZabolockyi** [camunda/camunda-modeler#1470] opened 2019-08-19 07:46 UTC
__Describe the Bug__

ESLint couldn't find the plugin "eslint-plugin-bpmn-io".

__Steps to Reproduce__

1. Download ZIp Archive
2 Unzip Camunda modeler
3. execute 'npm install' command in console
4. execute 'npm run all' command in console
also trying to fix problem by scripts 'npm install eslint-plugin-bpmn-io@latest --save-dev' and 'npm install --resolve-plugins-relative-to' but it does not help

__Expected Behavior__
scrips finished without any exceptions

__Environment__

 - OS: Windows 10
 - Camunda Modeler Version: 3.2.3
 - ESLint: 6.1.0

**Comment by nikku** [comment] 2019-08-19 07:48
Which archive did you download? In which folder do you `npm install`?

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 07:57
trying to work with develop branch and branch with tag 'v3.2.3, executes all command from modeler folder.

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 07:58
i forgot to add: 
npm@6.10.3
node@v12.7.0
may be it will help you

**Comment by nikku** [comment] 2019-08-19 08:02
Can you verify the following works (or does not work) for you:

```
git clone git@github.com:camunda/camunda-modeler.git
cd camunda-modeler
npm install
npm run all
```

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 08:10
i don't have git atm, so i'm not cloning repository from gitbut download as zip archive
it was needed to install few plugins such as lerna, eslint, lint and webpack to make npm install work without any exceprions. otherwise it failed. now 'npm install' works fine and 'npm run all'  not

**Comment by nikku** [comment] 2019-08-19 08:17
Cannot reproduce this on Linux.

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 08:18
but i work on windows, not Linux :)

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 08:29
Do you need .log files? Will it help or not?

**Comment by philippfromme** [comment] 2019-08-19 08:55
Cannot reproduce on Windows 10 either.

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 09:00
it's make me sad. what information i can give you to clarify my problem?

**Comment by nikku** [comment] 2019-08-19 09:50
Not sure. Do you have `eslint` installed globally?

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 09:55
yes

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 09:58
Tried to reinstall eslint. There was two warnings:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
may it will help

**Comment by nikku** [comment] 2019-08-19 10:07
Does it work if you uninstall the global eslint version?

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 10:11
Nope. Unisntall the global eslint. Failed at " 'eslint' is not recognized as an internal or external command, operable program or batch file."

**Comment by nikku** [comment] 2019-08-19 12:00
This seems to be an issue with your setup then, I presume it is the fact that you build it via the standard `cmd`?

I'd recommend you to use the git bash shipped with [git for windows](https://gitforwindows.org/) or the [Linux sub-system for Windows](https://docs.microsoft.com/en-us/windows/wsl/install-win10) for building the app. That should work fine.

Building with the shells integrated in VSCode or other IDEs should work fine, too.

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 12:38
Have same problem with git bash for windows.

**Comment by nikku** [comment] 2019-08-19 14:02
Unfortunately I cannot help you beyond this point.

We got two stock Windows 10 machines here for which the setup works. Our CI is green on Windows on some Server 16 or so, too.

**Comment by AlexeyZabolockyi** [comment] 2019-08-19 14:28
Ok. thank for the support. One last question from me. Does your windows have 32 bit or 64 bit?

**Comment by nikku** [comment] 2019-08-19 14:31
64

**Comment by nikku** [comment] 2019-08-19 14:38
Closing this issue as there is nothing else we can do for you. Hope you sort this thing out!

**Closed by nikku** 2019-08-19 14:38 UTC
Labels: help wanted
