### ISSUE TITLE
Unable to deploy from Modeler to Camunda 8 Self Managed deployed to Azure

### ISSUE THREAD

**Issue by superbeagle** [camunda/camunda-modeler#3037] opened 2022-07-18 14:26 UTC
### Describe the bug

This is the error in the log when I attempt to deploy from Modeler into Camunda 8 Self Managed deployed to Azure:
`2022-07-13T11:53:50.371Z  ERROR app:zeebe-api Failed to connect with config (secrets omitted): {
  endpoint: {
    type: 'selfHosted',
    url: 'camundajoe.eastus2.cloudapp.azure.com:443'
  }
} Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
    at Object.callErrorFromStatus (C:\Modeler 5.0\resources\app.asar\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\Modeler 5.0\resources\app.asar\node_modules\@grpc\grpc-js\build\src\client.js:180:52)
    at C:\Modeler 5.0\resources\app.asar\node_modules\@grpc\grpc-js\build\src\call-stream.js:111:35
    at Object.onReceiveStatus (C:\Modeler 5.0\resources\app.asar\node_modules\zeebe-node\dist\lib\GrpcClient.js:136:36)
    at InterceptingListenerImpl.onReceiveStatus (C:\Modeler 5.0\resources\app.asar\node_modules\@grpc\grpc-js\build\src\call-stream.js:106:23)
    at Object.onReceiveStatus (C:\Modeler 5.0\resources\app.asar\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:365:141)
    at Object.onReceiveStatus (C:\Modeler 5.0\resources\app.asar\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
    at C:\Modeler 5.0\resources\app.asar\node_modules\@grpc\grpc-js\build\src\call-stream.js:182:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}`

### Steps to reproduce

1. Deploy Camunda Platform 8 Self Managed to Azure using these instructions:
[Deploy to Azure](https://github.com/upgradingdave/camunda-deep-dives/tree/main/azure-zeebe-ingress)
3. Create a sample Camunda 8 process in Modeler
4. Attempt to deploy using Gateway address
5. See error

### Expected behavior

Process is deployed

### Environment

Azure Kubernetes cluster, see instructions above

**Comment by barmac** [comment] 2022-07-20 07:54
Hi @superbeagle, thanks for the report. I will look into this and try to reproduce the issue. When I am done, I will let you know in this issue.

**Comment by barmac** [comment] 2022-09-30 08:55
@superbeagle were you able to deploy to Azure with zbctl? It may be related to https://jira.camunda.com/browse/SUPPORT-14704?focusedCommentId=252907&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

**Comment by barmac** [comment] 2022-10-18 08:01
@superbeagle Please let me know if you can reproduce this issue with [the current nightly](https://camunda.org/release/camunda-modeler/nightly/).

**Comment by superbeagle** [comment] 2022-10-21 16:25
Will try it this afternoon JoeOn Oct 18, 2022, at 04:02, Maciej Barelkowski ***@***.***> wrote:﻿
@superbeagle Please let me know if you can reproduce this issue with the current nightly.

**Comment by nikku** [comment] 2023-01-30 10:54
```
Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
```

This could potentially be an issue with `grpc` (binary protocol) forwarding, cf. also [this case](https://jira.camunda.com/browse/SUPPORT-15699). 

I'd ask you @superbeagle to reproduce whether this works against `zbctl`. If that is the case then this would be a reason for us to further investigate this issue.

Closing the issue for now, happy to re-open if we are able to root cause this to a `zbctl <-> Camunda Modeler` miss-match.

**Closed by nikku** 2023-01-30 10:54 UTC
Labels: bug, backlog
