### ISSUE TITLE
Modeler freezes when run several times from Eclipse

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3352] opened 2022-12-09 12:13 UTC
### Describe the bug

There was a problem with EPIPE error when Modeler was run from Eclipse which was fixed via https://github.com/camunda/camunda-modeler/pull/3314
However, users report now that the app freezes randomly on Windows.
I was not able to reproduce it on Mac though.

### Steps to reproduce

1. Run Modeler several times from Eclipse
2. do that
3. now this happens

### Expected behavior

Should not freeze.

### Environment

- OS: Windows
- Camunda Modeler Version: 5.6 (rc, nightly)
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

### Additional context

Raised via [SUPPORT-15137](https://jira.camunda.com/browse/SUPPORT-15137)

**Comment by marstamm** [comment] 2022-12-09 12:58
I am able to reproduce it, but it is very flaky. Here is how I can reproduce it:

- The modeler instance MUST be spawned from eclipse. I can't reproduce it with a modeler opened from the explorer and just opening Files in eclipse
- The modeler stops working when I try to open 2 files quickly and the first is not finished rendering when the second one is opened.

**Logs**

There are no warnings or errors in the logs. I tried to spot irregularities and the only thing I found was this:

First diagram:
```
2022-12-09T12:37:24.408Z  INFO app:cli parsing [
  'D:\\camunda-modeler\\camunda-modeler-5.6.0-rc.1-win-x64\\Camunda Modeler.exe',
  '--allow-file-access-from-files',
  'D:\\Users\\<<USER>>\\eclipse-workspace\\bpmFiles\\diagram1.bpmn'
] in 'D:\\camunda-modeler'
2022-12-09T12:37:24.408Z  INFO app:main open files [
  'D:\\Users\\<<USER>>\\eclipse-workspace\\bpmFiles\\diagram1.bpmn'
]
2022-12-09T12:37:24.427Z  INFO app:main window focused
2022-12-09T12:37:24.398Z  INFO app:main:bootstrap starting Camunda Modeler v5.6.0-rc.1
2022-12-09T12:37:24.400Z  INFO app:cli parsing [
  'D:\\camunda-modeler\\camunda-modeler-5.6.0-rc.1-win-x64\\Camunda Modeler.exe',
  'D:\\Users\\<<USER>>\\eclipse-workspace\\bpmFiles\\diagram1.bpmn'
] in 'D:\\camunda-modeler'
2022-12-09T12:37:24.400Z  INFO app:flags searching for flags.json in paths [
  'D:\\camunda-modeler\\camunda-modeler-5.6.0-rc.1-win-x64\\resources',
  'C:\\Users\\<<USER>>\\AppData\\Roaming\\camunda-modeler\\resources'
]
```

Second diagram:
```
022-12-09T12:37:25.041Z  INFO app:cli parsing [
  'D:\\camunda-modeler\\camunda-modeler-5.6.0-rc.1-win-x64\\Camunda Modeler.exe',
  '--allow-file-access-from-files',
  'D:\\Users\\<<USER>>\\eclipse-workspace\\bpmFiles\\diagram2.bpmn'
] in 'D:\\camunda-modeler'
2022-12-09T12:37:25.030Z  INFO app:main:bootstrap starting Camunda Modeler v5.6.0-rc.1
2022-12-09T12:37:25.032Z  INFO app:cli parsing [
  'D:\\camunda-modeler\\camunda-modeler-5.6.0-rc.1-win-x64\\Camunda Modeler.exe',
  'D:\\Users\\<<USER>>\\eclipse-workspace\\bpmFiles\\diagram2.bpmn'
] in 'D:\\camunda-modeler'
```

Note that the `INFO app:main open files` is missing in the second one. 

However, still a big question mark on why this happens, why the main window would become unresponsive and what role eclipse plays in all of this

**Comment by barmac** [comment] 2023-01-09 13:10
On Mac, I cannot reproduce it even when I open multiple BPMNs at once.

**Comment by philippfromme** [comment] 2023-01-17 14:08
I tried to reproduce this issue on my machine with the help of @marstamm. No success. The modeler works just fine.

OS: Windows 10 Pro 22H2
Eclipse version: 2022-12 (4.26.0)

@CatalinaMoisuc How should we continue?

**Comment by marstamm** [comment] 2023-01-17 14:48
I did some click-testing again after my chat with @philippfromme. I can still reproduce it, but I can now narrow it down further and give a workaround for the user:

- It is **not** reproducible when the Camunda modeler is registered for the `.bpmn` file extension and `bpmn File` is choosen as how to open the file
![image](https://user-images.githubusercontent.com/21984219/212928288-64233de2-3ecd-45e5-83c4-b1ccc6d9f33a.png)

- I can still reproduce it if you decide to open it using `Browse` button and select the `Camunda Modeler.exe` manually

I could not find a screenshot from the customer to see if they have enabled this, but registering the Modeler as an editor for `.bpmn` files using the `support/register_fileassoc.bat` could solve the issue for them.

**Comment by barmac** [comment] 2023-01-17 15:50
Great that we seem to have a workaround. I updated the Jira ticket with a link to your comment.

**Comment by nikku** [comment] 2023-01-18 09:15
Closing this issue as [making the Camunda Modeler the default app for BPMN files is a workaround, and also recommended solution: https://github.com/camunda/camunda-modeler/issues/3352#issuecomment-1385541790.

**Closed by nikku** 2023-01-18 09:15 UTC
Labels: bug, ready, platform:Windows, channel:support
