### ISSUE TITLE
Warn about missing BPMN Shape 

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#4277] opened 2024-05-08 14:46 UTC
### Problem you would like to solve

I was not warned by Modeler that the diagram was missing a BPMN Shape for a process element.

Specifically, there was no `<bpmndi:BPMNShape>` for this:
```xml
<bpmn:sequenceFlow id="Flow_1d8avtw" sourceRef="Activity_1ipwzk8" targetRef="Activity_0ll9m9k" />
```

### Proposed solution

Warn the user with a problem stating that the process model has an item not visible in the diagram, and which item.

### Alternatives considered

Pay really good attention to the XML :)

In all honesty, another option is for Zeebe to reject models where the visual diagram does not provide a shape for each element in the process. There are several issues with this:
- breaks backward compatibility
- less interoperability with models produced by third parties
- I like doing less

### Additional context

I investigated [a process instance](https://bru-2.operate.camunda.io/689a796f-7efa-487f-9e44-76ca3a98c77b/processes/4503599664803449) that unexpectedly had an extra token after a parallel gateway. This made us think we had a bug in the engine.

After detailed root causing, I discovered that Zeebe executed the process instance correctly. There was a rogue Sequence Flow by passing the Parallel Gateway in the bpmn process (XML), but the visual diagram did not contain a BPMNShape for this item.

- incident channel with analysis: [#inc-unexpected-token-in-process-instance](https://camunda.slack.com/archives/C072L6FLWSG/p1715174440703259)
- applied fix of process after encountering issue https://github.com/zeebe-io/zeebe-engineering-processes/pull/389

**Comment by barmac** [comment] 2024-05-08 14:53
We could get this for free if we enable `bpmnlint:recommended` ruleset per default.

**Comment by nikku** [comment] 2024-05-13 10:01
@barmac Lightweight alternative to be considered: Add only the [`no-bpmndi` rule](https://github.com/bpmn-io/bpmnlint/blob/main/docs/rules/no-bpmndi.md). I think it is an important safeguard; at best it will save our users a bunch of time to root cause bugs.

**Comment by nikku** [comment] 2024-05-13 10:02
Moving to `ready` to discuss with the team.

**Closed** 2024-05-24 12:03 UTC
Labels: in progress, enhancement
