### ISSUE TITLE
Event label not transferred to new pool when moving event

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1211] opened 2019-02-12 14:26 UTC
// given
see attached screen cast

// when
I move an element plus label from one pool to another

// then
the event label gets lost

// hint 
the label stays visually behind the new pool element. The label will not be transferred to the pool (xml).

![1211 move event between pools does not include attached label](https://user-images.githubusercontent.com/232571/52642479-617fed00-2edb-11e9-9ed1-676370a65629.gif)

**Comment by nikku** [comment] 2019-02-12 15:02
Duplicate of https://github.com/camunda/camunda-modeler/issues/1050.

Fixed in Camunda Modeler `v3.0.0-0`.

**Closed by nikku** 2019-02-12 15:02 UTC
