### ISSUE TITLE
File change detection does not work for BPMN and CMMN (DMN works)

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#569] opened 2017-05-04 09:49 UTC
Camunda Modeler Version: 1.8.0

Also changes are ignored when re-opening closed tab.

**Comment by nikku** [comment] 2017-05-04 11:35
Works on Linux.

It seems however that the general file change detection is somewhat broken.

* We check for changed files on app re-open 
* We check for file change on tab re-open

In both cases, I'd expect the new version of the diagram to just get opened.

**Comment by nikku** [comment] 2017-05-04 11:36
Related to #563

**Comment by nikku** [comment] 2018-02-15 23:31
Should be fixed via #563?

**Comment by nikku** [comment] 2018-04-19 07:46
Cannot reproduce anymore.

**Closed by nikku** 2018-04-19 07:46 UTC
Labels: bug, invalid, platform:Darwin
