### ISSUE TITLE
Missing auto layout after reataching a sequence flow

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1199] opened 2019-02-12 13:38 UTC
// given
see attached screen cast

// when
I reattach the lower sequence flow

// then
I have to correct the sequence flow layout manually

![auto layout after reattaching sequence flow](https://user-images.githubusercontent.com/232571/52639286-347c0c00-2ed4-11e9-9a33-34a5290f4fee.gif)

**Comment by nikku** [comment] 2019-02-12 16:28
This is an exact duplicate of https://github.com/camunda/camunda-modeler/issues/672, right?

Needs to be fixed via https://github.com/bpmn-io/bpmn-js/issues/718.

**Closed by nikku** 2019-02-12 16:28 UTC
Labels: duplicate
