### ISSUE TITLE
I can open the referenced process' BPMN file right from a Call Activity

### ISSUE THREAD

**Issue by sebwarnke** [camunda/camunda-modeler#1885] opened 2020-07-20 13:34 UTC
__Is your feature request related to a problem? Please describe.__
In Camunda Modeler one can not easily access the process that is referenced in a call activity by the called element field. As a consequence it is hard to find the called process definition.

__Describe the solution you'd like__
In case called element contains a static process definition key Camunda Modeler shall resolve the key to a process definition. This might be initially implemented with a file naming convention where the bpmn file name equals the key.

If called element contains an expression the resolution is not possible, of course.

__Describe alternatives you've considered__
Using Cawemo like this:
![Kapture 2020-07-20 at 15 32 58](https://user-images.githubusercontent.com/26740468/87943446-58b32380-ca9e-11ea-9143-f778f5f79fd2.gif)

Without Cawemo there is just no other way.

**Comment by philippfromme** [comment] 2023-03-01 21:58
Duplicate of https://github.com/camunda/camunda-modeler/issues/112.

**Closed by philippfromme** 2023-03-01 21:58 UTC
Labels: BPMN, enhancement, backlog
