### ISSUE TITLE
As user I can use the space tool to move elements which belong to the same scope only

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1212] opened 2019-02-12 14:31 UTC
// given 
see attached screen cast

// when
I use the space tool in order to create more space in the upper pool

// then
I influence the elements in the second pool too

// expected behavior
the space tool is limited to scope where it is used. For example a pool or a sub process. 

![1212 space tool only applied to one scope](https://user-images.githubusercontent.com/232571/52642509-7197cc80-2edb-11e9-919a-8e8070cd7d61.gif)

**Comment by nikku** [comment] 2019-02-12 14:56
Duplicate of https://github.com/camunda/camunda-modeler/issues/876.

**Closed by nikku** 2019-02-12 14:56 UTC
