### ISSUE TITLE
Timer documentation link opens up twice

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2905] opened 2022-04-08 09:32 UTC
__Describe the Bug__

When we try to open up the documentation for timers the exact same link opens up twice.

__Steps to Reproduce__

1. Create a timer event
2. open up the properties panel for the same and click on "Documentation: Timer events" under Timer.
3. We could see that the documentation link opens up twice

__Expected Behavior__

The link leading to documentation on timer events should open up once.

__Environment__

- OS: [ Windows 10]
- Camunda Modeler Version: [5.0.0]
- Execution Platform: [ Camunda Platform, Camunda Cloud]

https://user-images.githubusercontent.com/85225325/162408343-aba9996a-3a0f-4827-9fbe-279efd301fae.mp4

**Comment by barmac** [comment] 2022-04-08 12:04
I can reproduce it on Mac.

**Comment by marstamm** [comment] 2022-04-08 12:04
Also reproduceable on Linux with all other links in the properties panel (User Task, Multi-Instance Task)

Links in What's new don't seem to be affected

**Comment by barmac** [comment] 2022-04-08 12:05
...and I can't reproduce it in 4.12. So it's a regression.

**Comment by barmac** [comment] 2022-04-08 12:22
We trigger two events in the properties panel:

```
[new-window] new window to https://docs.camunda.org/manual/latest/reference/bpmn20/events/timer-events/#time-duration
[will-navigate] navigating to https://docs.camunda.org/manual/latest/reference/bpmn20/events/timer-events/#time-duration
```

**Comment by barmac** [comment] 2022-04-08 12:25
The reason for that is we use `target=_blank` in the properties panel. In What's new, we don't

**Comment by marstamm** [comment] 2022-04-08 15:13
fixed with https://github.com/camunda/camunda-modeler/pull/2911

**Closed by marstamm** 2022-04-08 15:13 UTC
Labels: bug, needs review, BPMN, impact:low
