### ISSUE TITLE
BPMN Properties Panel cannot be opened

### ISSUE THREAD

**Issue by hg9102** [camunda/camunda-modeler#1435] opened 2019-07-23 22:07 UTC
__Describe the Bug__

Cannot read property 'open' of undefined
    at open (webpack:///src/app/tabs/bpmn/BpmnEditor.js:557:39)
    at triggerAction (webpack:///src/app/tabs/MultiSheetTab.js:269:18)
    at triggerAction (webpack:///src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack:///src/app/App.js:1506:15)
    at fn (webpack:///src/app/App.js:2025:19)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:55:57975
    at exec (webpack:///src/app/AppParent.js:68:11)
    at EventEmitter.emit (events.js:182:13) [ error ]

__Environment__

 - OS: MacOS 10.13.4
 - Camunda Modeler Version: 3.2.1.3865

**Comment by barmac** [comment] 2019-07-24 07:41
Can you describe the context in which the error appeared?

It might also be helpful if you attach the logs available via Console (preinstalled Mac application). You can find the log in `~/Library/Logs/Camunda Modeler` directory.

**Comment by nikku** [comment] 2019-07-30 07:41
We cannot reproduce your problem.

Closing this issue dues to missing feedback.

**Closed by nikku** 2019-07-30 07:41 UTC
Labels: invalid
