### ISSUE TITLE
File changed externally dialog opens twice on editor focus

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1118] opened 2019-01-17 15:28 UTC
__Reproduce__

1. Change file externally
2. Go back to Camunda Modeler

__Expected Behavior__

1. Dialog shown once

__Actual Behavior__

1. Dialog shown twice

![2019-01-17_16-26-45](https://user-images.githubusercontent.com/7633572/51328943-b95e3c00-1a74-11e9-90c8-5869d1e37591.gif)

---

Related to https://github.com/camunda/camunda-modeler/issues/468, [`SUPPORT-4636`](https://app.camunda.com/jira/browse/SUPPORT-4636)

**Comment by pinussilvestrus** [comment] 2019-01-23 12:15
I was not able to reproduce it on `macOS@10.14.2`. The dialog only opened once, despite I switched the focus a couple of times (as it's described in #468).

![jan-23-2019 13-14-28](https://user-images.githubusercontent.com/9433996/51605971-daa9a700-1f10-11e9-8b9a-b8911c587d91.gif)

Are there additional actions needed to reproduce it?

**Comment by nikku** [comment] 2019-01-23 17:17
Possible duplicate of https://github.com/camunda/camunda-modeler/issues/413.

**Comment by nikku** [comment] 2019-01-31 12:17
@pinussilvestrus What about solving this on the method level instead of introducing complex state related operations:
```js
async function doWithTab(tab) {
  // do anything here...
}


/**
 * This wraps the given async fn and ensures
 * it may only be executed serially.
 * 
 * The promise for the currently running execution will be
 * cached. The function will only be re-evaluated once 
 * a running execution got completed.
 * 
 * @param  {AsyncFunction} fn
 * 
 * @return {Promise<?>} promise for the to-be result
 */
async function justOnce(fn) {
  
  const runningCache = {};

  return function(tab) {

    const { id } = tab;

    if (runningCache[id]) {
      return runningCache[id];
    }

    const promise = fn(tab);

    runningCache[id] = promise;

    promise.finally(() => runningCache[id] = false);

    return promise;
  };
}

const onlyOnceDoWithTab = justOnce(doWithTab);
```

**Closed** 2019-02-06 19:03 UTC
Labels: bug, channel:support, needs review, platform:Windows
