### ISSUE TITLE
Moving a text field below a button results in error

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2197] opened 2021-04-08 12:45 UTC
__Describe the Bug__

Given the following example form

```json
{
  "type": "default",
  "components": [
    {
      "key": "textfield1",
      "label": "Text Field",
      "type": "textfield"
    },
    {
      "key": "textfield2",
      "label": "Text Field",
      "type": "textfield"
    },
    {
      "key": "button6",
      "label": "Button",
      "type": "button"
    }
  ]
}
```

and moving the first text field below the button, the text field got erased from the editor. Also, an error is displayed in the Developer Console.

![Kapture 2021-04-08 at 14 41 32](https://user-images.githubusercontent.com/9433996/114028404-baa7f900-9878-11eb-8fa2-6be709c266e0.gif)

![image](https://user-images.githubusercontent.com/9433996/114028384-b67bdb80-9878-11eb-90ee-7bb9fcae985d.png)

__Steps to Reproduce__

1. Open example form from above
2. Drag & drop the first text field to the very bottom
3. Recognize the text field is lost
4. Notice the text field is still persisted in the JSON view

__Expected Behavior__

Moving the text field should work without problems.

__Environment__

- OS: MacOS 10.15
- Camunda Modeler Version: 4.7.0-rc.0

**Comment by philippfromme** [comment] 2021-04-08 12:56
I cannot reproduce this. Do you have a way of reproducing this 100% or is it just failing sometimes?

**Comment by pinussilvestrus** [comment] 2021-04-08 12:58
It fails for me any time I try it:

1. Create new form
2. Create text field
3. Create another text field
4. Create button
5. Try to move any text field below the button

**Comment by pinussilvestrus** [comment] 2021-04-08 13:02
Some capture - it also feels as drag & drop is not 100% reliable on my machine (blue drop indicator is not showing up all the time).

![Kapture 2021-04-08 at 15 00 12](https://user-images.githubusercontent.com/9433996/114031041-41f66c00-987b-11eb-9c3e-775d43e3d07a.gif)

Maybe dragula has some difficulties on Mac?

**Comment by philippfromme** [comment] 2021-04-08 13:05
Okay, I can reproduce it sometimes, when the blue indicators are not showing which is really weird. I guess we'll have to drop (no pun intended) dragula even earlier than expected.

**Comment by MaxTru** [comment] 2021-04-09 08:49
Same on Linux: the blue drop indicator rarely appears
![elementDropping](https://user-images.githubusercontent.com/42800119/114155014-4bd2aa80-9921-11eb-9796-dd605014dc1c.gif)

**Comment by MaxTru** [comment] 2021-04-12 08:36
Closed by https://github.com/camunda/camunda-modeler/pull/2205

**Closed by MaxTru** 2021-04-12 08:36 UTC
Labels: Forms, bug, needs review
