### ISSUE TITLE
FEEL Editor counts empty space and displays the wrong error message

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3128] opened 2022-09-09 12:00 UTC
### Describe the bug

The Feel editor (for the message task here) counts the empty space and displays the error message "syntaxError:expression expected" rather " "subscription correlation key must be defined" should be the valid one. This issue also happens depending on the order of the deletion of the contents in the field. See attachment for example

### Steps to reproduce

1. Create a receive message task
2. Select a Global message reference and click on the Subscription correlation key field
3. Enter the following text 
{
"hello"
{
4. Delete the first brace and the text hello first and later delete the last curly brace
5. We could see that the empty space before the braces is counted and the error message  "syntaxError:expression expected" is thrown.

Expected error based on the order of deletion

1. Normal deletion :

https://user-images.githubusercontent.com/85225325/189345043-d1e62f01-cd84-4a38-82d4-75540cfdf2b5.mp4

2. Differed order of deletion

https://user-images.githubusercontent.com/85225325/189345121-f20086d3-66db-4e70-9306-80108361e190.mp4

### Expected behavior

when there is no content at all in the field the error message should be "subscription correlation key must be defined" Hance emepty spaces should not be counted for text

### Environment

- OS: [ Windows 10]
- Camunda Modeler Version: [5.3.0]
- Execution Platform: [ Camunda Cloud]

**Comment by pinussilvestrus** [comment] 2022-09-12 11:06
What are our thoughts on this @christian-konrad ? I think you could argue whitespaces are already expressions.

@marstamm already explained that this could be even expected behavior.

**Comment by marstamm** [comment] 2022-09-12 11:19
Sorry for not commenting on this earlier. My reasoning is: whitespace is considered a value by the engine and we persist it, therefore we need linting on whitespace as well.

When editing the FEEL expression, I would expect to get hints on syntax error on what I types. Being that an empty expression with whitespace is invalid, the error message here is consistent behavior. It would also fail on deployment, so I expect to get an error message. 

Counter-argument: just whitespace should not be considered an expression and just be treated as `null`

**Comment by nikku** [comment] 2022-09-19 16:28
What is our resolution regarding this one? Let us make a pragmatic decision => We don't trim whitespace (discussed in the past), hence we need to regard it as a vaild expression.

**Comment by barmac** [comment] 2022-10-21 15:03
@GeethaParthasarathy @christian-konrad Let's have a decision whether we want to do anything regarding this or not.

**Comment by christian-konrad** [comment] 2022-10-21 16:46
Two situations:
- A user enters some stuff, deletes everything other than whitespaces -> the message shows that this is an invalid expression -> this is expected, since the user is aware of their changes
- A user did this but did not fix it. They leave the diagram and another user enters it to edit it. This user will see a lint error, directing them to fix the syntax error. This is the right thing because it makes them aware that there is some problem in the expression (just whitespaces), before they think the subscription key is missing and appending or prefixing it to the white spaces, which causes even more problems.

Thus, we should do nothing and I close the issue for now @barmac @GeethaParthasarathy

**Closed by christian-konrad** 2022-10-21 16:46 UTC
Labels: bug, help wanted, PM
