### ISSUE TITLE
Template with conditions does not apply default values correctly when applied to an existing element

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4124] opened 2024-02-08 12:56 UTC
### Describe the bug

The Modeler does not apply specified properties from a JSON template to the BPMN model correctly to an existing element.

It applies the template correctly when templated element is created/appended right away.

### Steps to Reproduce

1. Configure Modeler with the provided JSON template and bpmn files : 
 - add `add-item.bpmn` to `test/fixtures/diagrams`
<details>
  <summary>add-item.bpmn click to expand!</summary>

  ```bpmn
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_1c27vni" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.16.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.3.0">
  <bpmn:process id="Process_0hqfcqr1" isExecutable="true">
    <bpmn:task id="ServiceTask" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_0hqfcqr1">
      <bpmndi:BPMNShape id="Activity_di" bpmnElement="ServiceTask">
        <dc:Bounds x="160" y="80" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>

```
</details>

 - add `add-item_expected.bpmn` to `test/fixtures/diagrams`
 <details>
  <summary>add-item_expected.bpmn click to expand!</summary>

  ```bpmn
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_1c27vni" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.16.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.3.0">
  <bpmn:process id="Process_0hqfcqr1" isExecutable="true">
    <bpmn:serviceTask id="ServiceTask" zeebe:modelerTemplate="05d1c06a-b65d-428c-8ca0-10c14b3fb0ee" zeebe:modelerTemplateVersion="3">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="io.camunda:aws-dynamodb:1" />
        <zeebe:ioMapping>
          <zeebe:input source="itemOperation" target="input.operationGroup" />
          <zeebe:input source="addItem" target="input.itemOperation" />
          <zeebe:input source="tableName" target="input.tableName" />
          <zeebe:input source="={&#34;id&#34;:&#34;value&#34;}" target="input.item" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
      <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_0hqfcqr1">
          <bpmndi:BPMNShape id="Activity_1rrhra2_di" bpmnElement="ServiceTask">
              <dc:Bounds x="160" y="80" width="100" height="80" />
          </bpmndi:BPMNShape>
      </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>

```
</details>

2. Apply the template to an existing element

Observe that properties related to DynamoDB operations, such as tableName and item, are not applied as expected. : 
<img width="1174" alt="Screenshot 2024-02-07 at 13 27 29" src="https://github.com/bpmn-io/element-templates-cli/assets/108869886/2fa11d66-185f-4349-8a69-f41a23b0cc43">

### Expected Behavior

Modeler should correctly include all specified properties from the JSON template. This includes inputs for tableName and item, allowing for proper interaction with DynamoDB within the process.

### Environment

- OS: MacOS
- Camunda Modeler Version: 5.18.0 and later
- Execution Platform: Camunda 8
- Installed plug-ins: [...]

### Additional context

Reported by @Oleksiivanov in https://github.com/bpmn-io/element-templates-cli/issues/15

**Comment by barmac** [comment] 2024-02-08 13:04
This was introduced in v5.18

**Comment by barmac** [comment] 2024-02-08 13:09
This can be related https://github.com/bpmn-io/bpmn-js-element-templates/issues/49

**Comment by marstamm** [comment] 2024-02-13 09:42
Both https://github.com/bpmn-io/bpmn-js-element-templates/issues/49 and this issue seem to be caused by the same root cause.

To Replicate, have the following template properties:

| Property | default value | Condition   | Value when applied | expected? |
|----------|-------|-------------|--------------------|---|
| prop1    | foo   | -           | foo                | ✅  |
| prop2    | bar   | prop1 = foo | bar                |✅   |
| prop3    | baz   | prop2 = bar | -                  | ❌  |

It seems like we do not apply default values correctly when we have nested conditions. The conditions only become true while we are applying the template.

**Comment by nikku** [comment] 2024-02-14 09:32
@marstamm Did you close this my accident? Let's re-open and close only if fully integrated.

**Comment by marstamm** [comment] 2024-02-14 10:00
This was automatically closed by Github, this was not the intention

**Closed** 2024-02-23 08:53 UTC
Labels: bug, needs review, element templates
