### ISSUE TITLE
Without file extension Camunda 8 diagrams save with `.cloud-bpmn` extension

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4661] opened 2024-11-04 07:53 UTC
### Describe the bug

Camunda 8 diagram saves as `{NAME}.cloud-bpmn` when no file extension was explicitly provided.

### Steps to reproduce

1. Create a new Camunda 8 diagram
2. Save diagram with `{NAME}`, __provide no extension__
4. See that resulting file name is `{NAME}.cloud-bpmn`

### Expected behavior

Every BPMN diagram saves as `{NAME}.bpmn`. We analyze the diagram to deduce whether it is a Camunda 8 or Camunda 7 diagram.

### Environment

- OS: Linux
- Camunda Modeler Version: v5.29.0
- Execution Platform: Camunda 8
- Installed plug-ins: None

**Comment by abdul99ahad** [comment] 2024-11-04 08:15
I can reproduce this issue. If no format is specified, the file will be saved as `*.cloud-bpmn`

**Comment by philippfromme** [comment] 2024-11-04 08:18
I cannot reproduce this on Windows as I am not allowed to save a file without a valid extension.

**Comment by abdul99ahad** [comment] 2024-11-04 12:32
@nikku This behavior occurs because, if no type is specified, the default type will be inferred based on the diagram. For Camunda 8, this default will be cloud-bpmn.

**Question**: Should we unify the diagram type for both Camunda 7 and 8, or keep them distinct?

**Unified Approach:** Use a single diagram type for both versions, allowing us to apply the same type across Camunda 7 and 8.
**Separate Types:** Use bpmn for Camunda 7 and cloud-bpmn for Camunda 8, only adjusting the file extension accordingly.

Let me know if you'd prefer a unified or separate approach here.

**Comment by nikku** [comment] 2024-11-04 14:00
I think we _have_ to go for 

> **Separate Types**: Use bpmn for Camunda 7 and cloud-bpmn for Camunda 8, only adjusting the file extension accordingly.

Because `type` is the type of file from the editor point of view, not from the extension point of view.

**Closed** 2024-11-05 20:31 UTC
Labels: bug, needs review, platform:Darwin, platform:Linux, good first issue, spring cleaning
