### ISSUE TITLE
Unintuitive correlation of `optional` and `constraints.regex` with `constraints.notEmpty`

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-modeler#4314] opened 2024-05-27 10:57 UTC
### Describe the bug

When I try to define a field in an element template that:

* is validated by a regex
* but may remain empty

The regex itself allowing an empty field is not enough. Also, setting the constraint `constraints.notEmpty` is not enough.
You will have to set `optional`.

### Steps to reproduce

1. use this property and add it to an element template (use the web modeler for real time testing):

```json

  {
      "id": "ccPostfach",
      "label": "Email-CC",
      "description": "CC (comma separated) where to send the mail",
      "constraints": {
        "pattern": {
          "value": "^([a-zA-Z0-9._%+-]+@(gmail\\.com),?\\s?)*$",
          "message": "Must be a gmail address"
        },
        "notEmpty": false
      },
      "feel": "optional",
      "group": "default",
      "binding": {
        "name": "cc",
        "type": "zeebe:input"
      },
      "type": "String"
  }

```

2. The validation will fail on an empty field and show the error message from the pattern (although the pattern itself works with an empty string)
3. Now, add `"optional": true` as field to the property
4. This works as expected

### Expected behavior

Either `optional` or `constraints.notEmpty` is required, not both. Also the opposite boolean logic of the two fields makes editing unintuitive.

### Environment

- OS: not relevant
- Camunda Modeler Version: Web Modeler 8.5.0
- Execution Platform: Camunda 8
- Installed plug-ins: not relevant

### Additional context

Internal slack thread: https://camunda.slack.com/archives/C0693F1NFK5/p1716536237030329

**Comment by sephiroth-j** [comment] 2024-05-28 07:08
Not to mention that it not possible to add `"notEmpty": false` [with the template generator](https://github.com/camunda/connectors/blob/7a6bdcc9a29c38b53aa31f957e6b171e1060c0e8/element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/JakartaValidationFieldProcessor.java#L37-L39).

**Comment by barmac** [comment] 2024-06-10 09:01
Hi,

Thanks for your report. I'd like to understand better your requirements.

You wrote:

> When I try to define a field in an element template that:
> * is validated by a regex
> * but may remain empty

Do you expect the empty value to still be reflected in the XML, or should the property be not present there at all? The latter is what `optional` property means.

**Comment by nikku** [comment] 2024-06-17 09:28
@jonathanlukas At this point I assume the bottom of the issue is that `regex` and `notEmpty` validations are not magically playing with each other.

If you specify `notEmpty: false` then you'd in addition need to ensure that the pattern handles an empty input, too. This can usually be easily accomplished: `^(|my patter matching everything)$`.

**Comment by nikku** [comment] 2024-06-21 05:57
Closing this as won't fix. If there is anything we missed (in [prior](https://github.com/camunda/camunda-modeler/issues/4314#issuecomment-2157765424) [feedback](https://github.com/camunda/camunda-modeler/issues/4314#issuecomment-2172858943)), please chime in.

**Closed by nikku** 2024-06-21 05:57 UTC
Labels: bug, ux, element templates
