### ISSUE TITLE
Properties panel disappears when hidden in DMN table

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1114] opened 2019-01-16 14:57 UTC
__Describe the Bug__

Property panel becomes inaccessible in the table view when it's hidden.

__Steps to Reproduce__

![disappearing_properties_panel](https://user-images.githubusercontent.com/28307541/51257103-30c59a00-19a7-11e9-83ac-1b5c32214e56.gif)

__Expected Behavior__

Properties panel should be either completely hidden in the table view or still accessible after hiding.

__Environment__

 - OS: MacOS 10.14.2
 - Camunda Modeler Version: `master@2.2.4`; same on `next`

**Comment by nikku** [comment] 2019-01-16 15:13
This is a feature, not a bug.

We decided to not display the drop out in the past to not interfere with table editing.

**Comment by philippfromme** [comment] 2019-01-17 07:52
I've discussed this with @barmac and explained the reasoning behind it.

**Comment by nikku** [comment] 2019-01-17 08:16
Closing this issue, as this is the decided-upon state.

Happy to re-open if we receive additional input on the matter.

**Comment by nikku** [comment] 2019-03-25 08:57
Reopening this, as we get quite frequent feedback reporting this as a bug (https://github.com/camunda/camunda-modeler/issues/1248, https://github.com/camunda/camunda-modeler/issues/1330).

We need to have a way to open it / re-open it from the UI.

**Comment by philippfromme** [comment] 2020-06-05 07:28
Will be fixed as part of camunda/camunda-modeler#1811.

**Comment by MaxTru** [comment] 2020-09-07 14:49
This was fixed (as @philippfromme stated) with #1811

**Closed by MaxTru** 2020-09-07 14:49 UTC
Labels: DMN, backlog, enhancement, ux
