### ISSUE TITLE
Confusion when adding a message start event

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2229] opened 2021-04-23 14:15 UTC
__Describe the Bug__

After adding a message start event I don't know if the plus sign next to Initiatior adds a new initiator or a new message.

![grafik](https://user-images.githubusercontent.com/7870843/115883994-b40bab00-a44e-11eb-99b9-5965d954c51a.png)

__Steps to Reproduce__

Create a new start event, morph it to a message and open the property panel. Try to add a new message into the Details.
__Expected Behavior__

Some kind of visual separation between the plus and the Initiator label.

Best would be to move the initiator in a new line.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.7.0

**Comment by ingorichtsmeier** [comment] 2021-04-23 16:59
Seems to be related to the user-task-generated-form plugin: 
https://github.com/camunda-consulting/code/tree/master/snippets/camunda-modeler-plugins/camunda-modeler-plugin-usertask-generatedform-preview

After removing, it looks good.

Maybe you have an idea which css is responsible for this behavior?

**Comment by nikku** [comment] 2021-04-23 17:09
You may inspect the running app (and the `x` button specifically) using the Chrome DEV tools if you press `F12`. It should be fairly straight forward to see which styles from the plug-in interfere with the handle.

Closing this issue, as it is caused by a plug-in.

**Closed by nikku** 2021-04-23 17:09 UTC
Labels: bug
