### ISSUE TITLE
Collapsing a pool breaks sequence flow layout

### ISSUE THREAD

**Issue by Abendstolz** [camunda/camunda-modeler#1033] opened 2018-11-27 16:08 UTC
__Describe the Bug__

Collapsing a pool (kinda) breaks rendering (increases height of whole diagram by an unhealthy amount)

![process before collapsing](https://user-images.githubusercontent.com/26351327/49094859-82835b00-f267-11e8-9c13-b998c069801b.png)

![process after collapsing - rendering bug](https://user-images.githubusercontent.com/26351327/49094487-ae521100-f266-11e8-9021-910b4e923c77.png)

__Steps to Reproduce__

Steps to reproduce the behaviour:

0. Open [example diagram](https://github.com/camunda/camunda-modeler/files/2629369/BpmnReplace.poolMessageFlows.bpmn.txt)
0. Collapse any participant
0. Left over sequence flow has funny behavior

__Expected Behaviour__

Sequence flow is re-layouted _or_ removed entirely _?_.

__Environment__

Please complete the following information:
 - OS: 16.04.1-Ubuntu (but same on MacOS something)
 - Camunda Modeler Version: `>= 2.0`

----

@nevries  fyi, not that I think it's important, but maybe the MacOS version can be added by you, if necessary.

Archive containing original broken diagram: [camunda_modeler_2.2.1_bug_report.zip](https://github.com/camunda/camunda-modeler/files/2620775/camunda_modeler_2.2.1_bug_report.zip)

**Comment by barmac** [comment] 2018-11-29 08:52
Confirmed also with `2.2.0`, `2.2.2`, `2.1.2`, `2.0.3` and `2.0.0` on `macOS@10.14.1`. It seems like the last version which didn't have this bug was `1.16.2`.

**Comment by nikku** [comment] 2018-11-29 10:00
I'll have a look into this one.

**Comment by nikku** [comment] 2018-11-29 13:58
![image](https://user-images.githubusercontent.com/58601/49226491-0f085780-f3e7-11e8-8729-c5354b5c71d3.png)

:hushed:

Most simple diagram to reproduce this: [BpmnReplace.poolMessageFlows.bpmn.txt](https://github.com/camunda/camunda-modeler/files/2629369/BpmnReplace.poolMessageFlows.bpmn.txt)

**Comment by nikku** [comment] 2018-11-29 14:04
This is not a bug but a feature. 

Consider the rendered diagram: 

![image](https://user-images.githubusercontent.com/58601/49226774-d157fe80-f3e7-11e8-9b0b-01d05a1e193e.png)

Both message flows are being joined as `Task_A` is being removed. They are not parallel to each other but cross each other at `{ x: 366, y: -7906 }`. Because of this the are being joined at that coordinate before being transformed to a `bpmn:SequenceFlow` later in the process.

You could argue that what is shown to the user is not a practical though.

:walking_man:

**Comment by nikku** [comment] 2018-11-29 15:00
Moving this back to our backlog and flagging it as a potential improvement.

**Comment by nikku** [comment] 2018-11-29 15:08
@Abendstolz What should be the desired behavior after the pool is collapsed, given the example diagram I pasted above: (A) Sequence Flow is gone _or_ (B) Sequence Flow is now looping around remaining task.

**Comment by nevries** [comment] 2018-11-29 22:39
@nikku I'm a bit lost, why does the current implementation create a sequence flow out of the two message flows at all? From a modelling perspective, that makes no sense to me, or am I missing something?

**Comment by nikku** [comment] 2018-11-30 07:53
You are opting for: (A) Sequence Flow is gone.

In this case you could argue there is a bug that causes this behavior. We should not attempt to join message flows and remove them on pool collapsing.

**Comment by nikku** [comment] 2018-11-30 08:34
Relevant toolkit bug ticket: https://github.com/bpmn-io/bpmn-js/issues/917

**Comment by nikku** [comment] 2018-11-30 08:49
Reclassified this as a bug.

**Comment by nikku** [comment] 2018-11-30 10:11
Closed via https://github.com/camunda/camunda-modeler/commit/66d579c6c7748689b7752467366896e1f092b0bc.

**Closed by nikku** 2018-11-30 10:11 UTC
Labels: BPMN, bug, modeling

**Comment by nikku** [comment] 2018-11-30 12:10
Fixed in Camunda Modeler `v2.2.3`.
