### ISSUE TITLE
No template chooser for CallActivity template

### ISSUE THREAD

**Issue by Cruiser79** [camunda/camunda-modeler#3001] opened 2022-06-23 13:20 UTC
### Describe the bug

If i create a task template, which should switch to a callactivity task, this template is not shown in template chooser.

Use this sample.json file
```JSON    
{
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema/resources/schema.json",
    "name": "Caller All IO",
    "id": "com.camunda.example.CallerAllIO",
    "appliesTo": [
      "bpmn:Task"
    ],	
	"elementType": {
      "value": "bpmn:CallActivity"
    },
    "properties": [
      {
        "label": "Called Process",
        "type": "String",
        "editable": false,
        "value": "calledProcess",
        "binding": {
          "type": "property",
          "name": "calledElement"
        }
      },
      {
        "label": "Input all",
        "type": "Hidden",
        "binding": {
          "type": "camunda:in",
          "variables": "all"
        }
      },
      {
        "label": "Output all",
        "type": "Hidden",
        "binding": {
          "type": "camunda:out",
          "variables": "all"
        }
      }
    ]
  }
```

### Steps to reproduce

1. Create a sample.json with following content
2. Open Modeler 5.0.0
3. Create a BPMN Camunda Platform 8.0 document
4. Create a task node
5. Open task properties, no template chooser is displaying

### Expected behavior

Due to the flags appliesTo=bpmn:Task there should now be displayed the template chooser and the task should ne switch to a callactivity (because of elementType=bpmn:CallActivity)

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.0.0
- Execution Platform: -
- Installed plug-ins: -

**Comment by smbea** [comment] 2022-06-24 07:40
Duplicate of https://github.com/camunda/camunda-modeler/issues/3000

**Closed** 2022-06-24 13:19 UTC
Labels: bug
