### ISSUE TITLE
Properties panel and XML not in sync

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-modeler#474] opened 2016-11-30 10:07 UTC
Modeler version: 1.5.0 (64 bit)
Platform: Windows 7 64 bit

I sometimes observe that I edit properties, then hit Ctrl + S, and they are not completely reflected in the XML, neither in the file system nor in the modeler's XML view. This is quite annoying to discover at process runtime.

Can't reproduce it reliably at the moment.

I.e. I reach the following state:

![snippet1](https://cloud.githubusercontent.com/assets/586648/20748091/28b286ee-b6ed-11e6-887c-bb4e8da124b2.PNG)

![snippet2](https://cloud.githubusercontent.com/assets/586648/20748110/35adb242-b6ed-11e6-8c53-97830b6320c3.PNG)

**Comment by nikku** [comment] 2016-12-01 15:32
I cannot reproduce your changes. Try to check the developer console (`F12` inside the application) whenever you experience the bug again. Maybe there is some error logging that provides a bit more context.

**Comment by ThorbenLindhauer** [comment] 2016-12-05 10:13
I just tried reproducing and succeeded somewhat randomly. The console shows no error, though. I'll try to find a usage pattern that triggers this.

**Comment by benhoffmann** [comment] 2017-01-10 13:48
I encountered this behavior before and somehow figured out that I shouldn't hit Ctrl+S right after typing but wait a second or two. I don't know if that is the real cause, though.

**Comment by nikku** [comment] 2017-01-30 15:54
Yes, if you guys are super fast typers, you may get into sticky situations where:

* you typed something
* you switch to the XML tab immediately
* the typed action is _updated_ (delayed by a few ms)
* you do not see the stuff updated in XML

**Comment by nikku** [comment] 2018-02-26 15:02
Closing this, as this is an edge case that revolves around using our properties panel together with fast (< 300ms) saving / tab switching.

**Closed by nikku** 2018-02-26 15:03 UTC
Labels: bug, help wanted
