### ISSUE TITLE
Changed decision ID not persisted

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#544] opened 2017-03-06 12:50 UTC
Reproduce:
create new decision table
enter name and id
save dmn file

Problem:
new id was not persisted

**Comment by philippfromme** [comment] 2017-08-07 07:32
Can't reproduce using Camunda Modeler 1.9.0 (Windows 10). Maybe @pedesen could check this out.

**Comment by pedesen** [comment] 2017-08-07 07:41
Can't reproduce either (Camunda Modeler 1.9.0, Linux Mint).

**Comment by philippfromme** [comment] 2017-08-09 11:44
Definition ID is updated on [blur](https://github.com/bpmn-io/dmn-js/blob/master/lib/features/definition-id/DefinitionIdEdit.js#L36) so the ID not being persisted during editing is desired behavior. I'll close this ticket, I created a [new ticket](https://github.com/bpmn-io/dmn-js/issues/222) for discussion about changing the current behavior (e.g. updating not on blur but on input similar to bpmn-js-properties-panel).

**Closed by philippfromme** 2017-08-09 11:44 UTC
Labels: bug, DMN, ready
