### ISSUE TITLE
camunda-modeler4.11 unable to start on platform Ubuntu18.04

### ISSUE THREAD

**Issue by wangwanchao** [camunda/camunda-modeler#2598] opened 2021-11-30 10:55 UTC
OS
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
ldd
```
ldd --version
ldd (GNU libc) 2.30
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
bug
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to load /home/administrator/Downloads/camunda-modeler4.11/resources/app.asar/node_modules/grpc/src/node/extension_binary/electron-v12.0-linux-x64-glibc/grpc_node.node. /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.340gn3)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/administrator/Downloads/camunda-modeler4.11/resources/app.asar/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```
The older glibc version is 2.27. and camunda-modeler4.8 worked well. Then I try to upgrade glibc to ver 2.30,but it not work.

**Comment by nikku** [comment] 2021-11-30 11:20
@MaxTru is this something you can reproduce?

**Comment by wangwanchao** [comment] 2021-12-01 01:29
> 

[This post](https://stackoverflow.com/questions/68808530/camunda-modeler-a-javascript-error-occurred-in-the-main-process-version) maybe helps.

**Comment by MaxTru** [comment] 2021-12-01 15:06
> @MaxTru is this something you can reproduce?

I am on arch linux and cannot reproduce this.

According to https://github.com/JoshuaWise/better-sqlite3/issues/403 this might be caused by the ubuntu distro building the artifact. Not sure though.

Have you tried to build Camunda Modeler locally? ie.
```
npm i
npm run dev
```

or

```
npm i
npm run build
```

**Comment by wangwanchao** [comment] 2021-12-02 15:16
No, I just download binary package from [website](https://camunda.com/download/modeler/). I will try it tomorrow and get it back to you.

**Comment by nikku** [comment] 2021-12-02 20:14
There exists a number of resolutions for [Ubuntu 18 and GLIBC 2.29](https://duckduckgo.com/?q=ubuntu+18+GLIBC_2.29&ia=web). To start the latest Camunda Modeler on Ubuntu, you either have to upgrade to Ubuntu LTS 20 _or_ manually install a recent GLIBC version.

Closing this issue.

**Closed by nikku** 2021-12-02 20:14 UTC
Labels: bug
