### ISSUE TITLE
Linux distribution - JS error on run

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#426] opened 2016-10-11 22:22 UTC
Getting a JS error when running to run the 32bit and 64 bit Linux distros of the modeler:

```
A JavaScript error occurred in the main process
Uncaught Exception:
/mnt/workspace/project/folder1/folder2/site/src/camunda-modeler/camunda-modeler:1
(function (exports, require, module, __filename, __dirname, process, global) { ELF
                                                                              ^
SyntaxError: Invalid or unexpected token
   at Object.exports.runInThisContext (vm.js:76:16)
   at Module._compile (module.js:528:28)
   at Object.Module._extensions..js (module.js:565:10)
   at Module.load (module.js:473:32)
   at tryModuleLoad (module.js:432:12)
   at Function.Module._load (module.js:424:3)
   at loadApplicationPackage (/usr/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:288:12)
   at Object.<anonymous> (/usr/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:330:5)
   at Module._compile (module.js:556:32)
   at Object.Module._extensions..js (module.js:565:10)
```

Any ideas?

**Comment by nikku** [comment] 2016-10-12 09:15
Which version are you referring to `v1.3.2`?

**Comment by nikku** [comment] 2016-10-12 09:18
Cannot reproduce this with latest nightly and release on Arch Linux.

**Comment by StephenOTT** [comment] 2016-10-12 13:49
>Which version are you referring to v1.3.2?

@nikku yes were using 1.3.2 32 and 64 bit.

Any special install instructions for linux?

**Comment by nikku** [comment] 2016-10-12 14:54
You need to make sure you download and run the Camunda Modeler on Linux responding to your OS architecture (running 32bit on a 64bit architecture won't work).

Will close this for now as we cannot reproduce this (we got at least five different Linux variants in testing that work out nicely).

Please provide us with some details on your operating system / environment. That may help us to turn this issue into a reproducible bug report.

**Comment by StephenOTT** [comment] 2016-10-12 14:55
Will test nightly and report back.  THanks @nikku

**Closed by nikku** 2016-10-12 14:54 UTC
Labels: bug, release

**Comment by StephenOTT** [comment] 2016-10-20 14:58
@nikku it was a issue with the "release".  When we tried the nightly it worked as expected.

Thanks
