### ISSUE TITLE
While trying to cancel saving a diagram ,leaves the entire diagram closed.

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2359] opened 2021-07-08 14:39 UTC
__Describe the Bug__

While trying to cancel saving a diagram ,leaves the entire diagram closed.

__Steps to Reproduce__

1. Open a new diagram in the modeler.
2. Make some changes to it.
3. Try to close the diagram.
4. Now you are prompted to save the diagram ->click on save.
5. In the dialog click on Cancel.
6. The entire diagram is closed.

__Expected Behavior__

While cancelling on saving a diagram the entire diagram should not be closed since it should act different form the don't save option.There are chances that the user might make some more editions and save the diagram again.

__Environment__

- OS: Windows 10
- Camunda Modeler Version:4.9.0
- Execution Platform:Camunda Platform/Camunda cloud
- Installed plug-ins: [...]
https://user-images.githubusercontent.com/85225325/124941235-f59e0200-e00a-11eb-9026-3affa3c22c7e.mp4

**Comment by MaxTru** [comment] 2021-07-08 20:12
Interesting issue!

I cannot reproduce in Linux:
![CancelSave](https://user-images.githubusercontent.com/42800119/124984423-7ecc2d80-e039-11eb-8728-e114de99a843.gif)

@philippfromme can you reproduce?

**Comment by barmac** [comment] 2021-07-09 07:27
I can reproduce it in both 4.9.0 and 4.8.1 so it's not a regression. Moving this to the backlog.

**Comment by philippfromme** [comment] 2021-07-09 07:28
This has been around for a long time. ⏳

**Comment by nikku** [comment] 2021-08-16 10:12
Closed via https://github.com/camunda/camunda-modeler/pull/2392.

**Closed** 2021-08-16 10:39 UTC
Labels: bug, in progress, ux, spring cleaning
