### ISSUE TITLE
Improve deploy / run tool completed notifications

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1827] opened 2020-06-08 14:17 UTC
__Is your feature request related to a problem? Please describe.__

Using both tools results in a white on white background, looking slightly out of place deployment notification. I'd expect a notification that is engaging to me as a user and, in all cases, encourages me to go on, after I've completed the step.

__Describe the solution you'd like__

* I'd improve the styling / positioning of the notification(s): They should stand out and, through color coding, it should be quickly clear if any of the tools executed successfully (i.e. indicated via a green checkmark) or failed (i.e. indicated by a pirate head).

* I'd improve the call to action that both dialogs provide in terms of styling: 
    * Deploy: Currently points to nothing, does not show the deployment ID. Proposal: Make it possible to expand the notification to show the deployment ID. Link to cockpit to the deployment section _or_ link to run :arrow_right: encourage running the instance as the next step.
    * Run: points to something but the overall styling could be improved. Again, making it more engaging can go a long way.

__Describe alternatives you've considered__

No real alternative.

**Comment by smbea** [comment] 2021-12-02 14:50
Duplicate of #2607

**Closed** 2021-12-02 14:51 UTC
Labels: duplicate
