### ISSUE TITLE
Properties panel in BPMN editor flickers once resized

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3597] opened 2023-05-08 12:21 UTC
### Describe the bug

https://user-images.githubusercontent.com/28307541/236822185-b6bb8935-3ede-425f-8efa-13671c27778e.mov

### Steps to reproduce

See the capture above

### Expected behavior

No flickering

### Environment

- OS: MacOS
- Camunda Modeler Version: 5.11.0
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by marstamm** [comment] 2023-05-09 14:34
**Root Cause**

We have an unnecessary dependency on `layoutConfig` in the Properties Panel `useCallback`:  

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/01ed48fd0e05de5cf2f2901fd695f94fd26345e1/src/render/BpmnPropertiesPanel.js#L194-L198

This causes the callback here https://github.com/bpmn-io/properties-panel/blob/e211995c77ef1452d518597dd41226334e64938b/src/PropertiesPanel.js#L132-L136 called twice: once for the "new" callback with the old size, and the second time with the actual updated layout

**Comment by marstamm** [comment] 2023-05-30 12:13
fixed via #3633

**Closed by marstamm** 2023-05-30 12:13 UTC
Labels: bug, in progress, properties panel
