### ISSUE TITLE
Camunda Modeler uses a lot of CPU power although not used

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3086] opened 2022-08-11 07:15 UTC
### Describe the bug

I waked up my computer in morning from hibernate and saw a Spike in CPU power.

Checking the processes Camunda Modeler was the top one. I haven't used it today.

![grafik](https://user-images.githubusercontent.com/7870843/184081738-c1ec1ae5-4de8-43a8-bebd-a9e326d02029.png)

Is there any loop that uses CPU power?

### Steps to reproduce

1. Open Camunda Modeler
2. Put the computer to hibernate
3. Start the computer from hibernate
4. Check the processes of the operating system

### Expected behavior

If I don't use the Camunda Modeler, it doesn't consume any CPU power

### Environment

Camunda Modeler system information
 * Version: 5.1.0
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, bpmn-js Token Simulation, Migration, BPMN Linter, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform 7

**Comment by ingorichtsmeier** [comment] 2022-08-15 07:55
Even worse, today it uses CPU power, although the Modeler was not started:

![grafik](https://user-images.githubusercontent.com/7870843/184597404-55ca212f-07d6-425e-ae20-f7131fe4f99f.png)


![grafik](https://user-images.githubusercontent.com/7870843/184597329-1da55077-4c5c-41fc-b2c3-99a24ed4ddcb.png)

**Comment by nikku** [comment] 2022-08-15 08:07
We don't offer an auto-safe / auto-open feature.

Because of that I assume that the old modeler is left in a bogus state where it cannot recover. Please kill it and see if you can reproduce it in the future.

**Comment by nikku** [comment] 2022-08-19 09:48
Closing this issue. Please comment if this happens again.

**Closed by nikku** 2022-08-19 09:48 UTC
Labels: bug
