### ISSUE TITLE
On trying to add additional files while deployment, the dialog expands from the end and cuts off the top fields from being displayed. 

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2364] opened 2021-07-09 11:59 UTC
__Describe the Bug__

On trying to add additional files while deployment, the dialog expands from the end and cuts off the top fields from being displayed. 

__Steps to Reproduce__

1. Create a diagram to deploy
2. Add authentication in the Endpoint configuration.
3. Try to add additional files by clicking on select files.
4. We could see that the bottom part of the dialog(where the deploy and cancel buttons is present) is expanded and we could not scroll up completely the dialog as the top part is cut from the dialog box.

__Expected Behavior__

The complete deploy diagram dialog should be visible.

__Environment__

- OS: Windows 10
- Camunda Modeler Version:4.9.0
- Execution Platform:Camunda Platform
- Installed plug-ins: [...]

https://user-images.githubusercontent.com/85225325/125074537-b41a5f00-e0bd-11eb-969f-9ead2e5eeae5.mp4

**Comment by MaxTru** [comment] 2021-07-09 12:47
Probably windows specific, I cannot reproduce this on Linux

**Comment by MaxTru** [comment] 2021-07-14 08:52
@philippfromme could you please try to reproduce on Windows before we move this to the backlog? Thanks

**Comment by philippfromme** [comment] 2021-07-20 07:59
Will look into it. 👀

**Comment by philippfromme** [comment] 2021-07-20 13:54
I can reproduce this on Windows ™️ 👍🏻

**Comment by pinussilvestrus** [comment] 2021-07-20 14:38
I'm not able to reproduce it on macOS. Maybe a glitch with the Windows file selection.

**Comment by MaxTru** [comment] 2021-07-22 12:17
This was re-procuded and scope is clear - marking it for spring cleaning

**Comment by philippfromme** [comment] 2022-02-25 09:10
Can we close this? The deployment form has moved from a modal to an overlay.

**Closed** 2022-02-25 09:20 UTC
Labels: bug, platform:Windows, ux, backlog, spring cleaning
