### ISSUE TITLE
Run instance plugin does not detect changes in Executable option

### ISSUE THREAD

**Issue by oguzeroglu** [camunda/camunda-modeler#1671] opened 2020-01-27 12:48 UTC
__Describe the Bug__

Run instance plugin does not detect changes made in Executable option. It allows deploying/running Non-Executable processes.

__Steps to Reproduce__

1. Try deploying/running a executable process
2. Change the process to non executable
3. Try to deploy/run again
4. It still works

__Expected Behavior__

It should throw an error

__Environment__

- Any

**Comment by pinussilvestrus** [comment] 2020-01-28 11:18
So this bug includes two basic scenarios?

 | Scenario        |  actual behavior           |  expected behavior  |
| ------------- |-------------| -----|
| Changing Non executable --> Executable  | throwing start instance error (no executable process) | no error |
| Changing Executable  --> Non executable   | no error  |   throwing start instance error (no executable process) |

@oguzeroglu can you verify that?

I was not able to verify the first one. For me, it deployed the newest version of the diagram and then tries to run it.

The second scenario is caused by the fact we use the saved `processDefinition` since the engine returns no process definition if the process is not executable.  That's the one from the _last successful deployment_. We have to do that because the engine also returns no process definition if the diagram has no changes, cf. https://docs.camunda.org/manual/7.8/reference/rest/deployment/post-deployment/#request-body (`deploy-changed-only` flag is set to `true`).

If we change the `deploy-changed-only` to true, it would work, since we would always use the newest process definition directly, and if there's no, if there's an error, it would not run at all. That would mean we would have a new process definition version for every deployment. Do we want that?

**Comment by pinussilvestrus** [comment] 2020-01-28 12:19
Updated the issue description since we were not able to reproduce the first scenario.

**Comment by pinussilvestrus** [comment] 2020-01-28 14:11
Closed via https://github.com/camunda/camunda-modeler/commit/d3500fed63617e2fc792124ac3a078520fda5e10

**Closed by pinussilvestrus** 2020-01-28 14:11 UTC
Labels: bug, needs review
