### ISSUE TITLE
display meta data test fail

### ISSUE THREAD

**Issue by marciotex** [camunda/camunda-modeler#1948] opened 2020-09-30 22:37 UTC
__Describe the Bug__

Display meta data test failed:

 `<ElementTemplatesView>                                                                          
    basics                                                                                        
      ✓ should render                                                                             
      ✓ should get element templates on mount                                                     
      ✓ should get element templates for selected element type                                                                                                                                      
      ✓ should get element templates sorted alphabetically                                                                                                                                          
      ✓ should list element templates                                                             
      ✗ should display meta data                                                                  
        AssertionError: expected 'Walt\'s Catalog | 2001-09-08' to equal 'Walt\'s Catalog | 2001-09-09'                                                                                             
            at Context.eval (webpack:///./src/plugins/element-templates-modal/components/__tests__/ElementTemplatesViewSpec.js?:91:30)`

Here full log:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/share/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'client:test'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.18.4
4 verbose run-script [ 'preclient:test', 'client:test', 'postclient:test' ]
5 info lifecycle camunda-modeler-builder@0.0.0~preclient:test: camunda-modeler-builder@0.0.0
6 info lifecycle camunda-modeler-builder@0.0.0~client:test: camunda-modeler-builder@0.0.0
7 verbose lifecycle camunda-modeler-builder@0.0.0~client:test: unsafe-perm in lifecycle true
8 verbose lifecycle camunda-modeler-builder@0.0.0~client:test: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/marciotex/devel/camunda-modeler/node_modules/.bin:/usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/marciotex/devel/camunda-modeler/node_modules/.bin:/home/marciotex/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle camunda-modeler-builder@0.0.0~client:test: CWD: /home/marciotex/devel/camunda-modeler
10 silly lifecycle camunda-modeler-builder@0.0.0~client:test: Args: [ '-c', '(cd client && npm run test)' ]
11 silly lifecycle camunda-modeler-builder@0.0.0~client:test: Returned: code: 1  signal: null
12 info lifecycle camunda-modeler-builder@0.0.0~client:test: Failed to exec client:test script
13 verbose stack Error: camunda-modeler-builder@0.0.0 client:test: `(cd client && npm run test)`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid camunda-modeler-builder@0.0.0
15 verbose cwd /home/marciotex/devel/camunda-modeler
16 verbose Linux 5.8.0-2-amd64
17 verbose argv "/usr/bin/node" "/usr/share/npm/bin/npm-cli.js" "run" "client:test"
18 verbose node v12.18.4
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error camunda-modeler-builder@0.0.0 client:test: `(cd client && npm run test)`
22 error Exit status 1
23 error Failed at the camunda-modeler-builder@0.0.0 client:test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Sorry, I dont know formatting better.

__Steps to Reproduce__

1. git pull
2. npm install
3. npm test

And then the error above.

__Expected Behavior__

should display meta data test run sucessfull

__Environment__

- OS: Debian GNU/Linux sid
- node --version: v12.18.4

Regards,

**Comment by pinussilvestrus** [comment] 2020-10-01 07:03
I can't reproduce this in the current `develop` branch, on macOS. On which branch did you try that out?

**Comment by philippfromme** [comment] 2020-10-01 07:59
Could this be related to timezones? `expected 'Walt\'s Catalog | 2001-09-08' to equal 'Walt\'s Catalog | 2001-09-09'` looks suspicious.

**Comment by marciotex** [comment] 2020-10-01 15:43
> I can't reproduce this in the current `develop` branch, on macOS. On which branch did you try that out?

On develop branch.

**Comment by marciotex** [comment] 2020-10-01 15:56
> Could this be related to timezones? `expected 'Walt\'s Catalog | 2001-09-08' to equal 'Walt\'s Catalog | 2001-09-09'` looks suspicious.

Hi.

Thank you for your interest. Now, I ran again, and same results.

$ date
qui 01 out 2020 12:48:44 -03

Is there something I can do for get more informations?

**Comment by nikku** [comment] 2020-10-11 20:39
My proposal would be to debug that case and figure out where the miss-match is coming from.

**Comment by MaxTru** [comment] 2020-10-14 09:58
The root of this issue IMO is here:
```
  const dateUpdated = new Date(metadata.updated);

  const year = dateUpdated.getFullYear();

  const month = leftPad(String(dateUpdated.getMonth() + 1), 2, '0');

  const date = leftPad(String(dateUpdated.getDate()), 2, '0');
```
See https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js#L424

We interpret the timestamp set in the element templates (e.g.,:
```
      "metadata": {
        "catalogOrganizationId": "b810760f-167f-4b54-bd30-37cafcfdd08e",
        "catalogTemplateId": "0002e7a7-1dfe-41da-a01d-4ad3efc66497",
        "created": 1600263200305,
        "tags": [
          "MyTestRPACatalog"
        ],
        "updated": 1602154329905
      },
```

using various methods on [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). This will return the values based on local timezone. [Read MDN: *Note: It's important to keep in mind that while the time value at the heart of a Date object is UTC, the basic methods to fetch the date and time or its components all work in the local (i.e. host system) time zone and offset.]* Depending on where you run the test (in particular with daylight saving time), the day will therefore differ +/- 1 and the test will fail.

I see two possible alternatives to resolve this
**A)** We can assume that we cannot know in advance based on which timezone the `created` and `updated` timestamp was set in the element template. Therefore the only chance we have to interpret it based on local timezone. Therefore we would not change the logic but the `spec` [here](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js#L424) and also create the comparison value based on local timezone (ie. use `new Date("1000000000000").getDate()` and so on).
**B)** The `created` and `updated` properties in the element template config `metadata` are not part of the public element template API (they are not documented [here](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates)). The only system setting these values is Cawemo. I aligned with Cawemo team and they confirmed that they set the timestamp based on UTC timezone. Therefore we should change the logic [here](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js#L430) and rather use the UTC methods like `Date.prototype.getUTCDate()`.

@philippfromme what do you think would be appropriate?

**Comment by philippfromme** [comment] 2020-10-15 11:45
> **A)** We can assume that we cannot know in advance based on which timezone the `created` and `updated` timestamp was set in the element template. Therefore the only chance we have to interpret it based on local timezone. Therefore we would not change the logic but the `spec` [here](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js#L424) and also create the comparison value based on local timezone (ie. use `new Date("1000000000000").getDate()` and so on).

Let's go for it. 👍

**Comment by pinussilvestrus** [comment] 2020-10-18 16:23
Closed via https://github.com/camunda/camunda-modeler/commit/b994463a0ab4b4f786f6e7418e7617ecd293f4f5

**Closed by pinussilvestrus** 2020-10-18 16:23 UTC
Labels: bug, needs review
