### ISSUE TITLE
Service Task with External Implementation wont copy

### ISSUE THREAD

**Issue by johannmentz** [camunda/camunda-modeler#721] opened 2018-01-24 12:19 UTC
I created a service task with an implemetation type of external, therafter I right clicked and selcted copy. After trying to paste it nothing happened and my existing workflow became uneditable. (Could not move elements around.)
[CamundaBug.zip](https://github.com/camunda/camunda-modeler/files/1659773/CamundaBug.zip)

**Comment by nikku** [comment] 2018-01-24 13:05
This is a duplicate of https://github.com/camunda/camunda-modeler/issues/716 and will be fixed with the next Camunda Modeler release.

**Closed** 2018-01-24 13:05 UTC
