### ISSUE TITLE
Unhandled error when selecting process in the error panel on a collaboration diagram

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3358] opened 2022-12-13 14:49 UTC
### Describe the bug

Given a collaboration diagram with an error related to the process, when I click the process in the error panel, Modeler reports unhandled error.

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

No error, participant gets selected.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.5.1, 5.6.0
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

### Additional context

Log:

```
Cannot read properties of undefined (reading 'x')
    at file:///Users/maciej/.asdf/installs/camunda-modeler/5.5.1/Contents/Resources/app.asar/public/453.js:1:446988
    at this (webpack://camundanode_modules/@camunda/linting/lib/modeler/Linting.js:27:74)
    at showError (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:674:39)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/MultiSheetTab.js:269:18)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack://camunda-modeler-client/src/app/App.js:1831:15)
    at file:///Users/maciej/.asdf/installs/camunda-modeler/5.5.1/Contents/Resources/app.asar/public/bundle.js:2:2883152
    at file:///Users/maciej/.asdf/installs/camunda-modeler/5.5.1/Contents/Resources/app.asar/public/72.js:1:3411
    at file:///Users/maciej/.asdf/installs/camunda-modeler/5.5.1/Contents/Resources/app.asar/public/490.js:1:8466
    at apply (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:14:427)
    at apply (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:15:117)
    at file:///Users/maciej/.asdf/installs/camunda-modeler/5.5.1/Contents/Resources/app.asar/public/bundle.js:2:1583067
    at d (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:17:212)
    at wa (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:18:247)
    at call (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:18:56)
    at ya (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:21:68)
    at Da (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:84:408)
    at a (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:396)
    at Gb (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:39:139)
    at Kb (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:86:248)
    at file:///Users/maciej/.asdf/installs/camunda-modeler/5.5.1/Contents/Resources/app.asar/public/bundle.js:2:1679863
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:251:153)
    at Hb (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:85:206) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler/issues/new?assignees=&labels=bug&template=BUG_REPORT.yml#) [ info ]
```

**Comment by nikku** [comment] 2024-06-17 08:55
Duplicate of https://github.com/camunda/camunda-modeler/issues/4158.

**Closed by nikku** 2024-06-17 08:55 UTC
Labels: bug, backlog, linting
