### ISSUE TITLE
First line of element name is not aligned with following lines

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1217] opened 2019-02-13 10:06 UTC
// given
I have added a multiline name to an element

// when 
I observe the name field in the properties panel

// then
I see that the first line is not aligned with the other lines (see attached screenshot)

![label_alignment](https://user-images.githubusercontent.com/2777965/52703779-67c7a500-2f7f-11e9-8ef2-4dea62c72912.png)

**Comment by nikku** [comment] 2019-02-13 10:08
This is a duplicate of https://github.com/camunda/camunda-modeler/issues/1151.

**Closed by nikku** 2019-02-13 10:08 UTC
Labels: duplicate
