### ISSUE TITLE
Implement new undo / redo menu

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2554] opened 2021-11-10 17:56 UTC
__What should we do?__

Implement the [newly designed undo/redo menu](https://github.com/camunda/camunda-modeler-design/issues/51) and remove the existing undo/redo entries in the toolbar:

![image](https://user-images.githubusercontent.com/58601/141167256-504baf71-928c-4dda-8375-5983b0a21c9d.png)

__Tasks__

* [ ] Undo/redo menu is enabled/disabled depending on whether the action is possible in the currently active editor
* [ ] Clicking menu opens the popup where undo/redo can be triggered
* [ ] Clicking either action triggers it and keeps the popup open
* [ ] In the case that undo _or_ redo is not available the menu still shows, however the popup menu entries are not available
* [ ] If both actions become unavailable the popup menu closes and the button to open it is disabled
* [ ] Architecture: [Reuse existing dropdown overlay component](https://github.com/camunda/camunda-modeler/issues/2554#issuecomment-966153467)

Out of scope: Show keyboard shortcuts #2555.

__Why should we do it?__

Contribute to the editor redesign.

---

Cf. [design issue](https://github.com/camunda/camunda-modeler-design/issues/51).

**Comment by nikku** [comment] 2021-11-11 09:07
@pinussilvestrus Can we re-use the existing popup menu infrastructure to implement the menus or do we have to build new infrastructure for that?

**Comment by pinussilvestrus** [comment] 2021-11-11 09:40
The [`DropdownOverlay`](https://github.com/camunda/camunda-modeler/blob/develop/client/src/shared/ui/overlay/OverlayDropdown.js) component is currently designed to be on top of its anchor (as far as I can see). It is part of the status bar overlays. But making it also displayable on the bottom should be doable [by making some changes](https://github.com/camunda/camunda-modeler/blob/develop/client/src/shared/ui/overlay/Overlay.js#L77). The overlay dropdown would also be extended to offer [more than just text](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js#L49) (e.g. keyboard shortcut labels).

![image](https://user-images.githubusercontent.com/9433996/141274588-03d9b733-a44b-4d35-953e-0afbe279acd6.png)

What I could also imagine is to update the existing [`DropdownButton`](https://github.com/camunda/camunda-modeler/blob/develop/client/src/shared/ui/DropdownButton.js) we use for the toolbar.

**Comment by nikku** [comment] 2021-11-11 12:21
Thanks for clarifying. 

I think that would be the way to go, rather than duplicating functionality.

**Comment by andreasgeier** [comment] 2021-11-11 15:11
Let me clarify the expected behavior:

- if both, undo and redo, are not possible, the icon button is disabled, the dropdown cannot be opened
- if one action is not available, it is removed from the dropdown

**Comment by nikku** [comment] 2021-11-11 15:17
Updated the issue accordingly. Thanks.

**Comment by pinussilvestrus** [comment] 2021-11-18 15:56
Moving this to backlog due to current priorities (add + menu first).

**Comment by nikku** [comment] 2021-11-18 15:59
Proposal: Let's close it as won't fix and re-open it as needed.

**Comment by andreasgeier** [comment] 2021-11-19 10:08
Okay for me

**Comment by pinussilvestrus** [comment] 2021-11-19 10:09
Alright, let's close it then and wait for feedback.

**Closed by pinussilvestrus** 2021-11-19 10:09 UTC
Labels: backlog, Unified Modeler
