### ISSUE TITLE
Error: EPIPE: broken pipe, write

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#2992] opened 2022-06-13 11:58 UTC
### Describe the bug

Multiple users are experiencing he Modeler crashing randomly during usage.

The events seem to originate only from the combination "Modeler 5.0.0" and windows. I suspect this is caused by the electron update.

While the Sentry issues mostly show win32, we have at least 1 support case wich uses the 64 bit version: https://jira.camunda.com/browse/SUPPORT-13882

### Steps to reproduce

Sentry Issue: [CAMUNDA-MODELER-8XS](https://sentry.io/organizations/camunda-modeling/issues/3340637404/?referrer=github_integration)

```
Error: EPIPE: broken pipe, write
  File "~/build/console.js", line 75, in console.info
    originalConsoleMethod.apply(this, arguments);
  File "~/build/console.js", line 14, in ConsoleTransport.log
    console[type](type.toUpperCase(), message);
  File "~/build/console.js", line 18, in ConsoleTransport.info
    this.log('info', message);
  File "~/build/log.js", line 33, in null.<anonymous>
    transport[type](`${this.namespace} ${message}`);
...
(5 additional frame(s) were not displayed)
```

### Expected behavior

The modeler can be used on Windows

### Environment

- OS: Windows 32bit
- Camunda Modeler Version: 5.0.0
- Execution Platform: backend error
- Installed plug-ins: none

----

Tracked in SUPPORT-13882

**Comment by nikku** [comment] 2022-06-20 14:27
We could attempt to upgrade to electron@latest and see if that fixes the issue.

**Comment by nikku** [comment] 2022-06-27 11:14
Issue [still reproducible](https://jira.camunda.com/browse/SUPPORT-13882?focusedCommentId=239063&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-239063) in nightly.

**Comment by philippfromme** [comment] 2022-06-30 14:01
The issue seems to be caused by this line: https://github.com/camunda/camunda-modeler/blob/v5.0.0/app/lib/log/transports/console.js#L18 (called by https://github.com/camunda/camunda-modeler/blob/v5.0.0/app/lib/log/log.js#L33). So, calling `console.info` on the main process sometimes crashes the app. Seems to be quite a low-level issue. This feature hasn't caused any issues for years so something else must have changed (probably Electron/Node) that now causes the app to crash.

**Comment by barmac** [comment] 2022-12-09 12:11
This should be fixed via https://github.com/camunda/camunda-modeler/pull/3314. We suppress EPIPE errors now.

**Closed by barmac** 2022-12-09 12:11 UTC
Labels: bug, channel:support, backlog
