### ISSUE TITLE
Textbox should be bigger by default when editing Task Name

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#205] opened 2016-03-11 19:43 UTC
Wen you edit the name of a Task the text box is tiny and you always have to make it bigger using the mouse first. This is a bit annoying: 

![2016-03-11_20-37-43](https://cloud.githubusercontent.com/assets/1217596/13713558/d97cc99c-e7c9-11e5-9122-2d1351532f6b.png)

**Comment by meyerdan** [comment] 2016-03-14 07:37
You can now use the "name" input in the properties panel :)

**Comment by nikku** [comment] 2016-03-14 07:53
Duplicate of #157? We did some work on this in bpmn-io/bpmn-js#477.

Problem is fixed in the [latest nightly](https://camunda.org/release/camunda-modeler/nightly/) already.

**Closed by nikku** 2016-03-14 07:53 UTC
