### ISSUE TITLE
When copy pasting a service task which has a camunda:errorEventDefinition the errorRef is lost after a copy paste

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2203] opened 2021-04-09 09:14 UTC
__Describe the Bug__

When copy pasting a service task which has a `camunda:errorEventDefinition` the `errorRef` is lost after a copy paste. Note this only seems to occur, when the task had an elementTemplate applied
![ErrorRefLost](https://user-images.githubusercontent.com/42800119/114157809-52aeec80-9924-11eb-888d-bfcc2b18c969.gif)

__Steps to Reproduce__

1. Setup this element template:
```json
[
        {
  "name": "My super awesome UI Path template",
  "description": "",
  "id": "7aedee1c-d22d-4e3b-b9b4-093fcd1cedad",
  "appliesTo": [
    "bpmn:ServiceTask"
  ],
  "properties": [
    {
      "type": "Hidden",
      "value": "This is so awesome",
      "binding": {
        "type": "property",
        "name": "name"
      }
    },
    {
      "label": "UiPath Package Name",
      "type": "String",
      "value": "",
      "editable": false,
      "binding": {
        "type": "camunda:property",
        "name": "bot"
      }
    },
    {
      "type": "Hidden",
      "value": "external",
      "binding": {
        "type": "property",
        "name": "camunda:type"
      }
    },
    {
      "type": "Hidden",
      "value": "uipath",
      "binding": {
        "type": "property",
        "name": "camunda:topic"
      }
    },
    {
      "type": "Hidden",
      "value": "true",
      "binding": {
        "type": "property",
        "name": "camunda:asyncAfter"
      }
    },
    {
      "label": "a",
      "value": "${a}",
      "description": "a",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "a"
      }
    },
    {
      "label": "c",
      "value": "${c}",
      "description": "casdf",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "c"
      }
    },
    {
      "label": "b",
      "value": "b",
      "description": "b",
      "binding": {
        "type": "camunda:outputParameter",
        "source": "${b}"
      }
    },
    {
      "label": "new",
      "value": "blub",
      "binding": {
        "type": "camunda:errorEventDefinition",
        "errorRef": "81671d66-31a9-4f9f-b2dc-dc42baf0f708"
      }
    }
  ],
  "scopes": [
    {
      "type": "bpmn:Error",
      "id": "81671d66-31a9-4f9f-b2dc-dc42baf0f708",
      "properties": [
        {
          "label": "Error Code",
          "type": "Hidden",
          "value": "error",
          "binding": {
            "type": "property",
            "name": "errorCode"
          }
        },
        {
          "label": "Error Message",
          "type": "Hidden",
          "value": "",
          "binding": {
            "type": "property",
            "name": "camunda:errorMessage"
          }
        },
        {
          "label": "Error Name",
          "type": "Hidden",
          "value": "new",
          "binding": {
            "type": "property",
            "name": "name"
          }
        }
      ]
    }
  ]
}
]

```
2. Apply to service task
3. copy paste the task
4. `errorRef` is lost
  * In `xml`
  * As well as in the properties panel
![Screenshot_20210409_111349](https://user-images.githubusercontent.com/42800119/114158150-aae5ee80-9924-11eb-80a8-35c1353e7175.png)

__Expected Behavior__

`errorRef` is kept after copyPaste

__Environment__

Camunda Modeler 4.7-rc0

**Comment by pinussilvestrus** [comment] 2021-04-09 09:24
**root cause**

We have [behavior in place](https://github.com/camunda/camunda-bpmn-moddle/blob/master/lib/CopyPasteRootElementBehavior.js) that makes sure we copy references to root elements, e.g. for external service tasks. Given the following element

```xml
<bpmn:serviceTask id="Activity_0y46j68" camunda:asyncAfter="true" camunda:type="external" camunda:topic="uipath">
  <bpmn:extensionElements>
    <camunda:inputOutput>
      <camunda:inputParameter name="a">${a}</camunda:inputParameter>
      <camunda:inputParameter name="c">${c}</camunda:inputParameter>
      <camunda:outputParameter name="b">${b}</camunda:outputParameter>
    </camunda:inputOutput>
    <camunda:properties>
      <camunda:property name="bot" value="" />
    </camunda:properties>
    <camunda:errorEventDefinition id="ErrorEventDefinition_1 errorRef="Error_1" expression="blub" />
  </bpmn:extensionElements>
</bpmn:serviceTask>
```

it works as follows
* on copy, [it saves all to be-copied references](https://github.com/camunda/camunda-bpmn-moddle/blob/master/lib/CopyPasteRootElementBehavior.js#L112) => one reference saved
* on paste, it sets these references to the extension elements, **but** not to the original one, but by index
* the saved reference to the Error will be set to the **first** extension element, namely the `camunda:InputOutput`

```xml
<bpmn:serviceTask id="Activity_0y46j68" camunda:asyncAfter="true" camunda:type="external" camunda:topic="uipath">
  <bpmn:extensionElements>
    <camunda:inputOutput undefined="[object Object]">
      <camunda:inputParameter name="a">${a}</camunda:inputParameter>
      <camunda:inputParameter name="c">${c}</camunda:inputParameter>
      <camunda:outputParameter name="b">${b}</camunda:outputParameter>
    </camunda:inputOutput>
    ...
</bpmn:serviceTask>
```

:boom:

--> Suggestion(s): 
* in the saved referenced root element, save the correct element / idx per reference (short-term)
* refactor the whole behavior + tests (Spring cleaning)

**Comment by pinussilvestrus** [comment] 2021-04-09 13:22
Closed via https://github.com/camunda/camunda-modeler/pull/2204

**Closed by pinussilvestrus** 2021-04-09 13:22 UTC
Labels: bug, needs review

**Comment by nikku** [comment] 2021-04-12 09:46
Took me a while to dive into this one. 

As I understand now (and as you described) we did not account for scenarios yet where more extension elements than the `camunda:ErrorEventDefinition`s are being present, thus applying the references to other untracked references.

Thanks for diving into this and providing a quick fix.
