### ISSUE TITLE
Cannot access buttons in deploy modal when it exceeds the screen size

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-modeler#1706] opened 2020-02-26 13:44 UTC
__Describe the Bug__

* I cannot see the remainder of the deploy dialogue, most importantly I cannot access the deploy button
<img width="798" alt="screenshot" src="https://user-images.githubusercontent.com/586648/75350174-56a9b780-58a6-11ea-8e74-f4ba8340f0d4.png">

__Steps to Reproduce__

1. Windows 10
2. Screen resolution 1920x1080
3. Open deploy diagram dialogue

__Expected Behavior__

* I can access the entire dialogue, e.g. by scrolling

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 3.6.0

**Comment by barmac** [comment] 2020-02-26 13:50
Fixed in 3.7 & a duplicate of https://github.com/camunda/camunda-modeler/issues/1575

Anyway, thanks for reporting!

**Closed by barmac** 2020-02-26 13:50 UTC
Labels: bug
