### ISSUE TITLE
I as a user should be able to deploy Camunda Platform 8 diagrams if the Zeebe Gateway accepts only TLS connection

### ISSUE THREAD

**Issue by aivinog1** [camunda/camunda-modeler#2995] opened 2022-06-21 13:22 UTC
### Problem you would like to solve

I want to be able to deploy diagrams and start new process instances to Zeebe Gateway with TLS. The TLS setting for Zeebe is described [here](https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/secure-client-communication/).

### Proposed solution

I think that there should be a switch that enables TLS communication. For now, it is okay to use only the system's certificates.

### Alternatives considered

In addition to the switch, we can add a couple of fields that are describing the certificate's location, etc.
I can't see any alternatives though.

### Additional context

Camunda Platform 8. Mac OS. Also, it would be nice to print out a more concrete message about TLS.

**Comment by barmac** [comment] 2022-07-06 16:26
Thanks for opening the issue. However, it seems to be a duplicate of https://github.com/camunda/camunda-modeler/issues/2404. If you have anything to add, please leave a comment in the linked issue.

**Closed by barmac** 2022-07-06 16:26 UTC
Labels: enhancement
