### ISSUE TITLE
Add project/collection feature

### ISSUE THREAD

**Issue by Camunda-ChrisAllen** [camunda/camunda-modeler#1351] opened 2019-04-19 14:29 UTC
__Is your feature request related to a problem? Please describe.__

No

__Describe the solution you'd like__

I would like modeler to have the concept of grouping many project files into a "project" or "collection".  This could just be an ascii text file in the home directory that has the absolute paths to the files in the collection.  Open the project, and all files within the collection auto-load into Modeler.

__Describe alternatives you've considered__

None.

__Additional context__

This concept is common in many advanced text editors.  I would like to be able to quickly switch from project to project by referencing a collection by name.  This would be extremely handy.

**Comment by barmac** [comment] 2019-04-24 10:53
Thank you for your feature request. Can you please name any editors which implement your idea so that we could see what kind of solutions already exist?

**Comment by nikku** [comment] 2019-04-24 11:43
As mentioned by @Camunda-ChrisAllen many sophisticated text editors (i.e. Sublime Text / VSCode) implement such a feature.

**Comment by nikku** [comment] 2019-04-24 11:44
We do want something like this, however there exists no fixed time frame for when such feature is going to be implemented.

**Comment by philippfromme** [comment] 2023-03-01 21:55
Duplicate of https://github.com/camunda/camunda-modeler/issues/2508.

**Closed by philippfromme** 2023-03-01 21:55 UTC
Labels: enhancement, backlog
