### ISSUE TITLE
Text annotation doesn't move with its parent

### ISSUE THREAD

**Issue by Rafox97** [camunda/camunda-modeler#4492] opened 2024-09-02 15:00 UTC
### Describe the bug

When there is a text anywhere inside the pool, and I want to move the pool, the text box does not move along with the pool like activities or gateway do.

### Steps to reproduce

1. create a pool
2. create an activity
3. add a text box to the activity
4. move the pool

### Expected behavior

I would like that when moving the pool, the text box moves like the rest of the icons do.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

**Comment by philippfromme** [comment] 2024-09-10 10:22
I can reproduce the issue. It's not really a bug but the expected behavior. When moving an element we move all its children. The parent of artifacts like text annotations, data store references etc. depends on where they are on the canvas. Compare the behavior of data store references:

![brave_OF89L4F4df](https://github.com/user-attachments/assets/d7595759-761f-48fe-86ef-4cd02e3c9a5b)

I guess text annotations should behave the same.

**Comment by nikku** [comment] 2024-09-10 11:48
Should be a duplicate of https://github.com/camunda/camunda-modeler/issues/4172?

**Comment by nikku** [comment] 2024-09-10 11:49
Ok, not exactly a duplicate, but related.

**Closed** 2024-09-10 13:53 UTC
Labels: bug, good first issue, spring cleaning
