### ISSUE TITLE
Loading indicator's position is affected by log panel

### ISSUE THREAD

**Issue by oguzeroglu** [camunda/camunda-modeler#1736] opened 2020-03-20 08:26 UTC
__Describe the Bug__

The position of the loading indicator is affected by the log panel. When the Log panel is added to the DOM, loading indicator is pushed on top. See the GIF:

![](https://user-images.githubusercontent.com/15003836/77028452-14e9c980-6999-11ea-872e-93520f456d34.gif)

__Steps to Reproduce__

1. Open Camunda Modeler
2. Look to the screen 👀 

__Expected Behavior__

We should decide **if this is not the expected behavior.** Another approach would be that:

1) Render the loading indicator always right in the center.
2) Nothing else is visible as long as the loading indicator is visible, so that it still looks visually centered even if we add the log panel.

__Environment__

- OS: NA
- Camunda Modeler Version: NA

**Comment by nikku** [comment] 2020-03-22 19:22
Do you have any idea how to improve the behavior? I personally do not see the current is-state as a bug. Let me elaborate.

We have two loading indicators that are shown after one another

* the app-is-loading indicator
* the diagram-is-opening indicator

The one you see jumping is the diagram-is-opening indicator which is obviously affected by the log panel open status.

**Comment by oguzeroglu** [comment] 2020-03-23 08:27
I created this ticket as a request from @nazlikaya, so maybe she has an idea too.

An approach to prevent the flickering would be:
1) Always place the indicator right in the center of the screen
2) Whenever the indicator is being rendered, the rest of the elements should be hidden. The indicator should never be visible with the other elements.

Or we can simply close this ticket : ) Let's wait for @nazlikaya

**Comment by nikku** [comment] 2020-03-23 08:36
> 2. Whenever the indicator is being rendered, the rest of the elements should be hidden. The indicator should never be visible with the other elements.

This means that there will be a substantial flicker when opening new tabs. Likely we will only get rid of the flicker if we drop one of the loading indicators.

**Comment by nazlikaya** [comment] 2020-03-23 12:42
Can we postpone to show the second spinner until the elements are shown (toolbar, panel etc.)? Because the second spinner refers to diagram.

**Comment by nikku** [comment] 2020-03-23 14:23
Looking at a Camunda Modeler 3.6 screen capture here I indeed see a different behavior (still a lot of flicker), though.

![capture 8iY8PO_optimized](https://user-images.githubusercontent.com/58601/77325795-2aece680-6d19-11ea-8779-f08ed424f1ca.gif)

At least the editor controls should not be shown in 3.6 until all tab contents (diagram editor, diagram) are fully loaded and rendered.

Could you @nazlikaya share a screenshot that marks which controls you think should be shown before the "diagram importing indicator" is shown? We can then discuss this and see if it is feasible to implement it.

**Comment by nikku** [comment] 2020-03-23 14:24
I'll also double check our current loader code and see if we can apply a quick fix.

**Comment by nikku** [comment] 2020-03-25 09:50
After double checking the issue (up to date screen capture attached) I can confirm that both modelers behave exactly the same:

* Both show two different loading indicators, the second one being local to the diagram
* The tab loader causes a quick flicker before it spawns

---

![capture yS8AnZ_optimized](https://user-images.githubusercontent.com/58601/77523005-64426500-6e85-11ea-83db-79f8db0a7bf1.gif)

**Comment by nikku** [comment] 2020-03-25 21:04
The situation will be improved substantially via https://github.com/camunda/camunda-modeler/pull/1743.

**Comment by nikku** [comment] 2020-03-27 07:16
Closed via https://github.com/camunda/camunda-modeler/pull/1743.

**Closed by nikku** 2020-03-27 07:16 UTC
Labels: bug, needs review
