### ISSUE TITLE
When _Save as_ dialog is open, arrow keys don't move the cursor but the selection instead

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1315] opened 2019-03-19 11:10 UTC
__Describe the Bug__

When _Save as_ dialog is open, arrow keys don't move the cursor but the selection instead.

__Steps to Reproduce__

![bug](https://user-images.githubusercontent.com/28307541/54601704-fd06ff00-4a3f-11e9-8c1d-a8c7648d030b.gif)

1. Select an element on diagram
2. Open _Save as_ dialog
3. Try to move the cursor with arrow keys

__Expected Behavior__

Cursor is moved whereas diagram elements are not.

__Environment__

 - OS: MacOS 10.14.3
 - Camunda Modeler Version: 2.2.4, 3.0.0-beta.3

**Comment by nikku** [comment] 2019-03-19 16:36
Duplicate of https://github.com/camunda/camunda-modeler/issues/813.

**Comment by pinussilvestrus** [comment] 2019-03-20 08:30
Since it is a duplicate, this issue can be closed.

**Closed by pinussilvestrus** 2019-03-20 08:30 UTC
Labels: bug, platform:Darwin, ready
