### ISSUE TITLE
JavaScript Error when going back to Application

### ISSUE THREAD

**Issue by TilmanK** [camunda/camunda-modeler#798] opened 2018-04-30 12:55 UTC
Hi,

I just had Camunda Modeler running for some time (hours) in the background when I came back to the app and received a TypeError in an Error window (just opened the window, don't know if I clicked on anything specific). I couldn't find anything in the dev logs, nevertheless I attached the log and a screenshot. 

I could proceed with normal operation after closing the error popup.

Maybe you can find out what causes this. Just saw this once.

Best Regards
Tilman
[-1525092849969.log](https://github.com/camunda/camunda-modeler/files/1960590/-1525092849969.log)
![crash](https://user-images.githubusercontent.com/8856390/39428102-7cf62ffa-4c86-11e8-91fd-2f8cd00b195d.png)

**Comment by nikku** [comment] 2018-05-14 09:42
If this issue re-appears, maybe you're able to deduce certain usage patterns that cause it?

It looks like it is caused by the application menu not properly updating. Unfortunately I cannot reproduce it myself given the existing information.

Closing this issue for now. We may re-open it if we stumble upon this again in a reproducible manner.

**Closed by nikku** 2018-05-14 09:42 UTC
Labels: cannot reproduce
