### ISSUE TITLE
Externaly changed file is not reimported

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1318] opened 2019-03-19 14:53 UTC
__Describe the Bug__

missing reimport of extrernal changes 

__Steps to Reproduce__

// given
I've opened a bpmn file in the modeler

// when
I change the xml in an external editor

// then
the changes will not be reimported, although the modeler detects the change and displays a notification

__Expected Behavior__

external changes will be reimported

__Environment__
- Linux
- Camunda Modeler Version: 3.0.0-beta3

**Comment by pinussilvestrus** [comment] 2019-03-19 15:27
Was not able to reproduce it on macOS.

**Comment by barmac** [comment] 2019-03-19 15:50
Same (MacOS 10.14.3).

**Comment by philippfromme** [comment] 2019-03-19 15:57
It works for existing diagrams that I opened, doesn't work for newly created diagrams.

**Comment by pinussilvestrus** [comment] 2019-03-20 08:50
After debugging it reveals that the cached [`lastXML` inside the Tab's rerendering](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/MultiSheetTab.js#L370) followed by `App.js#updateTab` is the old one. Therefore it re-renders the Editor with old content.

**Comment by philippfromme** [comment] 2019-03-20 08:52
Good catch!


Kind Regards
Philipp Fromme
Software Developer
---------------------------------------------

Camunda Services GmbH

Zossener Str. 55 – 58

10961 Berlin

Telefon +49 30 664 04 09 - 00

---------------------------------------------
Amtsgericht Charlottenburg: HRB 113230 B
Geschäftsführer: Jakob Freund, Bernd Rücker

________________________________
Von: Niklas Kiefer <notifications@github.com>
Gesendet: Mittwoch, 20. März 2019 09:50
An: camunda/camunda-modeler
Cc: Philipp Fromme; Comment
Betreff: Re: [camunda/camunda-modeler] Externaly changed file is not reimported (#1318)


After debugging it reveals that the cached lastXML inside the Tab's rerendering<https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/MultiSheetTab.js#L370> followed by App.js#updateTab is the old one. Therefore it re-renders the Editor with old content.

**Comment by philippfromme** [comment] 2019-03-22 15:41
Closed via https://github.com/camunda/camunda-modeler/pull/1323.

**Closed by philippfromme** 2019-03-22 15:41 UTC
Labels: bug, needs review
