### ISSUE TITLE
DMN Property Panel cannot be opened again

### ISSUE THREAD

**Issue by volkergersabeck** [camunda/camunda-modeler#1248] opened 2019-02-18 10:58 UTC
When the user hides the property panel of a DMN table
Then the user cannot open the property panel again from within the DMN table.
Only opening a BPMN diagram and opening the property panel from there brings it back.

Additional question: should the expand status of the property panel be global or per open file?

![1248 dmn property panel cannot be reopened](https://user-images.githubusercontent.com/232571/52946495-70035400-3374-11e9-93e6-a35a789d5747.gif)

**Comment by pinussilvestrus** [comment] 2019-02-20 08:46
This is intended behavior: https://github.com/camunda/camunda-modeler/issues/1114. 

I'll close this issue since this is the decided-upon state. @volkergersabeck Feel free to re-open it if you have additional thoughts about it 👍

**Closed by pinussilvestrus** 2019-02-20 08:46 UTC
