### ISSUE TITLE
Enable connection tool for selected text annotations

### ISSUE THREAD

**Issue by volkergersabeck** [camunda/camunda-modeler#2042] opened 2020-12-18 14:25 UTC
__Description of the Issue__

Currently, text annotations cannot be connected to other elements starting with the text annotation itself. It can be achieved by first selection the target element and creating a new connection from there.

We should offer the connection tool (keyboard shortcut `c`) also when a text annotation (in BPMN and DMN) is selected.

![capture RHuZbw_optimized](https://user-images.githubusercontent.com/58601/112833753-74dc7b00-9097-11eb-9fb6-9fc7a491d700.gif)

_As seen in the screencapture, the global connect tool allows to connect gateway :arrow_right: text annotation but not text annotation :arrow_right: gateway._

__Expected Behavior__

The global connect tool allows starting a connection from a text annotation.

**Comment by tkhadir** [comment] 2021-03-27 17:20
hello @volkergersabeck, @MaxTru  this issue is tagged `good first issue` i will be honored to contribute if it's possible 😄

**Comment by MaxTru** [comment] 2021-03-29 06:55
Dear @tkhadir ,

Sure - we would be happy to retrieve [contributions](https://github.com/camunda/camunda-modeler/blob/develop/.github/CONTRIBUTING.md) for this :-) 

Regards

**Comment by tkhadir** [comment] 2021-03-29 11:57
thank you very much @MaxTru can i have more explanations for this issue with and example please ? to be sure that i have understood the goal of it 😄

**Comment by nikku** [comment] 2021-03-29 12:05
@tkhadir I've noticed the issue is rather hard to understand without further context.

I've added some more details and a screencast. Please get back to us, if you feel there is still things missing. Please also approach us if you need guidance how to approach this issue.

**Comment by tkhadir** [comment] 2021-03-29 12:44
hello @nikku thank you very much for these informations it is more clear with 😄

**Comment by tkhadir** [comment] 2021-03-30 21:21
hello @nikku i'm back after analyzing how to enable the connection tool for text annotations, and then i found that in bpmn-js library we need to add 'bpmn:TextAnnotation' to the canStartConnection method to enable it.

thanks in advance for your remarks 😄

**Comment by tkhadir** [comment] 2021-03-31 08:11
related MR to enable the connection tool  on text annotation ⬆️ 
[https://github.com/bpmn-io/bpmn-js/pull/1428](url)

**Comment by MaxTru** [comment] 2021-04-07 09:50
Closed by https://github.com/bpmn-io/bpmn-js/pull/1428

**Comment by pinussilvestrus** [comment] 2021-04-08 07:59
Closed via https://github.com/camunda/camunda-modeler/issues/2194

**Comment by MaxTru** [comment] 2021-04-09 08:27
Follow-up: we should implement the same ux in dmn-js too. Will create a respective issue

**Comment by MaxTru** [comment] 2021-04-09 08:29
This is not yet closed, since we only implemented the experience for BPMN but not for DMN

**Comment by tkhadir** [comment] 2021-04-10 21:35
hello @MaxTru here is my modification related to enabling connect tool for dmn : 

https://github.com/bpmn-io/dmn-js/pull/628

("la boucle est bouclée" like we say in french 😄 )

cheers,
Tayeb

**Comment by MaxTru** [comment] 2021-04-12 07:44
Fixed upstream by https://github.com/bpmn-io/dmn-js/pull/628

**Comment by MaxTru** [comment] 2021-04-12 19:09
Closed via https://github.com/camunda/camunda-modeler/pull/2209

**Closed by MaxTru** 2021-04-12 19:09 UTC
Labels: DMN, enhancement, good first issue, needs review
