### ISSUE TITLE
Connection Not Snapping to Shape Center

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1436] opened 2019-07-24 08:37 UTC
![bug](https://user-images.githubusercontent.com/7633572/61778216-a00cc280-adfe-11e9-83e4-0b6a4d546412.gif)

__Steps to Reproduce__

1. Create connection between shapes.

__Expected Behavior__

* [x] We adopt the same behavior we got for tasks (connection snaps to shape center, unless on the border)

__Context__

This is the existing task behavior, see the following screenshot:

![capture 92znj3_optimized](https://user-images.githubusercontent.com/58601/64096049-df64f200-cd60-11e9-904a-51990663f1e2.gif)

Snapping is implemented in bpmn-js (via [`BpmnConnectSnapping`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/snapping/BpmnConnectSnapping.js)).

__Environment__

 - OS: Windows 10
 - Camunda Modeler Version: 3.2.1

**Comment by oguzeroglu** [comment] 2019-09-10 09:51
I believe the problem is the usage of every function in [this line](https://github.com/bpmn-io/bpmn-js/blob/aea527775e06818efa34725728565c9e2c1a3f5f/lib/features/snapping/BpmnConnectSnapping.js#L140).

What happens in this line is that for **all** axes (both x and y) we expect the mouse coordinate for given axis to be in this interval:

**]shapeStartOnAxis + PADDING, shapeEndOnAxis + PADDING[**

This area can be represented by the yellow area in following images.
**For axis X:**
<img width="396" alt="x_axis" src="https://user-images.githubusercontent.com/15003836/64603070-1ae66880-d3c0-11e9-9359-771ca19d891b.png">

**For axis Y:**
<img width="374" alt="y_axis" src="https://user-images.githubusercontent.com/15003836/64603084-1fab1c80-d3c0-11e9-8c44-9c4b910bd64d.png">

The comparison makes sense, however what causes the bug is the usage of **every** function instead of **some** function. That's why if a comparison fails for an axis, isCenter variable is false. Which explains this behaviour in the following gif (pay attention to how isCenter is true only when the mouse is in the yellow-represented areas):

![behaviour](https://user-images.githubusercontent.com/15003836/64603699-140c2580-d3c1-11e9-8c19-3f2c21953fed.gif)

Using **some** function instead of **every** function fixes the problem (return true if **any** of the tests succeeds).

**Comment by philippfromme** [comment] 2019-09-10 10:11
Good find. Shouldn't we snap `x` and `y` independently in the first place?

**Comment by oguzeroglu** [comment] 2019-09-11 14:57
Closed via https://github.com/bpmn-io/bpmn-js/pull/1188

**Comment by barmac** [comment] 2019-09-25 12:37
Closed via https://github.com/camunda/camunda-modeler/pull/1513#pullrequestreview-293041737

**Closed by barmac** 2019-09-25 12:37 UTC
Labels: bug, fixed upstream, good first issue, modeling, needs review, ux
