### ISSUE TITLE
Exception when clicking blue BPMN Diagram button (for 7 or 8)

### ISSUE THREAD

**Issue by ddrouin** [camunda/camunda-modeler#3290] opened 2022-11-09 15:38 UTC
### Describe the bug

Open up Camunda modeler 5.5.0.
Click either BPMN Diagram button.
Fail.

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

The BPMN editor should open.

### Environment

- OS: macOS 12.6.1 Monterey
- Camunda Modeler Version: 5.5.0
- Execution Platform: Camunda BPMN
- Installed plug-ins: BPMN Linter, Tooltip Plugin, dmn-testing-plugin, migration.

**Comment by nikku** [comment] 2022-11-09 16:02
Duplicate of https://github.com/camunda/camunda-modeler/issues/3253. Please disable the linter plug-in as it is incompatible with v5.3+.

**Closed by nikku** 2022-11-09 16:02 UTC
Labels: bug
