### ISSUE TITLE
Doesn't work FEEL expression

### ISSUE THREAD

**Issue by Oleksiivanov** [camunda/camunda-modeler#3470] opened 2023-02-16 08:59 UTC
### Describe the bug

FEEL expression doesn't work for the inner class.
In [REST](https://github.com/camunda/connectors-bundle/tree/main/connectors) connector we have next structure for `credentialsInBody` authentication type : 
```json
"request" : { //main request
"url": "main url"
 "authentication":{
"type":"credentialsInBody",
"request":{ //authentication request , we take token from this response
"url": "url for authentication"
}
}
}
```
in template, we put one main URL for auth request and main request, and after that, we use FEEL expression, for changing url : 
<img width="367" alt="Screenshot 2023-02-16 at 10 43 54" src="https://user-images.githubusercontent.com/108869886/219313361-faefb20f-adfd-4625-a6e6-8be8925e6993.png">

A template with test data is attached at the bottom of this bug report.

If we don't use FEEL expression for auth URL - everything works OK, but when we use FEEL expression, in Authentication.URL we have `null`.
```
ValidationException: Found constraints violated while validating input: 
 - authentication.request.url: must not be blank

```

For main request URL everything is work with FEEL expression.

### Steps to reproduce

1. put the attached template.json to the desktop modeler
2. create new BPMN diagram
3. choose needed template : "test FEEL"
4. all required fields for test already filled.
5. deploy diagram
6. run the process

### Expected behavior

Expected result : connector give response with status 200 (OK)

### Environment

- Camunda Modeler Version: 5.8.0 nightly
- bundle version :  0.16.0

### Additional context

Template : 
```json
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "test FEEL",
  "id": "465623b7-f64c-40de-8c2a-e2bf4c46bbc7",
  "version": 1,
  "documentationRef": "https://docs",
  "category": {
    "id": "connectors",
    "name": "Connectors"
  },
  "appliesTo": [
    "bpmn:Task"
  ],
  "elementType": {
    "value": "bpmn:ServiceTask"
  },
  "groups": [
    {
      "id": "operation",
      "label": "Operation"
    },
    {
      "id": "authentication",
      "label": "Authentication"
    },
    {
      "id": "configuration",
      "label": "Configuration"
    },
    {
      "id": "input",
      "label": "Input"
    },
    {
      "id": "output",
      "label": "Output"
    },
    {
      "id": "errors",
      "label": "Error Handling"
    }
  ],
  "properties": [
    {
      "type": "Hidden",
      "value": "io.camunda:http-json:1",
      "binding": {
        "type": "zeebe:taskDefinition:type"
      }
    },
    {
      "label": "Operation type",
      "id": "operationType",
      "group": "operation",
      "value": "listAvBotRuns",
      "type": "Dropdown",
      "choices": [
        {
          "name": "List available unattended Bot Runners",
          "value": "listAvBotRuns"
        }
      ],
      "binding": {
        "type": "zeebe:input",
        "name": "operationType"
      }
    },
    {
      "label": "Type",
      "id": "authenticationType",
      "group": "authentication",
      "description": "this auth for example",
      "value": "userNamePasswordAuth",
      "type": "Dropdown",
      "choices": [
        {
          "name": "Authenticate (username and password)",
          "value": "userNamePasswordAuth"
        }
      ],
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.withoutBindingType"
      }
    },
    {
      "id": "credentialsInBodyAuthType",
      "description": "with this auth we do 2 request. first - for authenticate, second - request for action with token",
      "group": "authentication",
      "type": "Hidden",
      "value": "credentialsInBody",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.type"
      },
      "constraints": {
        "notEmpty": true
      },
      "condition": {
        "property": "authenticationType",
        "oneOf": [
          "userNamePasswordAuth",
          "userNameApiKeyAuth"
        ]
      }
    },
    {
      "group": "authentication",
      "description": "this auth type needed for first request in connector (authenticate and get token)",
      "type": "Hidden",
      "value": "noAuth",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.authentication.type"
      },
      "constraints": {
        "notEmpty": true
      },
      "condition": {
        "property": "authenticationType",
        "oneOf": [
          "userNamePasswordAuth"
        ]
      }
    },
    {
      "id": "tokenAuthType",
      "description": "this auth type needed for second request in connector",
      "group": "authentication",
      "type": "Hidden",
      "value": "noAuth",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.type"
      },
      "constraints": {
        "notEmpty": true
      },
      "condition": {
        "property": "authenticationType",
        "oneOf": [
          "tokenAuth"
        ]
      }
    },
    {
      "id": "authenticationMethod",
      "type": "Hidden",
      "value": "post",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.method"
      }
    },
    {
      "label": "Username",
      "group": "authentication",
      "type": "String",
      "feel": "optional",
      "value": "testcamunda0001@gmail.com",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.body.username"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Password",
      "group": "authentication",
      "type": "String",
      "feel": "optional",
      "value": " VKFycP7AVVr8-",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.body.password"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "multipleLogin",
      "group": "authentication",
      "type": "Dropdown",
      "value": "false",
      "choices": [
        {
          "name": "TRUE",
          "value": "true"
        },
        {
          "name": "FALSE",
          "value": "false"
        }
      ],
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.body.multipleLogin"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "OutputHeaders",
      "description": "this expression will get token from authenticate resopponse and put it to next request",
      "group": "input",
      "type": "Hidden",
      "value": "={\"X-Authorization\":\"asObject:token.asString\"}",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.outputHeaders"
      },
      "constraints": {
        "notEmpty": true
      },
      "condition": {
        "property": "authenticationType",
        "oneOf": [
          "userNamePasswordAuth",
          "userNameApiKeyAuth"
        ]
      }
    },
    {
      "label": "Room URL",
      "description": "this room url will use for all requests",
      "group": "configuration",
      "type": "String",
      "value": "community.cloud.automationanywhere.digital",
      "binding": {
        "type": "zeebe:input",
        "name": "controlRoomUrl"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "id": "authenticationMethod",
      "type": "Hidden",
      "value": "post",
      "binding": {
        "type": "zeebe:input",
        "name": "method"
      }
    },
    {
      "label": "first url, for auth.",
      "description": " in real template it will be hidden property",
      "type": "String",
      "group": "configuration",
      "feel": "optional",
      "value": "=\"https://\"+controlRoomUrl+\"/v1/authentication\"",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.url"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "second url, for next request with token",
      "description": " in real template it will be hidden property",
      "type": "String",
      "group": "configuration",
      "feel": "optional",
      "value": "=\"https://\"+controlRoomUrl+\"/v1/devices/runasusers/list\"",
      "binding": {
        "type": "zeebe:input",
        "name": "url"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "body to second url",
      "description": "",
      "type": "String",
      "group": "configuration",
      "feel": "required",
      "value": "={\"sort\":[],\"filter\":{},\"page\":{}}",
      "binding": {
        "type": "zeebe:input",
        "name": "body"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Result variable",
      "description": "Name of variable to store the response in. Details in the <a href=\"https://docs.camunda.io/docs/components/connectors/use-connectors/#result-variable\" target=\"_blank\">documentation</a>",
      "group": "output",
      "type": "String",
      "binding": {
        "type": "zeebe:taskHeader",
        "key": "resultVariable"
      }
    },
    {
      "label": "Error expression",
      "description": "Expression to handle errors. Details in the <a href=\"https://docs.camunda.io/docs/components/connectors/use-connectors/#bpmn-errors\" target=\"_blank\">documentation</a>",
      "group": "errors",
      "type": "Text",
      "feel": "required",
      "binding": {
        "type": "zeebe:taskHeader",
        "key": "errorExpression"
      }
    }
  ]
}
```

**Comment by barmac** [comment] 2023-02-17 09:56
I can reproduce this issue. Usually, string concatenation evaluates to `null` when one of the variables is `null`. However, in this case the variable is substituted correctly for one URL but not for the other. We need more investigation into this.

**Comment by barmac** [comment] 2023-02-17 10:46
OK so I know how to fix this, but don't know the reason. It's for sure not a problem with Camunda Modeler but rather the way the engine evaluates input mapping.

So I noticed that if I move the property on top of the properties list, it evaluates correctly. The `controlRoomUrl` property has to be lifted accordingly. Try out this template:

```json
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "test FEEL",
  "id": "465623b7-f64c-40de-8c2a-e2bf4c46bbc7",
  "version": 1,
  "documentationRef": "https://docs",
  "category": {
    "id": "connectors",
    "name": "Connectors"
  },
  "appliesTo": [
    "bpmn:Task"
  ],
  "elementType": {
    "value": "bpmn:ServiceTask"
  },
  "groups": [
    {
      "id": "operation",
      "label": "Operation"
    },
    {
      "id": "authentication",
      "label": "Authentication"
    },
    {
      "id": "configuration",
      "label": "Configuration"
    },
    {
      "id": "input",
      "label": "Input"
    },
    {
      "id": "output",
      "label": "Output"
    },
    {
      "id": "errors",
      "label": "Error Handling"
    }
  ],
  "properties": [
    {
      "type": "Hidden",
      "value": "io.camunda:http-json:1",
      "binding": {
        "type": "zeebe:taskDefinition:type"
      }
    },
    {
      "label": "Operation type",
      "id": "operationType",
      "group": "operation",
      "value": "listAvBotRuns",
      "type": "Dropdown",
      "choices": [
        {
          "name": "List available unattended Bot Runners",
          "value": "listAvBotRuns"
        }
      ],
      "binding": {
        "type": "zeebe:input",
        "name": "operationType"
      }
    },
    {
      "label": "Room URL",
      "description": "this room url will use for all requests",
      "group": "configuration",
      "type": "String",
      "value": "community.cloud.automationanywhere.digital",
      "binding": {
        "type": "zeebe:input",
        "name": "controlRoomUrl"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "first url, for auth.",
      "description": " in real template it will be hidden property",
      "type": "String",
      "group": "configuration",
      "feel": "optional",
      "value": "=\"https://\"+controlRoomUrl+\"/v1/authentication\"",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.url"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Type",
      "id": "authenticationType",
      "group": "authentication",
      "description": "this auth for example",
      "value": "userNamePasswordAuth",
      "type": "Dropdown",
      "choices": [
        {
          "name": "Authenticate (username and password)",
          "value": "userNamePasswordAuth"
        }
      ],
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.withoutBindingType"
      }
    },
    {
      "id": "credentialsInBodyAuthType",
      "description": "with this auth we do 2 request. first - for authenticate, second - request for action with token",
      "group": "authentication",
      "type": "Hidden",
      "value": "credentialsInBody",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.type"
      },
      "constraints": {
        "notEmpty": true
      },
      "condition": {
        "property": "authenticationType",
        "oneOf": [
          "userNamePasswordAuth",
          "userNameApiKeyAuth"
        ]
      }
    },
    {
      "group": "authentication",
      "description": "this auth type needed for first request in connector (authenticate and get token)",
      "type": "Hidden",
      "value": "noAuth",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.authentication.type"
      },
      "constraints": {
        "notEmpty": true
      },
      "condition": {
        "property": "authenticationType",
        "oneOf": [
          "userNamePasswordAuth"
        ]
      }
    },
    {
      "id": "tokenAuthType",
      "description": "this auth type needed for second request in connector",
      "group": "authentication",
      "type": "Hidden",
      "value": "noAuth",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.type"
      },
      "constraints": {
        "notEmpty": true
      },
      "condition": {
        "property": "authenticationType",
        "oneOf": [
          "tokenAuth"
        ]
      }
    },
    {
      "id": "authenticationMethod",
      "type": "Hidden",
      "value": "post",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.method"
      }
    },
    {
      "label": "Username",
      "group": "authentication",
      "type": "String",
      "feel": "optional",
      "value": "testcamunda0001@gmail.com",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.body.username"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Password",
      "group": "authentication",
      "type": "String",
      "feel": "optional",
      "value": " VKFycP7AVVr8-",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.body.password"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "multipleLogin",
      "group": "authentication",
      "type": "Dropdown",
      "value": "false",
      "choices": [
        {
          "name": "TRUE",
          "value": "true"
        },
        {
          "name": "FALSE",
          "value": "false"
        }
      ],
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.request.body.multipleLogin"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "OutputHeaders",
      "description": "this expression will get token from authenticate resopponse and put it to next request",
      "group": "input",
      "type": "Hidden",
      "value": "={\"X-Authorization\":\"asObject:token.asString\"}",
      "binding": {
        "type": "zeebe:input",
        "name": "authentication.outputHeaders"
      },
      "constraints": {
        "notEmpty": true
      },
      "condition": {
        "property": "authenticationType",
        "oneOf": [
          "userNamePasswordAuth",
          "userNameApiKeyAuth"
        ]
      }
    },
    {
      "id": "authenticationMethod",
      "type": "Hidden",
      "value": "post",
      "binding": {
        "type": "zeebe:input",
        "name": "method"
      }
    },
    {
      "label": "second url, for next request with token",
      "description": " in real template it will be hidden property",
      "type": "String",
      "group": "configuration",
      "feel": "optional",
      "value": "=\"https://\"+controlRoomUrl+\"/v1/devices/runasusers/list\"",
      "binding": {
        "type": "zeebe:input",
        "name": "url"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "body to second url",
      "description": "",
      "type": "String",
      "group": "configuration",
      "feel": "required",
      "value": "={\"sort\":[],\"filter\":{},\"page\":{}}",
      "binding": {
        "type": "zeebe:input",
        "name": "body"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Result variable",
      "description": "Name of variable to store the response in. Details in the <a href=\"https://docs.camunda.io/docs/components/connectors/use-connectors/#result-variable\" target=\"_blank\">documentation</a>",
      "group": "output",
      "type": "String",
      "binding": {
        "type": "zeebe:taskHeader",
        "key": "resultVariable"
      }
    },
    {
      "label": "Error expression",
      "description": "Expression to handle errors. Details in the <a href=\"https://docs.camunda.io/docs/components/connectors/use-connectors/#bpmn-errors\" target=\"_blank\">documentation</a>",
      "group": "errors",
      "type": "Text",
      "feel": "required",
      "binding": {
        "type": "zeebe:taskHeader",
        "key": "errorExpression"
      }
    }
  ]
}
```

It looks like the problem is related to how the engine evaluates nested properties.

As we cannot do anything about this in the application, I am closing the issue. Let's continue the conversation on this with the engine developers.

**Closed by barmac** 2023-02-17 10:46 UTC
Labels: bug, ready, element templates
