### ISSUE TITLE
When changing a condition start event in an event process from interrupting to non-interrupting the condition is lost

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#647] opened 2017-08-23 13:43 UTC
Whenever I morph the type of the conditional start event in an event subprocess from interrupting to non-interrupting (or the other way round) the condition is loist.

Might apply to other types as well - haven't checked.

![grafik](https://user-images.githubusercontent.com/1217596/29618859-ba478200-8819-11e7-93ca-d838e6126b1d.png)

**Comment by berndruecker** [comment] 2017-08-23 13:43
Also true for timer start event

**Comment by nikku** [comment] 2019-08-12 07:45
Duplicate of https://github.com/camunda/camunda-modeler/issues/678.

**Comment by nikku** [comment] 2019-08-12 07:53
This is fixed via https://github.com/camunda/camunda-modeler/commit/2415cf9ba925b1b303923187c3556db468a0db0f / `bpmn-js@5.0.0-beta`.

**Closed by nikku** 2019-08-12 07:53 UTC
Labels: backlog, bug, modeling
