### ISSUE TITLE
Literal expression editor styles broken

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#4550] opened 2024-09-25 09:06 UTC
### Describe the bug

The styles of the literal expression editor are broken.

# 5.28

<img width="960" alt="Camunda_Modeler_cUyDlre0ni" src="https://github.com/user-attachments/assets/266822d8-e2ba-4239-b423-4d8dc925eb11">

# 5.26

<img width="960" alt="Camunda_Modeler_k6mwsTJHwg" src="https://github.com/user-attachments/assets/c7028ae5-0f90-43b3-9a89-1169f35ec912">

### Steps to reproduce

1. Open literal expression editor
2. Styles broken

### Expected behavior

Styles not broken.

### Environment

- Camunda Modeler Version: 5.28-rc.1

**Comment by barmac** [comment] 2024-09-25 09:14
Styles break only after you open a BPMN diagram.

**Comment by barmac** [comment] 2024-09-25 09:15
https://github.com/user-attachments/assets/78a8f60e-b3bc-4e87-b62a-b9bfbd343b9a

**Comment by barmac** [comment] 2024-09-25 09:16
Reproducible in 5.27:
![image](https://github.com/user-attachments/assets/20237442-9174-4ae0-baa0-4a940b971642)

**Comment by barmac** [comment] 2024-09-25 09:18
I suspect that BPMN styles introduce some CSS reset. Unfortunately, the DMN editor relies on the default user agent styles in multiple places.

**Comment by barmac** [comment] 2024-09-25 09:19
Notice that the problem exists in the Web Modeler too: 
![image](https://github.com/user-attachments/assets/1435e6f8-7339-426a-a7ae-e954276cb001)

**Comment by nikku** [comment] 2024-10-01 09:28
Related to https://github.com/camunda/camunda-modeler/issues/4550.

**Comment by jarekdanielak** [comment] 2024-10-14 18:36
The reason is the carbon style, as I described in my [comment](https://github.com/camunda/camunda-modeler/pull/4599#issuecomment-2411775603) to a pull request that closes a similar issue on welcome page.

I created an issue where we can discuss it and a PR with a _hotfix_.

https://github.com/bpmn-io/variable-outline/issues/4

**Comment by jarekdanielak** [comment] 2024-10-18 06:38
Fixed upstream in https://github.com/bpmn-io/dmn-js/pull/907

**Comment by nikku** [comment] 2024-10-18 06:41
@jarekdanielak Let's release + integrate the fix for this.

**Closed** 2024-10-24 09:27 UTC
Labels: bug, needs review, DMN, ui
