### ISSUE TITLE
Have elements and labels visually connected when selected

### ISSUE THREAD

**Issue by nevries** [camunda/camunda-modeler#952] opened 2018-10-18 19:39 UTC
__Is your feature request related to a problem? Please describe.__

When labels are positions not directly near the element they belong to, for example for long sequence flows with a lot of actions, it is hard to keep track which label corresponds to which sequence flow.

__Describe the solution you'd like__

When I select a label (or an element), I would like to see which element (or label) belongs to the selected one. For example by highlighting both.

__Describe alternatives you've considered__

One could also think about a way to "reset" the position of the label. For example, if it is gone far away from the corresponding element.

**Comment by nikku** [comment] 2018-10-22 07:08
That would be a great UX improvement indeed.

**Comment by philippfromme** [comment] 2018-10-23 09:41
Duplicate of https://github.com/camunda/camunda-modeler/issues/369.

**Closed** 2018-10-23 10:20 UTC
Labels: BPMN, CMMN, backlog, enhancement, interaction, modeling, ux
