### ISSUE TITLE
Cannot create a data association in a collapsed subprocess

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2752] opened 2022-02-11 11:15 UTC
__Describe the Bug__

When I try to connect data object reference to anything in a collapsed subprocess, it breaks the modeler.

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/28307541/153582156-e2540915-ae58-4dca-b8b0-eb7c21cfc552.png">

__Steps to Reproduce__

1. Create a collapsed subprocess and drill down
2. Create a data object reference and try to connect it to anything.
3. now this happens

__Expected Behavior__

No error is thrown.

__Environment__

- OS: MacOS
- Camunda Modeler Version: 5.0.0-alpha.1
- Execution Platform: Camunda Platform
- Installed plug-ins: [...]

Probably related to https://github.com/camunda/camunda-modeler/issues/2751

**Comment by marstamm** [comment] 2022-02-11 11:51
Same root cause as https://github.com/camunda/camunda-modeler/issues/2751:

https://github.com/bpmn-io/bpmn-js/blob/b8ed73b7f8e4c47d9b2bf10a565bd8fd7f2bc953/lib/features/ordering/BpmnOrderingProvider.js#L72-L74

The ordering provider explicitly states only Process and Collaboration should be containers, when it should be all root elements. I will look into it if

1. it is according to the spec, it can only be child of a process. Then we have to forbid placing it in a subprocess
2. or if we can loosen it to include `bpmn:FlowElementsContainer` as a container

**Comment by marstamm** [comment] 2022-02-11 12:21
I could not find anything in the spec limiting these elements to only exist in the root.

I would allow these elements to also be drawn in `bpmn:FlowElementsContainer`s. This has side effects (e.g. Associations would not always be on top), but would then be automatically moved when collapsing the subprocess.

Previously:
![image](https://user-images.githubusercontent.com/21984219/153590520-c67c3216-198e-4fdd-a077-3b5f582f7cc8.png)

New:
![image](https://user-images.githubusercontent.com/21984219/153590472-a1d2f23a-62a2-4493-97ae-4bc7dba2b8fb.png)

It's an improvement if you ask me :see_no_evil:

**Comment by MaxTru** [comment] 2022-02-17 15:08
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1599

**Comment by MaxTru** [comment] 2022-03-18 15:50
Closed via https://github.com/camunda/camunda-modeler/pull/2817

**Closed by MaxTru** 2022-03-18 15:50 UTC
Labels: bug, fixed upstream
