### ISSUE TITLE
macOS dialogs don't remove focus from currently selected element

### ISSUE THREAD

**Issue by jarekdanielak** [camunda/camunda-modeler#4445] opened 2024-08-05 12:12 UTC
### Describe the bug

When you open a dialog on macOS (e.g. Save as...) with diagram element selected in the background, you can still move the element with arrow keys.

https://github.com/user-attachments/assets/66fee1a1-824a-4ca9-ad30-1c707502e6ba

### Steps to reproduce

1. Select any element on a diagram.
2. Trigger Save as... dialog.
3. Try to move the cursor left and right in the `Save as:` field.

### Expected behavior

The focus should be on a dialog window and arrow keys should move the cursor in the input field instead of a diagram element.

### Environment

- OS: macOS Sonoma 14.5
- Camunda Modeler Version: 5.26.0-rc.0

**Comment by barmac** [comment] 2024-08-05 12:45
Duplicate of https://github.com/camunda/camunda-modeler/issues/813

**Closed by barmac** 2024-08-05 12:45 UTC
Labels: bug, backlog
