### ISSUE TITLE
Modeler does not refresh changes

### ISSUE THREAD

**Issue by Cortogrip** [camunda/camunda-modeler#2939] opened 2022-05-03 07:41 UTC
__Describe the Bug__

Modeler does not refresh changes. When a title is changed (for example on a simple flow) the view is not refresh.  Same for all changes in rigght panel.

## Camunda Modeler system information
 * Version: 5.0.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 7

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by smbea** [comment] 2022-05-03 07:53
Please use the bug [issue template provided]( https://github.com/camunda/camunda-modeler/blob/develop/.github/ISSUE_TEMPLATE/BUG_REPORT.md), including the steps to reproduce. This will help us better understand the issue.

**Comment by smbea** [comment] 2022-05-12 07:43
Since there has been no new activity here and I was not able to reproduce the issue with the information provided, I will close this for now. This can be opened again if more information comes in.

**Closed by smbea** 2022-05-12 07:43 UTC
Labels: bug, help wanted
