### ISSUE TITLE
Allow pre-selection of Camunda platform version

### ISSUE THREAD

**Issue by strangelookingnerd** [camunda/camunda-modeler#3696] opened 2023-07-04 08:53 UTC
### Problem you would like to solve

When opening a *.bpmn file in the the modeler the Camunda platform version is `<unset>`

![image](https://github.com/camunda/camunda-modeler/assets/49242855/0cddee58-c34c-4a2b-8c70-eea2d4653a8b)

Until a version is selected (and applied) the user will not be able to see problems/warnings because linting is not enabled until you select a version.

Further if one creates a new *.bpmn file in the the modeler the Camunda platform version is always pre-selected to the "latest stable" version. Which again is good, but might not match the version a user desires and so he has to remember to change the version every time.

For these reasons it would be great if there was a way to configure a specific version that will be pre-selected by default. 

### Proposed solution

For me it would be best to have this option exposed in the [flags.json](https://docs.camunda.io/docs/components/modeler/desktop-modeler/flags/) configuration corresponding to the [ENGINE_PROFILES](https://github.com/camunda/camunda-modeler/blob/31ecc7c1b9ef8dca9974370fd2ef05d30430dcb6/client/src/util/Engines.js#L16) settings:

```
{
    "platform-engine-version": "7.19.0",
    "cloud-engine-version": "8.2.0"
}
```

This way the current behavior won't change but I'd be able to overwrite it if I wanted to.

### Alternatives considered

Alternatively to the proposed solution the setting could be stored in the user-specific settings once a selection was made (`${user.home}\AppData\Roaming\camunda-modeler\config.json`) similar to the `endpoints`.

I could obviously hard-code the defaults I want and rebuild the modeler, but that seems to be a little overkill 💥 

### Additional context

I'd be happy to provide a PR if you think this feature is sensible to you 👍🏼

**Comment by nikku** [comment] 2023-07-04 09:16
Thanks for opening this issue. Is this a duplicate of https://github.com/camunda/camunda-modeler/issues/2491?

**Comment by nikku** [comment] 2023-07-04 09:21
We previously received a contribution to implement this; however [it stalled](https://github.com/camunda/camunda-modeler/pull/3528). We're happy to accept your contribution to build this feature.

**Comment by strangelookingnerd** [comment] 2023-07-04 09:28
@nikku Indeed a duplicate - I will look into https://github.com/camunda/camunda-modeler/pull/3528. Maybe I can give it another shot.

**Closed** 2023-07-04 09:28 UTC
Labels: duplicate, enhancement
