### ISSUE TITLE
Selecting BPMN XML on MacOS with Camunda Modeler broken

### ISSUE THREAD

**Issue by Hafflgav** [camunda/camunda-modeler#3092] opened 2022-08-16 07:41 UTC
### Describe the bug

Hey, 
in the Camunda Desktop Modeler I am trying to select and copy my BPMN XML. Even though copying works fine the selection looks a little bit broken. When trying to select all it looks something like this: 
![image](https://user-images.githubusercontent.com/30292227/184824081-3e93e02b-06d9-44a8-bede-b03d569095a8.png)
 
Fun fact: When I open up a second model in another tab it works perfectly fine.
So there is a workaround to get to the used behaviour and this might only be a edge-case.

### Steps to reproduce

1. Close all BPMN files in the Modeler and quit the Application
2. Open the Modeler with only one BPMN file 
3. Go to the XML Tab 
4. Try to select all and you will notice that this is not really possible as the screenshot above tells. 

### Expected behavior

As a user I would expect that everything is selected. 

### Environment

- OS: MacOS 12.5
- Camunda Modeler Version: 5.2.0
- Execution Platform: Camunda Platform 8
- Installed plug-ins: Linter, Token Simulation 

### Additional context

BPMN Example: 
`<?xml version="1.0" encoding="UTF-8"?><bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:modeler="http://camunda.org/schema/modeler/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Web Modeler" exporterVersion="bebc136" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.0.0" camunda:diagramRelationId="1785a5af-b649-4435-acf0-f40d0ef2d41a">
  <bpmn:process id="template-api-orchestration" name="API Orchestration Tutorial" isExecutable="true">
    <bpmn:startEvent id="StartEvent" name="Start">
      <bpmn:outgoing>Flow_1</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_1" sourceRef="StartEvent" targetRef="make-request"/>
    <bpmn:endEvent id="EndEvent" name="End">
      <bpmn:incoming>Flow_2</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_2" sourceRef="make-request" targetRef="EndEvent"/>
    <bpmn:serviceTask id="make-request" name="Make a request" zeebe:modelerTemplate="io.camunda.connectors.HttpJson.v1.noAuth" zeebe:modelerTemplateIcon="data:image/svg+xml;utf8,%3Csvg%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%221%201%2016%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M17.0335%208.99997C17.0335%2013.4475%2013.4281%2017.0529%208.98065%2017.0529C4.53316%2017.0529%200.927765%2013.4475%200.927765%208.99997C0.927765%204.55248%204.53316%200.947083%208.98065%200.947083C13.4281%200.947083%2017.0335%204.55248%2017.0335%208.99997Z%22%20fill%3D%22%23505562%22%2F%3E%0A%3Cpath%20d%3D%22M4.93126%2014.1571L6.78106%203.71471H10.1375C11.1917%203.71471%2011.9824%203.98323%2012.5095%204.52027C13.0465%205.04736%2013.315%205.73358%2013.315%206.57892C13.315%207.44414%2013.0714%208.15522%2012.5841%208.71215C12.1067%209.25913%2011.4553%209.63705%2010.6298%209.8459L12.0619%2014.1571H10.3315L9.03364%2010.0249H7.24351L6.51254%2014.1571H4.93126ZM7.49711%208.59281H9.24248C9.99832%208.59281%2010.5901%208.42374%2011.0177%208.08561C11.4553%207.73753%2011.6741%207.26513%2011.6741%206.66842C11.6741%206.19106%2011.5249%205.81811%2011.2265%205.54959C10.9282%205.27113%2010.4558%205.1319%209.80936%205.1319H8.10874L7.49711%208.59281Z%22%20fill%3D%22white%22%2F%3E%0A%3C%2Fsvg%3E%0A">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="io.camunda:http-json:1"/>
        <zeebe:ioMapping>
          <zeebe:input source="get" target="method"/>
          <zeebe:input source="https://catfact.ninja/fact" target="url"/>
        </zeebe:ioMapping>
        <zeebe:taskHeaders>
          <zeebe:header key="resultVariable"/>
          <zeebe:header key="resultExpression" value="={&quot;body&quot; : body}"/>
        </zeebe:taskHeaders>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1</bpmn:incoming>
      <bpmn:outgoing>Flow_2</bpmn:outgoing>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="template-api-orchestration">
      <bpmndi:BPMNEdge id="Flow_1acdqfc_di" bpmnElement="Flow_1">
        <di:waypoint x="188" y="100"/>
        <di:waypoint x="240" y="100"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0mx0itt_di" bpmnElement="Flow_2">
        <di:waypoint x="340" y="100"/>
        <di:waypoint x="392" y="100"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent">
        <dc:Bounds x="152" y="82" width="36" height="36"/>
        <bpmndi:BPMNLabel>
          <dc:Bounds x="158" y="125" width="24" height="14"/>
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1jmq3se_di" bpmnElement="EndEvent">
        <dc:Bounds x="392" y="82" width="36" height="36"/>
        <bpmndi:BPMNLabel>
          <dc:Bounds x="400" y="125" width="20" height="14"/>
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_11vg6or_di" bpmnElement="make-request">
        <dc:Bounds x="240" y="60" width="100" height="80"/>
        <bpmndi:BPMNLabel/>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>`

**Comment by nikku** [comment] 2022-08-16 08:26
I believe this is a duplicate of https://github.com/camunda/camunda-modeler/issues/2923. Can you confirm?

**Comment by Hafflgav** [comment] 2022-08-16 08:34
Ah yes! You are right @nikku 👍 
Have scrolled through the list but haven't seen anything similar yet... Haven't looked that far in the past. :)

**Closed** 2022-08-16 08:55 UTC
Labels: bug, duplicate, spring cleaning
