### ISSUE TITLE
Cannot insert the lane in BPMN diagram with multi-level lanes

### ISSUE THREAD

**Issue by slizenko** [camunda/camunda-modeler#2768] opened 2022-02-17 14:49 UTC
I have pool with two level lanes - departments & roles.
![image](https://user-images.githubusercontent.com/50139137/154505311-0b4e2964-4b4f-4d6a-9571-47909f0acf90.png)
[TEST_WF.txt](https://github.com/camunda/camunda-modeler/files/8089552/TEST_WF.txt)

__Steps to Reproduce__
1. Open attached file in Modeler 4.12
2. Insert lane under DEPT1 lane
3. See the bug
![image](https://user-images.githubusercontent.com/50139137/154506418-f1a0bdc6-e7a7-442a-b347-cc04e96e0d65.png)

__Expected Behavior__
1. Lane inserted correct.

__Environment__
- OS: Windows 10
- Camunda Modeler Version: 4.12 x64
- Execution Platform: Camunda Platform

**Comment by smbea** [comment] 2022-03-01 08:32
I am closing this as I could not reproduce this in Modeler 5.0.0-alpha.1.
If there is still an issue, feel free to reach out again.

**Closed by smbea** 2022-03-01 08:32 UTC
Labels: bug
