### ISSUE TITLE
Maximizing the window crashes the modeler (segfault)

### ISSUE THREAD

**Issue by tannerli** [camunda/camunda-modeler#4325] opened 2024-05-31 07:09 UTC
### Describe the bug

When trying to maximize the modeler window, the application crashes with a segfault. It seems to only affect the 5.23 version. I tested 5.17 and 5.22 and they both work as expected

### Steps to reproduce

1. (Run Ubuntu on X.org, don't know if required)
2. Start the modeler
3. Use one of the following:
  * Click the "maximize" window decoration button
  * Drag the window to the top of the screen
4. The application crashes:

```
./camunda-modeler 
INFO app:main:bootstrap starting Camunda Modeler v5.23.0
INFO app:cli parsing [
  '/opt/camunda-modeler/camunda-modeler-5.23.0-linux-x64/camunda-modeler'
] in '/opt/camunda-modeler/camunda-modeler-5.23.0-linux-x64'
INFO app:flags searching for flags.json in paths [
  '/opt/camunda-modeler/camunda-modeler-5.23.0-linux-x64/resources',
  '/home/tannerli/.config/camunda-modeler/resources'
]
INFO app:flags found []
INFO app:flags active {}
INFO app:error-tracking Cannot initialize Sentry:  Crash reports not enabled.
INFO app:plugins searching for plugins/*/index.js in paths [
  '/opt/camunda-modeler/camunda-modeler-5.23.0-linux-x64',
  '/opt/camunda-modeler/camunda-modeler-5.23.0-linux-x64/resources',
  '/home/tannerli/.config/camunda-modeler/resources',
  '/home/tannerli/.config/camunda-modeler'
]
INFO app:plugins found plug-in entries []
INFO app:plugins registered []
INFO app:main:bootstrap received ready
INFO app:workspace restoring /home/tannerli/some.bpmn
INFO app:main:bootstrap received client-ready
INFO app:main window focused
INFO app:workspace saving
Segmentation fault (core dumped)
``` 

### Expected behavior

* No crash
* Maximized window

### Environment

- OS: Ubuntu 24.04
- Camunda Modeler Version: 5.23
- Execution Platform: Camunda 7
- Installed plug-ins: None

**Comment by nikku** [comment] 2024-05-31 07:59
Fixed with nightly and to be shipped with next modeler release.

Closing as duplicate of https://github.com/camunda/camunda-modeler/issues/4299.

**Closed by nikku** 2024-05-31 07:59 UTC
Labels: bug
