### ISSUE TITLE
Form Editor crashes when FEEL expression is created in the File Picker form element

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4644] opened 2024-10-29 15:54 UTC
### Describe the bug

When we create a FEEL expression  in the ` supported file formats field ` of the File Picker form element, the current form editor crashes such that it affects the subsequently created forms as well

### Steps to reproduce

1. Create a form with File picker form element
2. Add a Feel expression to the supported file formats field and create a unparsable feel expression 
3. Correct the unparsable feel expression
4. Even after correcting we could see the following:
-> Feel pop up editor does not open up
-> Form editor properties panel is frozen
->subsequently opened up forms are all affected

https://github.com/user-attachments/assets/6c7fbe38-a903-437a-b95c-df1d93ff4201

### Expected behavior

Adding an unparsable FEEL expression to the form field should not break the form editor

### Environment

- OS: [e.g.MacOS 10.2]
- Camunda Modeler Version: [5.29.0 rc-0]
- Execution Platform: [ Camunda 8]
- Installed plug-ins: [...]

**Comment by GeethaParthasarathy** [comment] 2024-10-29 15:57
cc @camunda/hto

**Comment by vsgoulart** [comment] 2024-10-29 17:22
@GeethaParthasarathy I can't reproduce it. Did I do something wrong? Could check if the steps are correct?

https://github.com/user-attachments/assets/e02e7b06-b0fb-4aff-a181-8f00f6e301e3

**Comment by GeethaParthasarathy** [comment] 2024-10-30 08:17
Hey @vsgoulart I guess there is a missed step this issue happens when there is an error in your Feel expression and then even if you rectify it the form editor is broken 

https://github.com/user-attachments/assets/be1680f0-c5e8-4963-9018-d28ca423bac3

**Comment by vsgoulart** [comment] 2024-10-30 10:17
@GeethaParthasarathy Here's the fix: https://github.com/camunda/camunda-modeler/pull/4647

**Comment by nikku** [comment] 2024-10-30 11:44
Closed via https://github.com/camunda/camunda-modeler/pull/4647.

**Closed** 2024-10-30 12:57 UTC
Labels: bug, needs review
