### ISSUE TITLE
Element template plugin doesn't support non-default templates for bpmn:Process

### ISSUE THREAD

**Issue by Eilenn** [camunda/camunda-modeler#2121] opened 2021-02-26 13:16 UTC
__Describe the Bug__

The documentation (https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates#supported-bpmn-types) says that the element-templates support element bpmn:Process, but element template that doesn't have the property isDefault:true with a property appliesTo:["bpmn:Process"] is not displayed in template catalog, so it cannot be applied. Probable root cause lies in the ElementTemplatesView.getElementTemplates - for process selectedElement seems to be null.
The same template works fine for Task, so it isn't an issue of a faulty template.

__Steps to Reproduce__

1. Copy the file from https://github.com/camunda-consulting/code/blob/master/snippets/camunda-kpi-monitoring-demo/element-template/kpi.json
2. Place the element template in the resources/element-templates directory of the Camunda Modeler installation.
3. Open or restart the modeler
4. Create a BPMN diagram and click on the Open Catalog button for the process
5. The opened catalog modal window shows no templates

__Expected Behavior__

The opened modal window shows a KPI Template which can be applied to the process - elements KPI Unit and KPI Threshold are shown in the properties panel and can be set.

__Environment__

- Windows 10
- Camunda Modeler Version: 4.4.0, 4.5.0,4.6.0 (and possibly earlier versions as well)

**Comment by MaxTru** [comment] 2021-02-26 15:03
Dear @Eilenn ,

thanks for reporting and for the detailed bug description. I was able to reproduce it and as you stated it, probably the reason is that we do not have a selected element for the case of `bpmn:Process`.

We will tackle this.

**Comment by MaxTru** [comment] 2021-03-02 08:11
Closed by https://github.com/camunda/camunda-modeler/pull/2125

**Closed by MaxTru** 2021-03-02 08:11 UTC
Labels: bug, element templates, needs review

**Comment by MaxTru** [comment] 2021-03-04 19:11
Dear @Eilenn ,

we are currently investigating a bug related to this issue (see https://github.com/camunda/camunda-modeler/issues/2128). It turns out that supporting the use case "Apply an element template to a process or collaboration" end-2-end (so in all constellations incl. applying, unlinking and removing) is not trivial to support. Therefore, could you please provide more context on your use case / why you need to apply element templates to processes or collaborations?

Thanks
Max

**Comment by Eilenn** [comment] 2021-03-04 19:38
Hi,
thank you so much for the efforts to fix the issue. The main business need behind this request is the exact functionality that the original github project I linked in the bug description has provided, namely introducing KPIs for the processes. It has been described in the blog post: https://camunda.com/blog/2016/08/kpi-monitoring-with-camunda/ I'm not really interested in the Collaboration part of that example, but your documentation states that you still support the Process element templates - hence the bug report. 
The specific business case is providing a customer with a way of reporting processes that run over the expected time - this value is different for each process and defined by the process owners. As the processes don't have the due date, I know of no other convenient way of monitoring it. Especially since the customer is not an Enterprise customer, so Optimize reporting is not an option.
Best regards,
Eilenn

**Comment by MaxTru** [comment] 2021-03-04 21:25
> Hi,
> thank you so much for the efforts to fix the issue. The main business need behind this request is the exact functionality that the original github project I linked in the bug description has provided, namely introducing KPIs for the processes. It has been described in the blog post: https://camunda.com/blog/2016/08/kpi-monitoring-with-camunda/ I'm not really interested in the Collaboration part of that example, but your documentation states that you still support the Process element templates - hence the bug report.
> The specific business case is providing a customer with a way of reporting processes that run over the expected time - this value is different for each process and defined by the process owners. As the processes don't have the due date, I know of no other convenient way of monitoring it. Especially since the customer is not an Enterprise customer, so Optimize reporting is not an option.
> Best regards,
> Eilenn

Hi Eilenn,

thanks for the quick response. This helps.

Without the element template support, the business users would have to specify the `kpiunit` and `kpi` values manually via the `Extensions` tab. Example:
![Screenshot_20210304_222234](https://user-images.githubusercontent.com/42800119/110032178-222dce80-7d38-11eb-9432-506c0e43163a.png)

Could you please elaborate whether this is a managable solution (from the business user perspective) or not?

Thanks

**Comment by Eilenn** [comment] 2021-03-04 21:35
Hi,
it is not a manageable solution from business/practical perspective, since it's much more error prone than having a template. We're relying heavily on the templating mechanism, since most of our process developers are relatively inexperienced and deploy the processes from multiple projects to a remote engine. Moreover, since the processes are developed in a non-Java environment, the process testing capabilities are severely limited and templating is one of our QA mechanisms in a way. The planned usage of the template would be in a general reporting functionality for a multi-tenant environment, what makes the ease of use and simplification of the process development our top priority in formulating the best practices/guidelines for the developers.
Best regards
