### ISSUE TITLE
Cloud deploy modal is cut off from the window.

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2882] opened 2022-04-01 12:46 UTC
__Describe the Bug__

Choose to deploy a BPMN diagram via cloud we could see that the deploy diagram modal is cut-off from the windows.

__Steps to Reproduce__

1. Create/Open a BPMN diagram in the Camunda 8 Platform
2. Choose to deploy in any of the cloud versions and choose Camunda Platform self-managed and oAuth for authentication.
3. We could see that the deploy diagram modal is cut off from the windows.

__Expected Behavior__

The depoly diagram modal should fit inside the window.

__Environment__

- OS: [ Windows 10]
- Camunda Modeler Version: [5.0.0 Nightly]
- Execution Platform: [Camunda Cloud]
<img width="958" alt="323562a893633abd34adab495812bf0a" src="https://user-images.githubusercontent.com/85225325/161266318-29762666-e5e7-44a0-b64a-62c8f4caa04c.png">

**Comment by andreasgeier** [comment] 2022-04-01 15:43
This isn't expected behavior. Ensure that an overlay dialog does not grow out of the viewport.

I quickly hacked the dialog to showcase how it should work:

https://user-images.githubusercontent.com/938244/161297002-2c378121-c40d-41ce-801e-a84256c5b7a2.mov

This should be done for all overlays including what's new:

https://user-images.githubusercontent.com/938244/161297104-86d66673-9300-4a40-89fb-54a137e7fd8a.mov

**Comment by pinussilvestrus** [comment] 2022-04-03 11:56
Thanks both for your feedback 👍 Moving this to backlog since it's not blocking the release.

**Closed** 2022-04-19 09:27 UTC
Labels: bug, in progress, spring cleaning
