### ISSUE TITLE
Support attribute "required" for checkboxes

### ISSUE THREAD

**Issue by tobiasschaefer** [camunda/camunda-modeler#3529] opened 2023-03-30 06:50 UTC
### Problem you would like to solve

In the Camunda Modeller almost all fields support the attribute `required`. However, checkbox does not. Why?

There is a specific use-case where it makes sense to declare a checkbox as required forcing the user to check it to complete the form: the user must explicitly accept the "general terms and conditions" by setting the checkbox.

### Proposed solution

If `required` is set for the checkbox, then the validation of the form should fail if the checkbox is not set.

Note: one could argue setting `required` could also be fulfilled by having clicked and de-selected the checkbox again. However, this is IMHO not intuitive and contradicts with the fact that sending the form will always transmit `true` or `false`, never `null`.

### Alternatives considered

As a workaround I could use a radio-button with a single element and set the radio-button group to `required`.

However, this looks differently and I have never seen an UI use a radio button for this use case.

### Additional context

@jonathanlukas said I should "definitely" file an issue, see https://camunda-platform.slack.com/archives/C6WGNHV2A/p1680081789973369

### Breakdown (edit by @Skaiir)

- [x] Implement in form-js core (https://github.com/bpmn-io/form-js/pull/595)
- [x] Release a new version of form-js containing the changes (0.14.0)
- [x] Implement linting rules (https://github.com/camunda/form-linting/pull/47)
- [x] Release a new version of the linting rules (0.7.0)	
	- [x] Since we just managed to squeeze in the features to tasklist 8.2, change the defined form-js version for tasklist. https://github.com/camunda/form-linting/pull/48
	- [x] Release a patched version of the linting rules
- [x] [Bump both versions in modeler](https://github.com/camunda/camunda-modeler/pull/3570)
- [x] [Document changes](https://github.com/camunda/camunda-platform-docs/pull/2024)

**Comment by jonathanlukas** [comment] 2023-03-30 15:04
@tobiasschaefer sorry for bothering here, but I think the issue belongs https://github.com/bpmn-io/form-js
wdyt?

**Comment by nikku** [comment] 2023-03-30 15:48
@jonathanlukas The issue is in a fine place as long as it is a request for the Camunda Modeler.

**Comment by nikku** [comment] 2023-03-30 15:49
@tobiasschaefer I believe you pointed to a good use-case for check box (checked) being required. I'll forward your request to the respective team for further assessment.

**Comment by nikku** [comment] 2023-03-30 15:50
CC @christian-konrad @pinussilvestrus

**Comment by Skaiir** [comment] 2023-03-30 16:50
> Note: one could argue setting required could also be fulfilled by having clicked and de-selected the checkbox again. However, this is IMHO not intuitive and contradicts with the fact that sending the form will always transmit true or false, never null.

@tobiasschaefer 

Yeah, this is also the first thing that came to mind, I think it's more of a philosophical distinction,  required has usually meant 'requires a value'. Here it's being re-used as 'requires to be true'. This distinction is also why required was never implemented for checkbox. 

I mean, to be super specific, we could just change the label to something like 'Must be checked', 'Requires checking'. We could use the same schema variable under the hood, or we could use a new one, honestly it's a 30 minute implementation either way.

**Comment by tobiasschaefer** [comment] 2023-03-30 17:19
@jonathanlukas , @nikku : I primarily see this as a feature request for the Camunda Modeller so that as an end user I can set the `required` attribute for a checkbox. 

If I'm not mistaken this also leads to a feature request for form-js to evaluate the `required` attribute.

@Skaiir IMHO it would be better to re-use the `required` attribute and simply add a label in the modeller describing the behaviour. But I'm sure the Camunda UX experts have a better big picture.

I'd love to see feature in the next release. "30 minute implementation" sounds as if could be possible 😀

**Comment by RomanKostka** [comment] 2023-03-31 09:42
@Skaiir 
From my point of view, it makes perfect sense to support checkboxes with a **required** property.
The same goes for the checklist component.

I would also suggest to use the same property, name and behavior as for the other components.

required for a checkbox means that it must be checked.
required for a checklist means that at least one of the items must be checked.

**Comment by Skaiir** [comment] 2023-03-31 10:39
@RomanKostka and following that logic, taglist as well?

**Comment by Skaiir** [comment] 2023-03-31 11:35
Base behaviour is in, now to do the visuals:

https://user-images.githubusercontent.com/17801113/229109842-6690d0e3-b224-4166-b9f5-1a917a2ef415.mp4

**Comment by Skaiir** [comment] 2023-04-04 07:12
Good news, PR is now in review: https://github.com/bpmn-io/form-js/pull/595.

For full product suite integrations, we still need
- [ ] some new linting rules
- [ ] some new docs
- [ ] waiting on the integration cycles

**Comment by Skaiir** [comment] 2023-04-06 05:35
Welp, we built this functionality fast enough that it landed in tasklist 8.2, so there's almost no waiting on the execution side of things. This means we can integrate the new version and linting rules within the modelers ASAP 😃.

**Comment by tobiasschaefer** [comment] 2023-04-25 07:05
Hi @Skaiir ,

do you have a rough idea when this feature will be in the next Camunda Modeler? I'm looking forward to it ;-)

**Comment by pinussilvestrus** [comment] 2023-04-25 07:07
We releases that with form-js@0.14, so once it is integrated in form-playground + camunda-modeler, it will be there. So I'd assume it in with the next regular Camunda Modeler release 👍 

/cc @camunda/modeling-dev correct me if I'm wrong

**Comment by pinussilvestrus** [comment] 2023-04-25 10:53
`@camunda/form-playground@0.6` is released, so it will be included with the next version bump (along with `@bpmn-io/form-js@0.14` and `form-linting@0.7`.

Let me know whether we should open a PR or whether it's already handled via renovate.

**Closed** 2023-04-26 11:57 UTC
Labels: needs review, enhancement, Forms

**Comment by tobiasschaefer** [comment] 2023-04-27 06:43
@Skaiir , @pinussilvestrus , @nikku , @RomanKostka , @jonathanlukas :

I downloaded the nightly of the Camunda Modeler and tested the new feature. Looks good 👍 

Thanks to you all for your contributions 🥇
