### ISSUE TITLE
Can not open bpmn files from 4.6.0v on 4.7.0v on mac

### ISSUE THREAD

**Issue by RorroCis** [camunda/camunda-modeler#2212] opened 2021-04-13 20:04 UTC
__Can not open bpmn files from 4.6.0v on 4.7.0v on mac__

Today I download the dmg 4.7.0v from Camunda Modeler page and I tried to open one of the bpmns that we were working and I received the error ` "filename.bpmn" is not a BPMN, DMN or FORM file.`

__Steps to Reproduce__

1. Have the version 4.6.0 of Camunda Modeler intalled on your mac
2. Try to open this file:
```<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" id="Definitions_06gwgcw" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="4.6.0">
  <bpmn:process id="refundTransaction" processType="None" isClosed="false" isExecutable="true">
    <bpmn:startEvent id="Event_0r30oq2" camunda:asyncBefore="true" />
  </bpmn:process>
  <bpmn:message id="Message_0tetooa" name="TransactionConfirmedEvent" />
  <bpmn:error id="Error_0lduquo" name="Error_00ied8v" errorCode="payments.transactions.cashout.unknownStatus" />
  <bpmn:error id="Error_1f2fg12" name="Error_1170p4c" errorCode="bpmn.too.many.requests" />
  <bpmn:message id="Message_15b82hi" name="RefundRevisionSubmitted${refundOperationId}">
    <bpmn:extensionElements>
      <zeebe:subscription correlationKey="=refundOperationId" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmn:message id="Message_0h91dzx" name="ManualRefundRevisionSubmitted${refundOperationId}">
    <bpmn:extensionElements>
      <zeebe:subscription correlationKey="=refundOperationId" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="refundTransaction">
      <bpmndi:BPMNShape id="Event_0r30oq2_di" bpmnElement="Event_0r30oq2">
        <dc:Bounds x="152" y="102" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```
3. Download de 4.7.0 dmg of Camunda modeler and install it
4. Try to open the same bpmn 

__Expected Behavior__

Open bpmns files from older versions

__Environment__

- OS: MacOS 10.5.7
- Camunda Modeler Version: 4.6.0 & 4.7.0

**Comment by nikku** [comment] 2021-04-14 07:06
Thanks for your bug report. I can reproduce it with the diagram you provided.

Is this a Camunda Platform or Zeebe / Camunda Cloud diagram? Looking at the used namespaces I see both `camunda` and `zeebe` namespaces being used. Due to a bug in the modeler (https://github.com/camunda/camunda-modeler/pull/2213) this makes the diagram unrecognizable for the latest released version.

Future versions of the tool are going to treat this diagram as a Zeebe diagram I believe.

**Comment by nikku** [comment] 2021-04-14 10:34
Closed via https://github.com/camunda/camunda-modeler/pull/2213

**Closed by nikku** 2021-04-14 10:34 UTC
Labels: bug, needs review

**Comment by RorroCis** [comment] 2021-04-14 11:32
> Thanks for your bug report. I can reproduce it with the diagram you provided.
> 
> Is this a Camunda Platform or Zeebe / Camunda Cloud diagram? Looking at the used namespaces I see both `camunda` and `zeebe` namespaces being used. Due to a bug in the modeler (#2213) this makes the diagram unrecognizable for the latest released version.
> 
> Future versions of the tool are going to treat this diagram as a Zeebe diagram I believe.

We were using Zeebe and a few week ago we started a migration to Camunda Platform. Maybe you're seeing both tags because they we're originally a Zeebe diagram and one of the members of the team open it with Camunda modeler and continue to make the changes from there. Maybe that's why we have both tags, and triggers this bug. Thank you so much for your taking care of this so quickly!

**Comment by nikku** [comment] 2021-04-14 12:12
For you it does make sense to double check your diagrams for usages of the `zeebe` namespace.

Ensure that the namespace is gone once you completed the migration. The Camunda Modeler will support both Camunda Cloud / Zeebe and Camunda Platform in the future and a diagram that mixes both implementation hints won't be handled by it.

**Comment by philippfromme** [comment] 2021-04-14 12:43
@nikku 🥇

**Comment by RorroCis** [comment] 2021-04-14 12:53
Will do that! Thank you so much for everything @nikku 😄 !
