### ISSUE TITLE
Changing process properties breaks modeling

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#600] opened 2017-06-07 17:20 UTC
Can be reproduced on Mac and Windows in 1.8.1.

Steps to reproduce:
1. Create a new process, model start event and activity and save bpmn file (no pool)
2. Change Process-ID (notice that the log opens)
3. Try to add more elemens from pallette -> see that modeling is broken

**Comment by nikku** [comment] 2017-06-08 19:22
This is related to the addition of the Minimap:

```plain
Minimap._addElement (file://MODELER_DIR/resources/app.asar/public/index.js:107036:58)
    at Minimap._updateElement (file://MODELER_DIR/resources/app.asar/public/index.js:107015:10)
    at file://MODELER_DIR/resources/app.asar/public/index.js:106830:12
    at Array.forEach (native)
    at file://MODELER_DIR/resources/app.asar/public/index.js:106829:14
    at invokeFunction (file://MODELER_DIR/resources/app.asar/public/index.js:77373:13)
    at EventBus._invokeListener (file://MODELER_DIR/resources/app.asar/public/index.js:77272:19)
    at EventBus._invokeListeners (file://MODELER_DIR/resources/app.asar/public/index.js:77260:24)
    at EventBus.fire (file://MODELER_DIR/resources/app.asar/public/index.js:77220:24)
    at CommandStack._popAction (file://MODELER_DIR/resources/app.asar/public/index.js:75622:20)EventBus._invokeListener @ index.js:77287
index.js:77289 Uncaught TypeError: Cannot read property 'id' of undefined
```

Please inspect the Developer console (`F12` in the Modeler) for errors and paste then together with your bug report.

**Comment by nikku** [comment] 2017-06-08 19:26
Maybe it makes sense to make the Minimap more robust by catching errors internally?

**Comment by mschoe** [comment] 2017-06-09 07:41
I can confirm this issue and inspected the same error notification.

**Comment by mschoe** [comment] 2017-06-09 08:21
Same problem if you set the isExecutable Flag. 

As a workaround you can close the issue and reopen it. Nevertheless, this issue should be fixed asap.

**Comment by philippfromme** [comment] 2017-06-09 08:27
Sorry guys, I found that issue yesterday when I was working on making processes executable by default. I already fixed it in the minimap and updated the minimap version in the Camunda Modeler. Since this is fixed now I'm closing this issue. Thanks for reporting!

**Closed by philippfromme** 2017-06-09 08:27 UTC
Labels: bug, in progress

**Comment by pedesen** [comment] 2017-06-09 09:01
@mschoe The fix is now available via nightly build. I will also do a patch release.

**Comment by philippfromme** [comment] 2017-06-09 09:05
Thanks, @pedesen ! ❤️
