### ISSUE TITLE
Integrate new properties panel for Platform, but hide behind feature flag

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2577] opened 2021-11-22 13:14 UTC
__Is your feature request related to a problem? Please describe.__

With the M51 milestone, the new properties panel for Platform (for Cloud, it is integrated already) is planned to be ready.
We plan to
* Integrate it into the Camunda Modeler
* But hide it behind a feature flag (so old propPanel remains the default)

WHY?:
* Using the new properties panel is a major change from User perspective
* We want to use a bit more time to get feedback, and also use the feature flag to encourage users to give feedback and to allow more users to give feedback

__Describe the solution you'd like__

- [ ] Integrate new properties panel for Camunda Platform
- [ ] Add feature flag (e.g., `new-properties-panel`)
- [ ] Only show new properties panel, if feature flag was set

__Describe alternatives you've considered__

Only integrate once we have the new properties panel user tested and released in 1.0. Downsides of this solution:
* When we don't integrate, we miss out to learn about technical challenges we might face
* When users can't toggle it on via feature flag, we probably miss feedback from a large group of users

__Additional context__

n/a

**Comment by barmac** [comment] 2021-11-24 17:13
We can re-use the way we add the new properties panel to Camunda Cloud BPMN, but use the flag to decide whether the modules should be replaced. What needs to be figured out yet is how we handle the stylesheets. Perhaps we can just leave the old styles in the app as they use a different namespace.

**Comment by barmac** [comment] 2021-11-24 17:19
Just noticed that this issue is a duplicate of https://github.com/camunda/camunda-modeler/issues/2517 🙈

**Closed by barmac** 2021-11-24 17:19 UTC
Labels: ready, enhancement
