### ISSUE TITLE
Deployment tests are failing for no reason

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1812] opened 2020-05-27 07:15 UTC
__Describe the Bug__

[Sometimes](https://travis-ci.org/github/camunda/camunda-modeler/jobs/689798829#L1518) our builds fail due to a timeout of the deployment tests. This is an indicator of [flaky tests](https://testing.googleblog.com/2016/05/flaky-tests-at-google-and-how-we.html) in that test suite.

> We define a "flaky" test result as a test that exhibits both a passing and a failing result with the same code.

This is exactly what happens.

Flaky tests are a problem because they force contributors to restart jobs to get the right result.

__Steps to Reproduce__

1. Trigger build on CI
2. now this happens

__Expected Behavior__

No flakiness.

__Environment__

- OS: Windows (linked CI job)
- Camunda Modeler Version: `v4.0.0-alpha.3`

**Comment by pinussilvestrus** [comment] 2020-08-18 10:25
Is this still in progress?

**Comment by barmac** [comment] 2020-08-18 10:35
I started to work on this as a slack time topic. I will continue later this week.

**Comment by barmac** [comment] 2020-08-26 12:54
Moving this to backlog until we decide on https://github.com/camunda/camunda-modeler/issues/1917 and https://github.com/camunda/camunda-modeler/issues/1918
Work done on https://github.com/camunda/camunda-modeler/tree/1812-refactor-deployment-tool branch.

**Comment by nikku** [comment] 2021-07-15 07:52
Closing this one as I cannot reproduce that issue anymore.

**Closed** 2021-07-15 07:52 UTC
Labels: backlog, bug, spring cleaning, test
