### ISSUE TITLE
Token Simulation Desktop

### ISSUE THREAD

**Issue by Equinox07** [camunda/camunda-modeler#3672] opened 2023-06-16 06:24 UTC
### Describe the bug

![CamundaError](https://github.com/camunda/camunda-modeler/assets/25932772/51abecc7-e108-45e9-9201-935611b57f59)

### Steps to reproduce

1. Download latest version of Desktop Modeler 5.12
2. Add Token Simulation to plugin directory and Open Desktop Modeler with Sample Flow and Toggle simulation
3. Output console displays error

### Expected behavior

Nothing expected in output console

### Environment

- OS: [Windows 11]
- Camunda Modeler Version: [5.12.0]
- Execution Platform: [Camunda Platform Desktop Modeler]
- Installed plug-ins: [camunda-modeler-token-simulation-plugin]

### Additional context

![image](https://github.com/camunda/camunda-modeler/assets/25932772/2e37179e-7c95-4646-9840-76367e8aca79)

**Comment by smbea** [comment] 2023-06-16 09:56
I can reproduce this.

Seems like it was another issue of caused by the removal of the `.properties` class (used [here](https://github.com/camunda/camunda-modeler-token-simulation-plugin/blob/master/client/HideModelerElements.js#L32)) done with https://github.com/camunda/camunda-modeler/pull/3509

**Comment by nikku** [comment] 2023-06-21 10:51
Closed via https://github.com/camunda/camunda-modeler/issues/3674.

**Closed by nikku** 2023-06-21 10:51 UTC
Labels: bug, needs review

**Comment by nikku** [comment] 2023-06-28 18:56
Fixed with Camunda Desktop Modeler v12.0.1
