### ISSUE TITLE
Saving following file deletion does not replace the deleted file

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#2925] opened 2022-04-21 07:04 UTC
__Describe the Bug__

When one creates a new diagram, saves it (triggers the save modal), deletes the resulting file via the OS, and saves again, no file is stored on disk. This is due to the fact that no modification was made to the diagram, and hence the save button does nothing. This is inconsistent with most software out there which will still rewrite the file for you. It's an edge case and not a crucial one, but deserves fixing IMO. 

![electron_hcVJ8P0P8t](https://user-images.githubusercontent.com/17801113/164393170-c8a777d1-73a9-4dee-a438-a38e763c1b6f.gif)

__Steps to Reproduce__

1. New diagram
2. Save (modal)
3. Delete file via filesystem
4. Save again (no modal)
5. File is not rewritten

__Expected Behavior__

File should be rewritten in (5), as per most software out there. (VSCode, notepad, notepad++ kinda)

__Environment__

- OS: All
- Camunda Modeler Version: 5.0.0

**Comment by marstamm** [comment] 2022-04-21 07:13
This behavior also exists on Linux

**Comment by barmac** [comment] 2022-04-21 07:17
I can reproduce it on Mac as well.

**Comment by marstamm** [comment] 2022-05-09 09:38
I would propose the following change:

Remove the dirty/unsaved check before the save.
https://github.com/camunda/camunda-modeler/blob/e72740c750e9593f890eaeed41332ccc855f8c40/client/src/app/App.js#L1391-L1394

This will work the same as with other Editors (checked with VSCode, overrides file even when nothing was changed). I think it is the most pragmatic option, as we would otherwise have to check if the file was removed/modified externally/... since we last saved it.

**Comment by marstamm** [comment] 2022-05-09 11:55
closed via https://github.com/camunda/camunda-modeler/pull/2946

**Closed by marstamm** 2022-05-09 11:55 UTC
Labels: bug, needs review, spring cleaning
