### ISSUE TITLE
TextAnnotation associations disappear from DRD when source decision id is updated

### ISSUE THREAD

**Issue by bhoefman** [camunda/camunda-modeler#995] opened 2018-11-08 13:42 UTC
__Describe the Bug__

TextAnnotation associations disappear from DRD when source decision id is updated

__Steps to Reproduce__

1. create decision on DRD with name = "abc" and id = "Decision_abc"
2. append TextAnnotation to decision "abc"
   - the DRD shows a TextAnnotation associated to decision "abc"
   - the TextAnnotation has `<sourceRef href="#Decision_abc" />`
3. update id of decision "abc" to "Decision_123"
   - the association has disappeared from the DRD
   - the TextAnnotation still has `<sourceRef href="#Decision_abc" />`

__Expected Behavior__

- the association should remain on the DRD
- the TextAnnotation should have `<sourceRef href="#Decision_123" />`

__Environment__

 - OS: Windows 10
 - Camunda Modeler Version: 2.0.3

**Comment by philippfromme** [comment] 2018-11-12 10:41
I cannot reproduce this following the steps you described.

![2018-11-12_11-40-47](https://user-images.githubusercontent.com/7633572/48342418-e440a400-e66f-11e8-88c6-eeea6a989e5e.gif)

**Comment by bhoefman** [comment] 2018-11-12 14:19
Hi Philipp,

The issue occurs when the update is done from the decision table view.
Also, it seems to affect any kind of reference, i.e. not only associations between decision and TextAnnotation.

**Comment by philippfromme** [comment] 2018-11-12 14:38
Okay, I can can confirm that behavior.

> Hint: This seems to be a bug in [IdChangeBehavior](https://github.com/bpmn-io/dmn-js/blob/master/packages/dmn-js-shared/src/features/modeling/behavior/IdChangeBehavior.js#L52).

**Comment by barmac** [comment] 2020-03-12 09:37
Fixed via https://github.com/bpmn-io/dmn-js/pull/485

**Comment by barmac** [comment] 2020-03-16 13:35
Closed via https://github.com/camunda/camunda-modeler/pull/1730

**Closed by barmac** 2020-03-16 13:35 UTC
Labels: bug, fixed upstream, spring cleaning
