### ISSUE TITLE
External file changes are processed incorrectly

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#413] opened 2016-09-09 13:03 UTC
- External change triggers reload dialog twice

Support: https://app.camunda.com/jira/browse/SUPPORT-4636

**Comment by nikku** [comment] 2019-01-23 17:20
Closing this as a duplicate of #1118.

**Closed by nikku** 2019-01-23 17:20 UTC
Labels: bug, channel:support, duplicate, platform:Windows, ready

**Comment by nikku** [comment] 2019-02-06 19:05
Addressed via https://github.com/camunda/camunda-modeler/pull/1150.
