### ISSUE TITLE
Plugins are disabled while starting modeler double clicking on a file

### ISSUE THREAD

**Issue by Ichigo85** [camunda/camunda-modeler#753] opened 2018-03-15 08:54 UTC
Every time I start up the modeler by double clicking on a single file via file manager the plugins are disabled. The plugin menu doesn't appear.
Everything works well if  I firstly open modeler by application launcher.

This happens both on Windows and Linux and with all plugins I tested.

**Comment by nikku** [comment] 2018-03-15 09:05
This is a duplicate of https://github.com/camunda/camunda-modeler/issues/746 and has been fixed on master.

**Closed by nikku** 2018-03-15 09:05 UTC
Labels: duplicate
