### ISSUE TITLE
Using lasso tool activated by "l" key fails

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1229] opened 2019-02-13 16:21 UTC
__Describe the Bug__

When activating the lasso by using the "l" key you have to move the mose before you can select elements by click and drag

![lasso_key](https://user-images.githubusercontent.com/2777965/52726480-8f386500-2fb3-11e9-8872-47323b6f0648.gif)

__Steps to Reproduce__

- press l
- press the left mouse button
- drag the mouse
---> the diagram will be moved

if you move the mouse before click and drag it works as expected

__Expected Behavior__

If it is possible to activate the lasso tool by pressing the "l" key it should work trouble-free.

__Environment__

Please complete the following information:

 - OS: win10
 - Camunda Modeler Version: 3.0.0-beta-0

**Comment by pinussilvestrus** [comment] 2019-02-14 09:39
Reproduced it on MacOS 10.14.3.

**Comment by pinussilvestrus** [comment] 2019-02-19 13:48
Since I was able to reproduce it [inside the demo](https://demo.bpmn.io/new), it will need a fix in [`bpmn-js`](https://github.com/bpmn-io/bpmn-js).

**Comment by nikku** [comment] 2019-02-19 13:52
In this case, it is not a bug recently introduced with `v3.0.0-beta`. Rather, it is a duplicate / caused by the same bug like https://github.com/camunda/camunda-modeler/issues/664.

**Comment by nikku** [comment] 2019-02-19 13:53
I'd suggest that we pull this one out of the milestone, too.

**Comment by pinussilvestrus** [comment] 2019-02-19 13:55
Agree, since it seems to be a long-term issue: https://github.com/bpmn-io/diagram-js/issues/136

**Comment by nikku** [comment] 2020-12-20 23:53
Closed via https://github.com/camunda/camunda-modeler/issues/2040.

**Closed by nikku** 2020-12-20 23:53 UTC
Labels: bug, needs review
