### ISSUE TITLE
Labels moved on importing model

### ISSUE THREAD

**Issue by davidgs** [camunda/camunda-modeler#2566] opened 2021-11-18 12:50 UTC
__Describe the Bug__

When importing a model created from another BPMN tool, Camunda Modeler moves labels such that once exported and imported into another tool, all the labels are mis-aligned. 

This was discovered while preparing for the MIWG interoperability Demo. 

__Steps to Reproduce__

1. Open BPMN file created in another modeling tool (eg. [this diagram](https://github.com/camunda/camunda-modeler/files/7595569/aris.bpmn.txt))
2.change anything (say, the color of an element) and save the file
3. Reopen in other, i.e. Trisotech and see how all labels have moved 120px to the left. 

__Expected Behavior__

Labels or other object should not be repositioned when importing/exporting a file. 

__Environment__

- OS: MacOS
- Camunda Modeler Version: 4.11 (though it also happens in 4.8 - 4.10)
- Execution Platform: NA
- Installed plug-ins: NA

---

Depends on https://github.com/bpmn-io/bpmn-js/issues/1537.

**Comment by MaxTru** [comment] 2021-11-18 13:32
Timeline discussed in Modeler stakeholder meeting: 
* Camunda Modeler Release required end of February (to be used in March OMG Demo)
* Also we will use Camunda Cloud (not Platform)

**Comment by nikku** [comment] 2021-11-24 12:29
I've attached a test diagram for completeness.

**Comment by nikku** [comment] 2021-11-24 12:46
This is due to the nature that we do not handle internal `bpmndi:BPMNLabel` labels in bpmn-js at all at the moment. 

We'd need to properly pick up these labels and maintain them as we go:

* update them as the task label changes
* update them as the task is being moved

**Comment by nikku** [comment] 2021-11-24 12:52
Needs fix via https://github.com/bpmn-io/bpmn-js/issues/1537.

**Comment by MaxTru** [comment] 2021-11-28 07:54
Closing as duplicate of #2591

**Closed by MaxTru** 2021-11-28 07:54 UTC
Labels: bug, ready, miwg
