### ISSUE TITLE
Zoom via mouse wheel should return.

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#749] opened 2018-03-01 09:05 UTC
Hey folks, 

The newest version of the modeler has changed how the zoom works in order to incorporate a better experience for users with track pads. I have some thoughts on this 
1) The vast majority of users do not use track pads because it's a mouse i more efficient 
1) the change has made it more annoying and harder to navigate around the model when using a mouse

I'm gotten a lot of feedback from existing users that (including myself) that this feature should be reversed.

**Comment by nikku** [comment] 2018-03-01 09:31
Thanks @NPDeehan for your feedback.

This is essentially a duplicate of https://github.com/camunda/camunda-modeler/issues/738. As mentioned, track pad support was not the only reason for the switch.

With the new behavior we switched to the default scroll / zoom behavior in basically any application (with Google maps being a rare exception). In addition simply pressing the `CTRL` modifier brings back the old behavior. This is the standard behavior across applications / OS(s), too.

I understand that existing users may have some bad feelings about that because they need to re-learn how to use the Camunda Modeler. However, if you know how to zoom/scroll anywhere and you're new to Camunda you'll probably find your way into the application much quicker now.

**Closed** 2018-03-01 09:36 UTC
Labels: needs discussion, wontfix
