### ISSUE TITLE
Arrows disappear on adding color

### ISSUE THREAD

**Issue by tasso94** [camunda/camunda-modeler#1342] opened 2019-04-10 09:12 UTC
**Steps to reproduce**
1. Open Camunda Model 3.0.1
2. Create a BPMN model with a Sequence Flow
3. Select the Sequence Flow
4. Set an element color to the Sequence Flow

**Expected behavior**
The Sequence Flow arrow is colored.

**Observed behavior**
Th arrow of the Sequence Flow disappears:

![image](https://user-images.githubusercontent.com/58601/55869834-9761ea80-5b87-11e9-9de9-107d5442b3f1.png)

---

Depends on https://github.com/bpmn-io/bpmn-js/pull/972

**Comment by nikku** [comment] 2019-04-10 09:51
This is an issue with Camunda Modeler v2.x, too.

**Comment by nikku** [comment] 2019-04-10 09:54
Problem persists across imports, cf. [example diagram](https://github.com/camunda/camunda-modeler/files/3063146/color-sequence-flow.bpmn.txt)

**Comment by nikku** [comment] 2019-04-11 06:51
The issue is / was that we do / did not properly account for hex (`#aabbcc`) and rgb encoded colors in our BPMN toolkit. This gets fixed via https://github.com/bpmn-io/bpmn-js/pull/972.

**Comment by slizenko** [comment] 2019-05-08 09:11
I have the same problem in Modeler 3.1 for Windows x64 -
when transition colored, direction arrow disappeared.

**Comment by pinussilvestrus** [comment] 2019-05-09 08:29
Closed via aafbda44795d7e2c0bb00aa8a4bbe81956b17b1b

**Closed by pinussilvestrus** 2019-05-09 08:29 UTC
Labels: bug, needs review

**Comment by sebwarnke** [comment] 2019-06-19 19:13
This problem is still there in Modeler 3.1.2

**Comment by nikku** [comment] 2019-06-19 19:53
Correct. It is gone in the nightly though.

**Comment by kurtudis** [comment] 2019-07-17 09:13
relates to SUPPORT-5950
