### ISSUE TITLE
Modeler app crashing and closing after maximizing the window on Linux 

### ISSUE THREAD

**Issue by okaeiz** [camunda/camunda-modeler#4355] opened 2024-06-09 13:22 UTC
### Describe the bug

When I maximize the window, the app suddenly crashes.

### Steps to reproduce

1. Install Camunda Modeler on Linux.
2. Open it.
3. Maximize the window.

### Expected behavior

I expect the app to be maximized with no crash and error.

### Environment

- OS: Ubuntu-22.04
- Camunda Modeler Version: latest
- Execution Platform: any

**Comment by nikku** [comment] 2024-06-10 07:16
@okaeiz I assume you're running on [Camunda Modeler v5.24.0](https://github.com/camunda/camunda-modeler/releases/tag/v5.24.0)? If not, please test it. 

Is there any error message you're seeing when crashing?

This could be a duplicate of https://github.com/camunda/camunda-modeler/issues/4325.

**Closed** 2024-06-11 10:41 UTC
Labels: bug, needs more information
