### ISSUE TITLE
Segmentation fault on arch linux with latest modeler (1.16.2)

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-modeler#877] opened 2018-08-10 06:47 UTC
Heyho guys,

unfortunately I have a problem with the latest camunda modeler, after updating arch linux.
Current kernel version `4.17.13-arch1-1-ARCH`.

On starting the version 1.15.1 or 1.16.2 I get immediately an segmentation fault.

```
[zell camunda-modeler]$ coredumpctl info 1734
           PID: 1734 (camunda-modeler)
           UID: 1000 (zell)
           GID: 1000 (zell)
        Signal: 11 (SEGV)
     Timestamp: Fri 2018-08-10 07:45:37 CEST (8min ago)
  Command Line: ./camunda-modeler
    Executable: /home/zell/camunda/latest/camunda-modeler/camunda-modeler
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (zell)
       Boot ID: 96b9a72f223e43db9ec1856f988291db
    Machine ID: 68a9e4c981354d989daab091d8e0d969
      Hostname: zell-arch
       Storage: /var/lib/systemd/coredump/core.camunda-modeler.1000.96b9a72f223e43db9ec1856f988291db.1734
       Message: Process 1734 (camunda-modeler) of user 1000 dumped core.
                
                Stack trace of thread 1734:
                #0  0x0000000000a4fa30 n/a (/home/zell/camunda/latest/camunda-modeler/camunda-modeler)
``` 

I assume it is related to https://bugs.archlinux.org/task/59550 , https://github.com/electron-userland/electron-builder/issues/2981, https://github.com/electron/electron/issues/13767

-> https://github.com/electron/electron/issues/13972

Workaround for me is to use the version 1.14.0.

**Comment by nikku** [comment] 2018-08-10 06:53
This is not an issue with the latest kernel. As mentioned in the [linked arch bug ticket](https://bugs.archlinux.org/task/59550) it is the glibc upgrade that is causing trouble. Closing this as a duplicate of https://github.com/camunda/camunda-modeler/issues/869.

Cf. [my previous comment](https://github.com/camunda/camunda-modeler/issues/869#issuecomment-411084797) for a temporary workaround.

**Comment by nikku** [comment] 2018-08-19 21:12
Should work again, as the Arch Linux team reverted the glibc changes that broke electron support. 

Furthermore the actual fix in Electron is pending a release, cf. [this PR](https://github.com/electron/electron/pull/13988).

Closing this as fixed.

**Closed by nikku** 2018-08-19 21:12 UTC
Labels: bug
