### ISSUE TITLE
Keyboard shortcut for lasso tool does not work

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1201] opened 2019-02-12 13:48 UTC
// when
I use ctrl + mouse in order to select a group of element

// then
the lasso is not activated

![keyboard shortcut for lasso tool not working](https://user-images.githubusercontent.com/232571/52639798-5de96780-2ed5-11e9-8b05-7618665cbcf0.gif)

**Comment by nikku** [comment] 2019-02-12 16:30
The shortcut shown is wrong. The modifier is SHIFT and has been SHIFT always. 

Closing this as a duplicate of https://github.com/camunda/camunda-modeler/issues/1039 which we fixed in Camunda Modeler `v3.0.0-0`.

**Closed by nikku** 2019-02-12 16:30 UTC
Labels: bug
