### ISSUE TITLE
Move to Origin and Space Tool don't move embedded DI Label Coordinates

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1011] opened 2018-11-14 17:09 UTC
__Describe the Bug__

After Move to Origin or creating spacen the resulting XML file will have the labels 

__Steps to Reproduce__

1. Open a model that contains Label Positions in DI.
2. Use "Move to Origin" or the Space Tool.
3. Save the file as XML.
4. Open in another BPMN tool that does not always shows task labels on their default position, e.g. Trisotech.

__Expected Behavior__

Label Positions are recalculated.

__Environment__

Please complete the following information:

 - OS: Ubuntu 16.04
 - Camunda Modeler Version: nightly

**Comment by falko** [comment] 2018-11-21 10:38
Here are the files in which the issue occurred: 
[Original.bpmn.txt](https://github.com/camunda/camunda-modeler/files/2603858/Original.bpmn.txt)
[Made Space.bpmn.txt](https://github.com/camunda/camunda-modeler/files/2603859/Made.Space.bpmn.txt)
[Made Space + Moved to Origin.bpmn.txt](https://github.com/camunda/camunda-modeler/files/2603860/Made.Space.%2B.Moved.to.Origin.bpmn.txt)

**Comment by nikku** [comment] 2018-11-22 09:30
Can reproduce it now with the diagram you provided.

**Comment by falko** [comment] 2018-11-22 20:45
Almost all the other BPMN tools are using the DI coordinates for embedded labels to achieve pixel-perfect layout and interchange. We don't necessarily have to create them or read them, but we should certainly not destroy them if they are present.

So if we move a shape, the coordinates of the label should be updated. If the label is edited, a quick win could be to remove the label DI, because it might not fit the new label text anymore.

**Comment by falko** [comment] 2018-11-22 20:48
You can have a look at the Bounds Overlay Tool of the BPMN MIWG to see these label DIs in action: http://bpmn-miwg.github.io/bpmn-miwg-tools/visual-test-result-comparison-bounds.html?base=https%3A%2F%2Fraw.github.com%2Fbpmn-miwg%2Fbpmn-miwg-test-suite%2Fmaster%2FTrisotech%20BPMN%20Modeler%206.0.0%2FA.4.0-import.png&overlayFolder=https%3A%2F%2Fraw.githubusercontent.com%2Fbpmn-miwg%2Fbpmn-miwg-tools%2Fgh-pages%2FReference%2FBounds&variation=A.4.0&title=import%20A.4.0

They are particularly necessary for Sub-Process Labels.

**Comment by Skaiir** [comment] 2022-02-08 07:58
closing, duplicate of #2591

if this needs re-opening feel free to do so

**Closed by Skaiir** 2022-02-08 07:58 UTC
Labels: bug, duplicate, BPMN, backlog, miwg
