### ISSUE TITLE
Keyboard shortcuts menu crashes modeler 3.0.1

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#1357] opened 2019-04-26 07:50 UTC
- Hit Help -> Keyboard Shortcuts menu
- a blank screen appears
- Modeler freezes

reproduced on Windows and Mac

**Comment by nikku** [comment] 2019-04-26 08:40
Thanks for reporting.

Closing this as an exact duplicate of https://github.com/camunda/camunda-modeler/issues/1357.

We are working on a fix.

**Closed by nikku** 2019-04-26 08:40 UTC

**Comment by benhoffmann** [comment] 2019-04-26 08:47
The other issue is #1358, just for reference here.

**Comment by nikku** [comment] 2019-04-26 09:06
Thanks for the pointer, I pasted the wrong issue link :wind_face:.
