### ISSUE TITLE
Flaky behavior of {{secrets}} lint warning

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3905] opened 2023-09-29 14:13 UTC
### Describe the bug

When the version is set to 8.3 and we have used a connector template we see the {{secrets}} lint error , but this error sometimes pops up even when I have a version set to 8.1 or sometimes when I move to a DMN diagram. On reload the issue resolves

### Steps to reproduce

1. Create a connector template and set the Camunda version to 8.3
2. We should see the warning for {{secrets}}
3. Move to a different diagram where there is connector templates again and the version is set to 8.1
4. or Move to a DMN diagram
5. We could still see the lint warning

<img width="960" alt="f1ea0c858c043fafff7c17e0d37291f6" src="https://github.com/camunda/camunda-modeler/assets/85225325/5332825a-b1f2-4ace-b9e1-48dfb093b217">

<img width="960" alt="3f71c43e3e28a3ca64b86bca96f0b23f" src="https://github.com/camunda/camunda-modeler/assets/85225325/89df89da-fdd4-438e-9887-3103fa49210d">

### Expected behavior

Lint warning should appear only where it is valid

### Environment

- OS: [Windows 10]
- Camunda Modeler Version: [5.16.0]
- Execution Platform: [ Camunda 8]
- Installed plug-ins: [...]

**Comment by nikku** [comment] 2023-10-04 09:32
Moving to `ready`. We want to root cause this.

**Comment by philippfromme** [comment] 2023-10-09 11:55
Hate to say that I can reproduce this. 🙈

**Comment by philippfromme** [comment] 2023-10-10 08:17
Closed by https://github.com/camunda/camunda-modeler/pull/3916.

**Closed by philippfromme** 2023-10-10 08:17 UTC
Labels: bug, in progress, spring cleaning
