### ISSUE TITLE
Saving incorrectly updates state if switching to XML tab at least once

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#323] opened 2016-06-02 09:30 UTC
Version: 1.0.0

![state](https://cloud.githubusercontent.com/assets/2331533/15740436/2452db92-28b5-11e6-90db-be40389b715d.gif)

**Comment by ricardomatias** [comment] 2016-08-18 13:50
Cannot reproduce it. Might have been fixed with the changes in importing and exporting when switching views.

**Closed by ricardomatias** 2016-08-18 13:50 UTC
Labels: bug, starter
