### ISSUE TITLE
Show lint errors only respective to parent/child in a sub process

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3758] opened 2023-08-04 11:32 UTC
### Problem you would like to solve

Currently when we have a sub-process in a BPMN diagram we could see the lint errors corresponding to parent even when we drill down to the child and vice versa we see the lint errors corresponding to child even we drill up to the parent  which could cause confusion as the elements in the child and the parent can differ and clicking on them when you are not in the respective diagram does not lead to resolve the errors

https://github.com/camunda/camunda-modeler/assets/85225325/e7f35852-42eb-4bee-94b6-ba133359dc43

### Proposed solution

* [ ] show all the lint errors of both parent and child in the problems panel
* [ ] clicking on an error should lead to the respective diagram to resolve

### Alternatives considered

Show lint errors corresponding only to parent or child as we drill down/up the sub process

----

Depends on https://github.com/camunda/camunda-modeler/issues/3758.

**Comment by nikku** [comment] 2023-08-21 08:35
If I understand correctly the issue is that we don't properly jump into (and out of) the sub processes when focusing errors. I'd assume that clicking on the error _always_ focusses the respective element; this implies jumping into the sub-process where needed.

**Comment by philippfromme** [comment] 2023-08-22 14:42
@marstamm This will be addressed by your recent fix, right?

**Comment by marstamm** [comment] 2023-08-23 07:03
Yes, this is fixed upstream 👍

**Comment by nikku** [comment] 2023-08-23 07:42
Fixed upstream via https://github.com/camunda/linting/pull/78.

**Closed** 2023-08-24 13:26 UTC
Labels: needs review, BPMN, enhancement, spring cleaning, linting
