### ISSUE TITLE
Sub Process moves position

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1418] opened 2019-06-28 11:12 UTC
__Describe the Bug__

Sub Process moves position after expand & collapse operation

__Steps to Reproduce__

// given
element chain of star event --> task --> end event

// when
I perform the follwong operations:
1. transform task into expanded sub process
2. collapse the sub process
3. expand the sub process

// then
the position of the sub process has moved and is not aligned with the other elements anymore 

![ezgif-2-066b632b5011](https://user-images.githubusercontent.com/2777965/60338468-51f2d380-99a6-11e9-81db-574fe76f8f92.gif)

__Expected Behavior__

sub process keeps position

__Environment__

Please complete the following information:

 - OS: linux
 - Camunda Modeler Version: [3.2.0 nightly-190628]

**Comment by barmac** [comment] 2019-06-28 13:23
Related to https://github.com/bpmn-io/bpmn-js/pull/1026

**Comment by pinussilvestrus** [comment] 2019-06-30 10:54
Could also be related to https://github.com/bpmn-io/bpmn-js/issues/1103

**Comment by pinussilvestrus** [comment] 2019-07-01 12:58
**Root Cause**

The movement comes from an [offset generated by `GridSnapping`](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/grid-snapping/behavior/ResizeBehavior.js#L21).

**Comment by pinussilvestrus** [comment] 2019-07-02 07:18
Regarding the _horizontal movement_ of the SubProcess:

The movement resolves in [newly calculated optimal bounds](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/auto-resize/AutoResize.js#L128) which takes the [automatically created start event](https://github.com/bpmn-io/bpmn-js/pull/1039) into account. That's why the start Event seems to be moved inside the SubProcess after re-expanding (as the screencast above reveals).

**Comment by pinussilvestrus** [comment] 2019-07-02 09:18
After a discussion with @volkergersabeck we concluded to postpone this when we tackle an overall improvement-run regarding _Modeling with SubProcesses_ in the next quarter.  This will include several improvements like this one or  https://github.com/camunda/camunda-modeler/issues/1244, https://github.com/camunda/camunda-modeler/issues/1343.

Roo-Cause-Analysis is described in following commits

* https://github.com/camunda/camunda-modeler/issues/1418#issuecomment-507253683, vertically movement + disaligned sequence flows
* https://github.com/camunda/camunda-modeler/issues/1418#issuecomment-507552317, horizontally movement

**Comment by nikku** [comment] 2020-11-06 09:54
Closing this as we do not allow to collapse sub-processes anymore.

**Closed by nikku** 2020-11-06 09:54 UTC
Labels: backlog, bug
