### ISSUE TITLE
Unable to use same Id after task transform

### ISSUE THREAD

**Issue by menski** [camunda/camunda-modeler#97] opened 2015-11-27 09:43 UTC
Problem:
- If I transform a task to another type the id will be changed and I can't change it back to the old one

Steps to reproduce:

- Drag task from pallet and change id to "myId"
![initial-id](https://cloud.githubusercontent.com/assets/516296/11438163/5e4f5f42-94f3-11e5-83f7-1053194acb18.png)
- Transform task to User Task (the id will be automatically changed)
![changed-id](https://cloud.githubusercontent.com/assets/516296/11438178/77a63920-94f3-11e5-82a4-c502f0093450.png)
- Try to change id back to "myId"
![invalid-id](https://cloud.githubusercontent.com/assets/516296/11438183/801fe3da-94f3-11e5-91f1-554751a66b5e.png)

Expected Behavior:
- I can use "myId" again for the transformed task id
- (Optional) The id isn't changed during transformation

**Comment by nikku** [comment] 2015-11-27 09:53
Ok, so the issue is that IDs are not released, after element deletion. Otherwise you'd be able to assign it back. 

We went for the current approach (giving a new ID to the element) on purpose. Our thinking was: The element will be a new one so this should be indicated through an ID change.  It may be more convenient for users if the ID would stay the same though.

We'll probably need to iterate over that again and come up with something clever ... :wink;

**Comment by nikku** [comment] 2016-02-26 07:51
Need fix / refactoring in bpmn-js (via bpmn-io/bpmn-js#421).

**Comment by alpheios** [comment] 2016-03-08 08:21
We would be very happy, if ids would not change, when a bpmn element is transformed.
We identify bpmn elements in our workflow engine by the id. If the id changes the means of identification is lost. Our engine does not recognize the elements anymore and the linked behaviors (scripts, screens, ...) are lost.


A solution could be, to introduce a permanent uuid as an extension to the current element id. But I think I would prefer the id simply to not change. (Though I can understand the idea, why the id changes.)

**Closed** 2016-04-21 10:03 UTC
Labels: bug, needs review

**Comment by pedesen** [comment] 2016-04-21 10:11
@alpheios We closed this issue, because the original bug is fixed. But we opened another feature request issue regarding the id retaining when morphing: https://github.com/bpmn-io/bpmn-js/issues/513
