### ISSUE TITLE
Changing a DMN decision id does not update information requirements pointing to it

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1378] opened 2019-05-21 22:35 UTC
__Describe the Bug__

Changing a DMN decision id does not update information requirements pointing to it The information requirement disappears from the diagram but stays in the XML and causes an exception upon deployment in the engine.

__Steps to Reproduce__

1. Create two decisions connected with an information requirement
2. Rename the id of the required decision in the property panel

__Expected Behavior__

The information requirement is updated and stays visible.

__Environment__

Please complete the following information:

 - OS: Kubuntu 18.04.2 LTS
 - Camunda Modeler Version: 3.1.1 nightly of 2019-05-20

**Comment by pinussilvestrus** [comment] 2019-05-22 12:48
This is a duplicate of https://github.com/camunda/camunda-modeler/issues/1338, right? If yes, let's close this issue.

**Closed** 2019-06-03 14:00 UTC
Labels: help wanted
