### ISSUE TITLE
Name of DataOutputAssociation is unknown

### ISSUE THREAD

**Issue by michel777777** [camunda/camunda-modeler#2333] opened 2021-06-24 20:37 UTC
__Describe the Bug__

The name of DataOutPutAssociation is "unknow"

__Steps to Reproduce__

1. I open n ew diagram
2. I create a DataObjectReference
3. I connect the DataObjectReference to the Start Event -> it will created a DataOutputAssociation
4. I fill out the Name in the Poperties Panel for the DataOutputAssociation
5. No warning , no error
6. I close the model
7. I reopen the model
8. In the log: diagram_1.bpmn] unknown attribute <name> [ warning ]

__Expected Behavior__

No warning

__Environment__

- OS: Windows 10
- Camunda Modeler Version:  4.8.1
- Execution Platform: Camunda Platform
- Installed plug-ins: no one
![put_name](https://user-images.githubusercontent.com/86347050/123328960-87523d80-d53c-11eb-9e2a-0afea3dd1ccc.png)
![after_reopening](https://user-images.githubusercontent.com/86347050/123328973-8b7e5b00-d53c-11eb-9bfc-12fc2d9e54f9.png)
[diagram_1.zip](https://github.com/camunda/camunda-modeler/files/6712016/diagram_1.zip)

**Comment by pinussilvestrus** [comment] 2021-06-25 07:08
Thanks for reporting! Seems like we display the `name` property for elements that can't have it. For example DataAssociations

![image](https://user-images.githubusercontent.com/9433996/123384606-e5127400-d594-11eb-9419-bce24906b252.png)

**Comment by pinussilvestrus** [comment] 2021-06-25 07:11
It's also reproducible in older versions of the Modeler (tested with 4.2).

That would probably need a fix in the [NameProps](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/bpmn/parts/NameProps.js).

**Comment by michel777777** [comment] 2021-06-30 09:27
consider please BPMN 2.0.2 page 34 as well:

![image](https://user-images.githubusercontent.com/86347050/123937122-23919f80-d996-11eb-9e56-dc86e9fcb08f.png)

**Comment by pinussilvestrus** [comment] 2021-06-30 13:23
You're right, given by the specification, `dataAssociation` indeed can have names. It seems to be a meta-model bug then: https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json#L943

**Comment by MaxTru** [comment] 2022-03-11 09:38
@pinussilvestrus will double check if this was already fixed or not

**Comment by pinussilvestrus** [comment] 2022-03-11 09:43
This was fixed with version `v5.0.0-alpha.1`. 

Rationale: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/566

![Bildschirmfoto 2022-03-11 um 10 42 48](https://user-images.githubusercontent.com/9433996/157842290-d0ce9467-d108-442b-ad12-e181c6dd55e4.png)

**Closed by pinussilvestrus** 2022-03-11 09:43 UTC
Labels: bug, BPMN, good first issue, fixed upstream, spring cleaning
