### ISSUE TITLE
Support for numeric and boolean input types

### ISSUE THREAD

**Issue by markfarkas-camunda** [camunda/camunda-modeler#3622] opened 2023-05-17 17:56 UTC
### Problem you would like to solve

It is impossible to define boolean or numeric input type in the element template.

This issue was first raised here: https://github.com/camunda/zeebe/issues/12142

This issue was also raised in the forum: https://forum.camunda.io/t/checkbox-in-a-camunda-8-connector-template/44610 

Consider the following case: I would like to create a Stripe connector based on the rest prototype connector. For creating a charge, specifying the amount is mandatory. This has to be in integer format. [See here](https://stripe.com/docs/api/charges/create?lang=curl#create_charge-amount) 

For this it would make sense to have an input type Number in the element template json file.

Format would look like this:

```
    {
      "label": "Amount",
      "group": "parameters",
      "type": "Number",
      "feel": "optional",
      "binding": {
        "type": "zeebe:input",
        "name": "amount"
      }
    }
```

Supporting numeric inputs would also give the following advantages:

- Validation on the frontend (before deploying the process definition)
- More straightforward input for the user (number type input html tag)
- Eliminating the need of always converting a value in connector code

Also, adding a boolean type would have similar benefits. In the element template I could imagine something like this if we want to make it possible to get the right value for e.g.: the [capture](https://stripe.com/docs/api/charges/create?lang=curl#create_charge-capture) boolean property:

```
    {
      "label": "Capture",
      "group": "parameters",
      "type": "Boolean",
      "feel": "optional",
      "binding": {
        "type": "zeebe:input",
        "name": "capture"
      }
    }
```

Supporting boolean inputs would also give the following advantages:

- Validation on the frontend (before deploying the process definition)
- More straightforward input for the user (checkbox)
- Eliminating the need of always converting a value in connector code

Having Boolean and Number type format would allow us to construct a body property in the element template which consist of different types of values. For example:

```
{
  "propertyName1": "value",
  "numericPropertyName": 3,
  "booleanPropertyName": true
}
```

In this particular Stripe demo case:

```
{
  "currency": "usd",
  "amount": 200,
  "capture": true,
  ...
}
```

Constructing the body in element template looks something like this below. Converting inputs to the proper format makes it even harder to read this long value. That's one reason supporting different format would be really helpful:

```
    {
      "group": "input",
      "type": "Hidden",
      "value": "={\"currency\": if currency= null then null else currency, \"amount\":if amount= null then null else amount,\"capture\":if capture= null then null else capture}",
      "binding": {
        "type": "zeebe:input",
        "name": "body"
      },
      "optional": false
    }
```

### Proposed solution

Make it possible to define an input field with "type": "Number" and "type":"Boolean" instead of "type": "String".

### Alternatives considered

An alternative solution can be to convert the value from string to number with the [number()](https://docs.camunda.io/docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion/#number) function first, and then use this instead, but this approach is very inconvenient and cumbersome.

### Additional context

Related to https://github.com/camunda/camunda-modeler/issues/740
Related to https://github.com/camunda/camunda-modeler/issues/472
Related to https://github.com/camunda/camunda-modeler/issues/2739
Related to https://github.com/camunda/camunda-modeler/issues/1933
Related to https://github.com/bpmn-io/bpmn-js-element-templates/issues/39

**Comment by barmac** [comment] 2023-05-22 09:04
Thanks for suggestion. Is this a blocker for the team?

**Comment by barmac** [comment] 2023-05-22 10:03
Thanks for insights. We will discuss it in the next iteration planning.

**Comment by sbuettner** [comment] 2023-11-20 13:38
@nikku Hey Nico, in the context of element template generation we would like to make use of `boolean` types and therefore need support in the properties panel.

**Comment by nikku** [comment] 2023-12-01 13:17
We'll discuss this topic with the team again.

**Comment by nikku** [comment] 2023-12-01 13:23
An earlier investigation already revealed that building boolean bindings properly is likely not straight forward, cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/768 and following.

I added prior user feedback to this issue, asking for similar functionality. It is definitely unexpected that we don't support `Boolean` as a type.

**Comment by marstamm** [comment] 2024-01-18 14:06
I investigated what needs to be done to support this use-case today. Here is my evaluation on what challenges we need to overcome for it.

From the UI perspective, we already have the required components to allow templating with optional FEEL bindings. These are the same as form-js uses:
![image](https://github.com/camunda/camunda-modeler/assets/21984219/130ffaad-b1f6-428f-acc4-6dbf702d6d42)

However, when it comes to bindings, we face issues:

## Boolean
1. An unchecked checkbox will have no value (**not** false)
2. When used in a field that requires a feel expression (e.g. input mappings), zeebe accepts `true` as a value, but interprets it as the string `"true"`.

### Solution proposal
1
Provide options to define the value that should be set, for checked and unchecked state:

```
{
  "label": "Capture",
  "type": "Boolean",
  "feel": "optional",
  "checkedValue": "true", // optional, default: true
  "uncheckedValue": "false", // optional, default: undefined
  "binding": {
    "type": "zeebe:input",
    "name": "capture"
  }
}
```
This also allows checkboxes for other use-cases, where the property itself is not a boolean number, such as "Enable retries" setting "retries" to 3 with `"checkedValue": "3"`

2
See Below

## Number

Same as 2️⃣  for Boolean values, setting a number `123` in an input mapping without a feel expression, will result in the engine interpreting it as the string `"123"`

### Solution Proposal
2.1
Do not support (optional-) FEEL expressions for these custom elements. If we know which fields require a feel expression, we can then adjust the value by pre-fixing the value with `=` as a feel expression. However, this would limit the usability of these fields. In my opinion, allowing custom FEEL expressions allows us to build much more powerful connectors.

2.2
Similar to the first option, we could automatically prefix the `=` when we know the field requires it. However, because we use the content of the property exclusively to know if the property is a feel expression, we would need some additional logic. Both left and right side are the same value in the XML:
![image](https://github.com/camunda/camunda-modeler/assets/21984219/962fd336-435d-4468-8312-bbfad8ee71d1)

If we check if the value after `=` is atomic, we would show the checkbox/number input when reloading the properties panel. Even if the user previously used the editor to change the value. Only when an expression or variable name is used in the field would we show the feel editor.

---

As we need to know about the places which require feel in both cases, I would propose to go for 2.2, as it allows us more flexibility in building templates.

**Comment by nikku** [comment] 2024-01-18 15:30
> Both left and right side are the same value in the XML:
> 
> ![image](https://github.com/camunda/camunda-modeler/assets/58601/a8bb0420-3608-4b2c-988f-35b42a1f0c59)

Unfortunately this is not true. In core (engine) _all_ fields without `=` prefix are interpreted as strings, so passing `someNumber="15"` as an input mapping would yield the string `15`. Only `= 15` will yield the actual number. 

In other places interpretation of the value is completely user defined (`zeebe:properties`, `zeebe:taskHeader`).

In form-js things are easier, as we _know_ which fields are numbers, and we interpret them as  such. Element templates in contrast can bind to arbitrary properties. This is why it is particularily tricky to bind to everything that is _not a string_.

> Eliminating the need of always converting a value in connector code

@markfarkas-camunda This is an interesting expectation. I presume you mean you don't want to convert when using an input mapping? Or do you refer to other things as well, i.e. `zebee:property` with automatic type cohersion (which is impossible).

**Comment by marstamm** [comment] 2024-01-18 17:16
> Unfortunately this is not true. 

I am aware of that, as described in the problem section. This is in context of the solution proposal of 2.2, where we would automagically add the `=` sign. With this solution, both inputs would result in the same XML for input/output mappings

**Comment by nikku** [comment] 2024-01-19 07:11
> Similar to the first option, we could automatically prefix the `=` when we know the field requires it. 

We may know for input mappings. But what about other things such as additional configuration (`zeebe:property`, `zeebe:taskHeader`)? We don't know how these properties are interpreted, and hence don't know if `= 10` should be serialized or `10`. 

One example is webhook inbound (start) connector where there exists _no_ input mappings, but tons of FEEL expressions (that may be fed by `Number` fields):

![image](https://github.com/camunda/camunda-modeler/assets/58601/c395c25f-0196-49e0-b03f-360dc5d1630e)

----

My suggestion is: Let us not do magic, but find a robust solution to handle that. This is reflected on an earlier comment of mine (https://github.com/bpmn-io/bpmn-js-element-templates/issues/39#issuecomment-1876757920).

**Comment by marstamm** [comment] 2024-01-19 08:42
I see, let's not do any magic then and rely on user input to decide how we handle the input.

However, is our existing `feel` property powerful enough for it? As it currently only handles the display of the property to the user, there is one scenario missing: Binding to a FEEL field but not showing a FEEL editor.
I feel like there should be a third option that means "this is a feel field, but do not allow a feel editor to be displayed". `feel: restricted` maybe?

**Comment by nikku** [comment] 2024-01-19 09:39
> I feel like there should be a third option besides optional and required that means "this is a feel field, but do not allow a feel editor to be displayed". feel: restricted maybe?

I _feel_ the same :slightly_smiling_face:. Maybe it is going to be a different property as well. My proposal is: Let's prototype something and see how it works.

**Comment by marstamm** [comment] 2024-01-19 09:42
> Let's prototype something and see how it works

👍 

> Maybe it is going to be a different property as well

I thought about this as well, but we cover 90% of the use-cases with the existing FEEL property already: if a feel expression is optional, we will not break it if we allow `=15` even when `15` would work as well. It would be redundant to introduce another property that describes feel.

**Comment by marstamm** [comment] 2024-02-06 12:59
Forgot to link the implementation kickoff miro here: https://miro.com/app/board/uXjVNy4sDnE=/

**Comment by nikku** [comment] 2024-02-23 15:02
Released with https://github.com/camunda/camunda-bpmn-js/blob/main/CHANGELOG.md#410

**Comment by nikku** [comment] 2024-02-26 11:05
@barmac identified in https://github.com/camunda/camunda-modeler/pull/4154 a bunch of issues that we want to assess and potentially follow-up on.

CC @marstamm

**Comment by marstamm** [comment] 2024-02-28 10:47
I investigated the reported problems and evaluated them. I also tried to assign priorities to the issues to figure out what needs to be fixed before the release:

| Description | Evaluation | Priority | 
|----------|-------|-------------| 
| [Template requires string as value for numbers](https://github.com/camunda/camunda-modeler/pull/4154#issuecomment-1963689343) | Ease of Use, Not a regression, needs to be added to schema. [We discussed this in the kickoff and we recommend using FEEL as a value when required](https://miro.com/app/board/uXjVNy4sDnE=/?moveToWidget=3458764577561028523&cot=14) | low |
| [Condition with number is never fulfilled](https://github.com/camunda/camunda-modeler/pull/4154#issuecomment-1963717092) | Ease of Use, has workaround with String value | low |
| [`type: Boolean`, `value: true`, `feel: required` breaks](https://github.com/camunda/camunda-modeler/pull/4154#issuecomment-1963706609) | Breaking bug, need to cast value to string before passing to Editor | high |
| [`type: Number` inconsistent increase behavior](https://github.com/camunda/camunda-modeler/pull/4154#issuecomment-1963710867) | Can only reproduce in camunda-bpmn-js and downstream libs, works fine in element template repo. This is also broken for non-feel Number fields | needs more investigation, medium |
| [`type: Boolean`, `feel: optional` does not trigger FEEL editor](https://github.com/camunda/camunda-modeler/pull/4154#issuecomment-1963723301) | can't reproduce | can't reproduce |

**Comment by marstamm** [comment] 2024-03-07 08:24
Only major thing missing for an official release is https://github.com/bpmn-io/internal-docs/issues/919 documentation

**Comment by nikku** [comment] 2024-03-19 17:08
Closing as discussed. Will follow-up with documentation soon.

**Closed by nikku** 2024-03-19 17:08 UTC
Labels: ready, enhancement, element templates, channel:customer
