### ISSUE TITLE
Adding variable name in literal expression removes DRD view

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#3048] opened 2022-07-22 11:53 UTC
### Describe the bug

If you enter a Literal expression box from a DRD, you will see the on your right the panel where you enter details of the expression and on the left is the DRD that you entered from. 

If you start typing in the `Variable Name` field on the right, the DRD on the left will disapear

### Steps to reproduce

1. Create new Camunda 8 DMN Diagram
2. Add a box to the canvas and change it to a Literal expression
3. Open the literal expression box
4. Type anything into the variable name field
5. Observe the items in the DRD panel disapear.

### Expected behavior

The items on the DRD should be unaffected by naming a variable. 

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.1.0
- Execution Platform: Camunda 8
- Installed plug-ins: [...]

### Additional context

![namekillsdrd](https://user-images.githubusercontent.com/10612634/180433822-6e419501-6fa0-4572-b721-ea767519f741.gif)

**Comment by pinussilvestrus** [comment] 2022-07-25 13:52
Thanks for reporting! I can't reproduce this on version `5.0.0`, so I'm moving this to ready as a regression from the last release 👍

**Comment by pinussilvestrus** [comment] 2022-08-05 11:08
This also happens when making other changes, e.g., in the decision table view while the overview is open.

This was introduced once we updated dmn-js: https://github.com/camunda/camunda-modeler/commit/9bbcec9ed62cf9f6846af45e52f1d1584132ab59

**Comment by philippfromme** [comment] 2022-08-05 11:42
I just ran into this when changing DRD elements (decision table or literal expression) ID. Quite annoying.

**Comment by pinussilvestrus** [comment] 2022-08-05 13:00
When this happens, the Overview View is completely gone from the DOM, as it would have been detached

**Before**
![image](https://user-images.githubusercontent.com/9433996/183082497-dfc938ef-78b4-4db2-9979-a6d881ef061e.png)

**After**
![image](https://user-images.githubusercontent.com/9433996/183082374-ebeb337d-e324-44ad-8c0e-a750d15886ed.png)

**Comment by philippfromme** [comment] 2022-08-08 09:20
This is a regression introduced by https://github.com/bpmn-io/dmn-js/pull/698.

**Comment by philippfromme** [comment] 2022-08-09 07:28
Fixed by https://github.com/camunda/camunda-modeler/pull/3080.

**Closed by philippfromme** 2022-08-09 07:28 UTC
Labels: bug, in progress, DMN
