### ISSUE TITLE
Modeller 4.11.1 - SELECT Field, Value loss focus

### ISSUE THREAD

**Issue by Schebi** [camunda/camunda-modeler#2546] opened 2021-11-03 14:23 UTC
__Describe the Bug__

Modeler 4.11.1  Form with SELECT 
Values cant be set or typ in complete flow because the field value loose the focus after each typ of character or string.

![grafik](https://user-images.githubusercontent.com/9645231/140078399-e49e4e5f-8c2a-42c3-adc8-59e878222283.png)

__Steps to Reproduce__

Just make a Form with a new Select Field and type inside the values of each values.
On each typing the field loose the focus. And U have to click inside again to fill the field to the end.

__Expected Behavior__

typing without loose the field focus.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.11.1
- Execution Platform: N/A
- Installed plug-ins: N/A

**Comment by nikku** [comment] 2021-11-04 09:31
Could you use the existing issue template? Adding details on the Modeler version, execution platform and so forth?

Could you please provide complete steps to reproduce your issue, including an example diagram?

**Comment by smbea** [comment] 2021-11-09 08:56
Thanks for the report. I can reproduce the issue.

**Comment by MaxTru** [comment] 2021-11-09 12:03
Added this to our [improve forms journey](https://github.com/camunda/camunda-modeler/issues/2541) epic.

Thanks for reporting!

**Comment by philippfromme** [comment] 2022-01-12 08:52
This is a duplicate of https://github.com/camunda/camunda-modeler/issues/2603. Therefore I'll close it. 👍🏻

**Closed by philippfromme** 2022-01-12 08:52 UTC
Labels: bug, backlog, Forms
