### ISSUE TITLE
DMN Literal Expression Can no longer be Edited in Modeller

### ISSUE THREAD

**Issue by webcyberrob** [camunda/camunda-modeler#3367] opened 2022-12-21 03:48 UTC
### Describe the bug

Create a DMN Literal Expression in a DMN model in modeller. Click on the top left icon to open the literal expression editor and nothing happens. In prior versions this action would open the literal expression editor page.

### Steps to reproduce

1. Create a new DMN model
2. Create a new Literal Expression rather than a Decision Table
3. Clik on the blue icon in top left of literal expression widget - nothing happens...

### Expected behavior

The literal expression edit window is displayed.

### Environment

- OS: Windows 10
- Camunda Modeler Version: [5.6.0]

**Comment by nikku** [comment] 2022-12-21 08:19
I can reproduce your issue. The following error is logged to the console on click:

```
index.esm.js:135 Uncaught (in promise) Error: No provider for "class"! (Resolving: components -> class)
    at s (index.esm.js:135:12)
    at Object.get (index.esm.js:121:15)
    at a (index.esm.js:175:19)
    at index.esm.js:197:16
    at Array.map (<anonymous>)
    at c (index.esm.js:193:31)
    at Array.l (index.esm.js:208:15)
    at df.a [as get] (index.esm.js:169:41)
    at index.esm.js:324:20
    at Array.forEach (<anonymous>)
```

**Comment by nikku** [comment] 2022-12-21 19:10
I could not reproduce this against stock dmn-js.

At this point I believe this has to be either a camunda-dmn-js _or_ Camunda Modeler integration issue.

**Comment by nikku** [comment] 2022-12-21 19:11
@barmac If you want to have a look into this tomorrow, go for it. Otherwise :two: :zero: :two: :three: .

**Comment by barmac** [comment] 2022-12-22 09:21
I can reproduce it and will try to fix it today.

**Comment by barmac** [comment] 2022-12-22 09:24
Literal expression works in camunda-dmn-js but then fails in camunda modeler.

**Comment by barmac** [comment] 2022-12-22 09:28
The error looks like it's related to https://github.com/nikku/didi/issues/17

I discovered that in dmn-js we install an old version of diagram-js which forces v8.0.1 of didi in which the issue is still not fixed. This is due to outdated diagram-js-direct-editing dependency. I will upgrade it and try again.

**Comment by barmac** [comment] 2022-12-22 11:30
This is fixed via https://github.com/camunda/camunda-modeler/commit/7d2699ddc2b4bab70e47842c0aefddf375c1ac7b. Today's nightly will contain the fix.

**Closed by barmac** 2022-12-22 11:30 UTC
Labels: bug, ready

**Comment by nikku** [comment] 2022-12-22 12:22
So actually my dependency bumps did contribute :wink: :tada:
