### ISSUE TITLE
Decision Name not persisted

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#582] opened 2017-05-09 12:42 UTC
Reproduce:
- enter decision name 
- save decision
- open xml view

Expected Behavior:
- decision name attribute is set

Observed Behavior:
- decision name attribute is not set

Hint:
This happens when decision is saved while focus is in the name field

**Comment by philippfromme** [comment] 2017-08-04 13:50
I can not reproduce this in Camunda Modeler 1.9.0 using Windows 10.

**Comment by philippfromme** [comment] 2017-08-04 13:54
@pedesen maybe you can try to reproduce this. I might not fully understand the problem.

**Comment by pedesen** [comment] 2017-08-07 07:45
Can't reproduce either (Camunda Modeler 1.9.0, Linux Mint).

**Comment by philippfromme** [comment] 2017-08-09 11:41
Definition name is updated on [blur](https://github.com/bpmn-io/dmn-js/blob/master/lib/features/definition-id/DefinitionIdEdit.js#L36) so the name not being persisted during editing is desired behavior. I'll close this ticket, I created a [new ticket](https://github.com/bpmn-io/dmn-js/issues/222) for discussion about changing the current behavior (e.g. updating not on blur but on input similar to bpmn-js-properties-panel).

**Closed by philippfromme** 2017-08-09 11:42 UTC
Labels: bug, DMN, ready
