### ISSUE TITLE
Copy/Paste of Sub-Process looses Z-Order of Boundary Event, Compensation Associations and Event Sub-Process Contents

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1339] opened 2019-04-03 17:18 UTC
__Describe the Bug__

Copy & Paste of a an embedded sub-process results in the following issues:
- Z-Order issue: Boundary Events appear bellow the tasks they are attached to
- Compensation Associations disappear
- Event Sub-Process contents disappear

[diagram.bpmn](https://github.com/camunda/camunda-modeler/files/3041816/part2.bpmn.txt)
[log.txt](https://github.com/camunda/camunda-modeler/files/3039948/2019-04-03.Copy%2BPaste.Z-Order.Compensation.Associaton.Emb.SP.Contents.txt)

__Steps to Reproduce__

1. Open the attached BPMN model diagram.bpmn
2. Copy and paste all elements

__Expected Behavior__

The copy looks exactly the same.

__Environment__

 - OS: Ubuntu 18.04.2 LTS
 - Camunda Modeler Version: 3.0.1 (nightly build downloaded on 2019-04-03)

This issue has been discovered during the preparation for the upcoming BPMN MIWG demo in June 2019 in Amsterdam.

**Comment by falko** [comment] 2019-04-03 20:28
The good news is: The boundary event labels stay in position #1325

**Comment by pinussilvestrus** [comment] 2019-04-04 06:48
Thanks for reporting! I was able to reproduce it. Seems like we're having a very specific scenario where multiple bugs occur. When I copy the elements (e.g. the Compensation SubProcess), it works fine.

**Comment by philippfromme** [comment] 2019-11-20 12:57
Using Camunda Modeler v3.4.1 I cannot reproduce any of the issues anymore. Therefore, I will close this issue.

**Closed by philippfromme** 2019-11-20 12:57 UTC
Labels: BPMN, backlog, bug
