### ISSUE TITLE
Wrong element when going from call activity to subprocess expanded in Camunda Modeler

### ISSUE THREAD

**Issue by bassgelo** [camunda/camunda-modeler#1845] opened 2020-06-24 09:35 UTC
__Describe the Bug__

If I have a drawn a call activity in the Camunda modeler, I can always change the type by going to the wrench icon.
There is a case where I change the type to a "subprocess expanded" but instead of getting a subprocess, the modeler draws a task with no type

__Steps to Reproduce__

1. draw a call activity in the camunda modeler, technical details are not important
2. click on the "change type" icon of the call activity and select "subprocess expanded"
3. now the modeler draws no subprocess, instead a task with no type

__Expected Behavior__

1. draw a call activity in the camunda modeler, technical details are not important
2. click on the "change type" icon of the call activity and select "subprocess expanded"
3. now the modeler draws a subprocess expanded, in the default form, with a default start event.

__Environment__

- OS: Ubuntu 16.04
- Camunda Modeler Version: 4.0

**Comment by pinussilvestrus** [comment] 2020-06-24 19:00
Thanks for reporting! I was able to reproduce it. It seems like it is indeed a subprocess, but with the dimensions of a normal task.

![image](https://user-images.githubusercontent.com/9433996/85616219-ab471e80-b65d-11ea-9638-2959f3a3d458.png)

It's also reproducible on older versions (v3.7, v3.6).

**Comment by Skaiir** [comment] 2022-04-07 11:04
I'm going to track this elsewhere:

- https://github.com/bpmn-io/bpmn-js/issues/1631
- https://github.com/bpmn-io/bpmn-js/issues/1632

For now I'll close this ticket

**Comment by smbea** [comment] 2022-04-25 12:48
Closing this since the morphing issue was resolved by https://github.com/bpmn-io/bpmn-js/issues/1631. Will keep https://github.com/bpmn-io/bpmn-js/issues/1632 open so we look into improving the appearance of a morphed expanded subprocess.

**Closed by smbea** 2022-04-25 12:48 UTC
Labels: bug, BPMN, backlog, good first issue, spring cleaning
