### ISSUE TITLE
Adding longer expression and opening it in the FEEL editor moves to the top of the screen

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3980] opened 2023-11-10 13:31 UTC
### Describe the bug

When we add longer expressions in the respective field in the properties panel, try to open the editor it moves to the top of the screen

### Steps to reproduce

1. Create a new BPMN diagram
2. In the properties panel choose a field supporting FEEL 
3. Paste the test below or in general a longer text
4. open the editor
5. The editor jumps to the top of the screen
6. Dragging the editor is no longer possible

https://github.com/camunda/camunda-modeler/assets/85225325/3daa70f7-a4ac-41a0-918a-fedd439cac17

example expression:
```
replace(replace("### Roles this week

| Role | DRI |
|---|---|
| Moderator | @---moderator--- |
| Summary Writer | @---summaryWriter--- |

### Agenda

<!-- If information is documented that shall not be made available for all Camundi, please use and reference an [ELT confidental note](https://drive.google.com/drive/u/1/folders/1EVfpSkZIP3yY90brsNotytYh2SPuqsbJ)-->

#### Status Check-in

- [ ] Conduct status check-in: _ensure the ELT knows status of key-items on our roadmap. Consider next target release in [product hub](https://github.com/orgs/camunda/projects/9/views/31)_.

#### Discussion Topics

_Every ELT member can add discussion points here._

- [ ] ...

#### Management Bugs and Tasks

- [ ] Review [tasks](https://github.com/orgs/camunda/projects/52) that are currently `In progress`.
- [ ] Introduce new [tasks](https://github.com/orgs/camunda/projects/52) that were put into the `Inbox`, potentially assigning them (`/autoassign`) and moving to `Backlog` or `In progress`.

----------------------

Find recordings of all meetings [here](https://docs.google.com/document/d/1PfpCZ1eo8IdVvHdaehAH68VTQLJCRYaoxbih_mQsK9c/edit).

Find ELT confidental notes or link a new note [here](https://drive.google.com/drive/u/1/folders/1EVfpSkZIP3yY90brsNotytYh2SPuqsbJ).


Find all Weeklies (incl. past ones) [here](https://github.com/camunda/engineering-leadership-team/issues?q=label%3Aweekly+).

Cf. [weekly agenda](https://github.com/camunda/engineering-leadership-team/blob/main/.github/ISSUE_TEMPLATE/WEEKLY_NOTE.md), [manually create new agenda](https://github.com/camunda/engineering-leadership-team/issues/new?template=WEEKLY_NOTE.md&labels=weekly)", "---moderator---", nextModerator), "---summaryWriter---", nextSummaryWriter)

```

### Expected behavior

The editor should not be misplaced

### Environment

- OS: [Windows 10]
- Camunda Modeler Version: [5.17.0]
- Execution Platform: [ Camunda 8]
- Installed plug-ins: [...]

**Comment by marstamm** [comment] 2023-11-10 13:36
This probably has the same root-cause as https://github.com/camunda/camunda-modeler/issues/3969

**Comment by marstamm** [comment] 2023-11-28 14:55
Closing as a duplicate of https://github.com/camunda/camunda-modeler/issues/3969

**Closed by marstamm** 2023-11-28 14:55 UTC
Labels: bug, ready
