### ISSUE TITLE
Copy & Pasting multiple elements (including subProcess) leads to strange formatting

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2251] opened 2021-05-10 11:15 UTC
__Describe the Bug__

Copy & Pasting multiple elements (including subProcess) leads to strange formatting. The placing of elements in the paste result is not correct.

__Steps to Reproduce__

1. Model this diagram: 
![Screenshot_20210510_131222](https://user-images.githubusercontent.com/42800119/117650740-5d61d900-b191-11eb-8e25-12254ebc8d16.png) (or copy paste the XML)
2. With CTRL+A & CTRL&C copy everything
3. Open a new diagram
4. Don't(!) delete the start event
5. Paste into the new diagram
6. This happens. Note how the placing is wrong even in the preview:
![bug1](https://user-images.githubusercontent.com/42800119/117650966-a87bec00-b191-11eb-9246-ac0a32bc9457.gif)

__Expected Behavior__

Placing is not changed after copy and paste.

__Environment__

- OS: Linux
- Camunda Modeler Version: 4.8.0-rc0
- Installed plug-ins: none

__Resources__

Diagram used BPMN:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_0k0g7md" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="4.8.0-rc.0" modeler:executionPlatform="Camunda Platform" modeler:executionPlatformVersion="7.15.0">
  <bpmn:collaboration id="Collaboration_1wcmux5">
    <bpmn:participant id="Participant_03g6zas" name="Department A" processRef="Process_0ayy1ro" />
    <bpmn:participant id="Participant_1ejhu0r" name="Department B" />
    <bpmn:participant id="Participant_0w6liww" processRef="Process_1kmkve8" />
    <bpmn:messageFlow id="Flow_121jjfy" sourceRef="Participant_1ejhu0r" targetRef="StartEvent_1" />
    <bpmn:messageFlow id="Flow_1bfat4y" sourceRef="Event_04n9f2e" targetRef="Event_022b1ib" />
  </bpmn:collaboration>
  <bpmn:process id="Process_0ayy1ro" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" name="Invoices Incoming">
      <bpmn:outgoing>Flow_0mbqgx2</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:dataStoreReference id="DataStoreReference_186ql9y" name="Invoice Store" />
    <bpmn:endEvent id="Event_04n9f2e" name="Invoices Processed">
      <bpmn:incoming>Flow_07cigxy</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:subProcess id="Activity_0ux4h5i" name="COMPLEX PIECE OF WORK">
      <bpmn:incoming>Flow_0mbqgx2</bpmn:incoming>
      <bpmn:outgoing>Flow_07cigxy</bpmn:outgoing>
      <bpmn:multiInstanceLoopCharacteristics />
      <bpmn:userTask id="Activity_0ctpf8f" name="Inspect Invoice">
        <bpmn:outgoing>Flow_0kj4tdb</bpmn:outgoing>
      </bpmn:userTask>
      <bpmn:sequenceFlow id="Flow_0kj4tdb" sourceRef="Activity_0ctpf8f" targetRef="Activity_18iuhsv" />
      <bpmn:userTask id="Activity_18iuhsv" name="File Invoice">
        <bpmn:incoming>Flow_0kj4tdb</bpmn:incoming>
        <bpmn:dataOutputAssociation id="DataOutputAssociation_0m5vzgl">
          <bpmn:targetRef>DataStoreReference_186ql9y</bpmn:targetRef>
        </bpmn:dataOutputAssociation>
      </bpmn:userTask>
    </bpmn:subProcess>
    <bpmn:sequenceFlow id="Flow_0mbqgx2" sourceRef="StartEvent_1" targetRef="Activity_0ux4h5i" />
    <bpmn:sequenceFlow id="Flow_07cigxy" sourceRef="Activity_0ux4h5i" targetRef="Event_04n9f2e" />
    <bpmn:textAnnotation id="TextAnnotation_1iv29qk">
      <bpmn:text>Executed for every invoice</bpmn:text>
    </bpmn:textAnnotation>
    <bpmn:association id="Association_05lxl50" sourceRef="Activity_0ux4h5i" targetRef="TextAnnotation_1iv29qk" />
  </bpmn:process>
  <bpmn:process id="Process_1kmkve8" isExecutable="false">
    <bpmn:startEvent id="Event_022b1ib" name="New Invoices">
      <bpmn:outgoing>Flow_1csej18</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:exclusiveGateway id="Gateway_19l4gtq" name="Needs Additional Automated Check">
      <bpmn:incoming>Flow_1csej18</bpmn:incoming>
      <bpmn:outgoing>Flow_0co4k8f</bpmn:outgoing>
      <bpmn:outgoing>Flow_026ofl1</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:serviceTask id="Activity_0ng6mdv" name="Check">
      <bpmn:incoming>Flow_0co4k8f</bpmn:incoming>
      <bpmn:outgoing>Flow_1mpqotm</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Event_1jjvtfb">
      <bpmn:incoming>Flow_1mpqotm</bpmn:incoming>
      <bpmn:incoming>Flow_026ofl1</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1csej18" sourceRef="Event_022b1ib" targetRef="Gateway_19l4gtq" />
    <bpmn:sequenceFlow id="Flow_0co4k8f" sourceRef="Gateway_19l4gtq" targetRef="Activity_0ng6mdv" />
    <bpmn:sequenceFlow id="Flow_1mpqotm" sourceRef="Activity_0ng6mdv" targetRef="Event_1jjvtfb" />
    <bpmn:sequenceFlow id="Flow_026ofl1" name="No check needed" sourceRef="Gateway_19l4gtq" targetRef="Event_1jjvtfb" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_1wcmux5">
      <bpmndi:BPMNShape id="Participant_03g6zas_di" bpmnElement="Participant_03g6zas" isHorizontal="true">
        <dc:Bounds x="129" y="80" width="901" height="450" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="TextAnnotation_1iv29qk_di" bpmnElement="TextAnnotation_1iv29qk">
        <dc:Bounds x="770" y="210" width="170" height="30" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_0mbqgx2_di" bpmnElement="Flow_0mbqgx2">
        <di:waypoint x="268" y="320" />
        <di:waypoint x="363" y="320" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_07cigxy_di" bpmnElement="Flow_07cigxy">
        <di:waypoint x="713" y="320" />
        <di:waypoint x="972" y="320" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="232" y="302" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="205" y="278" width="89" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="DataStoreReference_186ql9y_di" bpmnElement="DataStoreReference_186ql9y">
        <dc:Bounds x="715" y="445" width="50" height="50" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="708" y="502" width="65" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_04n9f2e_di" bpmnElement="Event_04n9f2e">
        <dc:Bounds x="972" y="302" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="964" y="264.5" width="52" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0ux4h5i_di" bpmnElement="Activity_0ux4h5i" isExpanded="true">
        <dc:Bounds x="363" y="220" width="350" height="200" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_0kj4tdb_di" bpmnElement="Flow_0kj4tdb">
        <di:waypoint x="513" y="323" />
        <di:waypoint x="563" y="323" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Activity_1u3pu14_di" bpmnElement="Activity_0ctpf8f">
        <dc:Bounds x="413" y="283" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0o8cuim_di" bpmnElement="Activity_18iuhsv">
        <dc:Bounds x="563" y="283" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Association_05lxl50_di" bpmnElement="Association_05lxl50">
        <di:waypoint x="713" y="261" />
        <di:waypoint x="775" y="240" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Participant_0qcnws0_di" bpmnElement="Participant_1ejhu0r" isHorizontal="true">
        <dc:Bounds x="200" y="650" width="600" height="60" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Participant_0w6liww_di" bpmnElement="Participant_0w6liww" isHorizontal="true">
        <dc:Bounds x="590" y="790" width="600" height="250" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_1csej18_di" bpmnElement="Flow_1csej18">
        <di:waypoint x="688" y="920" />
        <di:waypoint x="745" y="920" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0co4k8f_di" bpmnElement="Flow_0co4k8f">
        <di:waypoint x="795" y="920" />
        <di:waypoint x="860" y="920" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1mpqotm_di" bpmnElement="Flow_1mpqotm">
        <di:waypoint x="960" y="920" />
        <di:waypoint x="1032" y="920" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_026ofl1_di" bpmnElement="Flow_026ofl1">
        <di:waypoint x="770" y="895" />
        <di:waypoint x="770" y="840" />
        <di:waypoint x="1050" y="840" />
        <di:waypoint x="1050" y="902" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="867" y="822" width="86" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_022b1ib_di" bpmnElement="Event_022b1ib">
        <dc:Bounds x="652" y="902" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="637" y="945" width="66" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_19l4gtq_di" bpmnElement="Gateway_19l4gtq" isMarkerVisible="true">
        <dc:Bounds x="745" y="895" width="50" height="50" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="726" y="952" width="88" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1vdpfl1_di" bpmnElement="Activity_0ng6mdv">
        <dc:Bounds x="860" y="880" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1jjvtfb_di" bpmnElement="Event_1jjvtfb">
        <dc:Bounds x="1032" y="902" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_121jjfy_di" bpmnElement="Flow_121jjfy">
        <di:waypoint x="580" y="650" />
        <di:waypoint x="580" y="470" />
        <di:waypoint x="250" y="470" />
        <di:waypoint x="250" y="338" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="DataOutputAssociation_0m5vzgl_di" bpmnElement="DataOutputAssociation_0m5vzgl">
        <di:waypoint x="649" y="363" />
        <di:waypoint x="723" y="445" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1bfat4y_di" bpmnElement="Flow_1bfat4y">
        <di:waypoint x="990" y="338" />
        <di:waypoint x="990" y="750" />
        <di:waypoint x="670" y="750" />
        <di:waypoint x="670" y="902" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>

```

**Comment by MaxTru** [comment] 2021-05-10 11:19
This is not a new behavior, it was also there in `4.7.0`. I am not sure, maybe we even accept it, because pasting a collaboration on a process with existing element is something you shouldnt do anyhow IMO. I would struggle to define a behavior for how it should work. @camunda/modeling-dev wdyt?

**Comment by barmac** [comment] 2021-05-10 11:20
This is because we have to include the existing start event in one of the participants. Not sure how we could fix that.

This is not a regression, so I suggest we place it in the backlog.

**Comment by philippfromme** [comment] 2021-05-10 11:23
Interesting bug. Looking forward to investigating this. 🔎

**Comment by philippfromme** [comment] 2022-01-19 13:56
This is a duplicate of https://github.com/camunda/camunda-modeler/issues/2049.

**Closed by philippfromme** 2022-01-19 13:56 UTC
Labels: bug, backlog
