### ISSUE TITLE
Can we translate interface of Camunda Modeler to another languague?

### ISSUE THREAD

**Issue by goshanoob** [camunda/camunda-modeler#1860] opened 2020-07-08 08:34 UTC
Our team want to translate interface of Camunda Modeler to a customer language. We think a customer will like it, cause he wants to participate in modeling.
Is it possible to edit the Modeler files for this? What files?

**Comment by pinussilvestrus** [comment] 2020-07-08 09:28
This is a duplicate of https://github.com/camunda/camunda-modeler/issues/478, right?

Currently, it's not possible to translate the Modeler UI  and it's still not on our roadmap. This might change once we see an increasing need for it.

**Closed** 2020-07-08 09:30 UTC
Labels: duplicate
