### ISSUE TITLE
Boolean fields/property in templates throw error when set true 

### ISSUE THREAD

**Issue by aleneum** [camunda/camunda-modeler#1933] opened 2020-09-07 15:47 UTC
__Describe the Bug__

When a template field is of type "Boolean", setting it to `true` will cause the following error when the document should be saved:

```
t.search is not a function
    at search (webpack:///node_modules/bpmn-moddle/node_modules/moddle-xml/dist/index.esm.js:1166:38)
    at file:///.../camunda-modeler-4.2.0-win-x64/resources/app.asar/public/bundle.js:11:28283
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:145:15)
    at properties (webpack:///node_modules/bpmn-moddle/node_modules/moddle-xml/dist/index.esm.js:1413:10)
    at parseContainments (webpack:///node_modules/bpmn-moddle/node_modules/moddle-xml/dist/index.esm.js:1230:9)
    at file:///.../camunda-modeler-4.2.0-win-x64/resources/app.asar/public/bundle.js:11:28670
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:145:15)
    at file:///.../camunda-modeler-4.2.0-win-x64/resources/app.asar/public/bundle.js:11:28599
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:145:15)
    at properties (webpack:///node_modules/bpmn-moddle/node_modules/moddle-xml/dist/index.esm.js:1413:10) [ error ]
```

__Steps to Reproduce__

1. Create `<project_folder>\.camunda\element-templates\templates.json` with content:
```
{
    "name": "Mail Task",
    "id": "com.camunda.example.MailTask",
    "appliesTo": [
        "bpmn:ServiceTask"
    ],
    "properties": [
        {
            "label": "Receivers",
            "type": "Boolean",
            "binding": {
                "type": "camunda:inputParameter",
                "name": "receivers"
            }
        }
    ]
}
```
2. Create `test.bpmn` file, save it at `<project_folder>`
3. Open `test.bpmn`
4. Add a task, set its type to `Service Task`
5. Choose `Mail Task` from `Element Template` Dropdown
6. Click `Receivers` checkbox, a checkmark appears
7. Try to save the document or click the XML tab
8. This dialog should appear:

![Screenshot (53)](https://user-images.githubusercontent.com/205986/92403256-57fb4d00-f131-11ea-994f-9aa2dbaf7d81.png)

__Expected Behavior__

* I expected the value for `Receivers` to be saved without any warning.
* I also expected to be able to switch into XML view.

__Environment__

- OS: Windows 10 Version 2004
- Camunda Modeler Version: 4.2.0

**Comment by pinussilvestrus** [comment] 2020-09-07 18:18
Thanks for reporting! I think there is already an issue regarding this: https://github.com/camunda/camunda-modeler/issues/472

Can you double-check whether you mean the same use case?

**Comment by aleneum** [comment] 2020-09-08 07:17
Hi @pinussilvestrus,

> Can you double-check whether you mean the same use case?

I wouldn't say its the same thing since #472 asks for Boolean support. Its definitely related though. The [documentation](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates) mentions:

> type: Defining the visual appearance in the properties panel (may be any of String, Text, Boolean, Dropdown or Hidden)

I understand this as Boolean support is already provided. Additionally, #740 mentions support for checkboxes which is to my understanding already implemented (as seen in the picture).

**Comment by aleneum** [comment] 2020-09-08 07:41
I checked all available types (and adjust the "name" parameter when necessary):

* property: no error, but also no effect (resets after scope change)
* camunda:property: no error, persistent
* camunda:inputParameter: error - t.search is not a function
* camunda:outputParameter (source instead of name): no error, persistent
* camunda:in (target instead of name): no error, persistent
* camunda:out (source instead of name): no error, persistent
* camunda:field: error - t.search is not a function

**Comment by MaxTru** [comment] 2020-09-11 13:31
Thanks for reporting.

The documentation was updated to make this more clear, see [here](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates). As #472 and the documentation point out, Boolean is not supported for all bindings. Boolean type will render a checkbox which will set the respective value to "true", this does not make sense in all cases.  

> property: no error, but also no effect (resets after scope change)

I was not able to reproduce that, could you please provide exact step to reproduce this behaviour in another issue focussed only at that aspect?

Referencing the [docs](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates) I will close this issue. 

I created another issue aiming at providing more meaningful error messages in case a non-valid combination was configured => https://github.com/camunda/camunda-modeler/issues/1939

**Closed by MaxTru** 2020-09-11 13:31 UTC
Labels: bug
