### ISSUE TITLE
Manual "Check for Updates" menu choice not working for 4.7.0

### ISSUE THREAD

**Issue by Camunda-ChrisAllen** [camunda/camunda-modeler#2402] opened 2021-08-24 13:18 UTC
__Describe the Bug__

Please see full description in this Slack thread here:  https://camunda.slack.com/archives/CKGH9LR40/p1629742357036000

Updater in Modeler 4.7.0 thinks I have the latest version, but I do not.  I tried several times with same result.  Earlier the previous week I received a "there is a new version available" message on startup, but I clicked off of it because I was delivering a training at the time.

__Additional context__

The version @Camunda-ChrisAllen used is more than 100days old and he clicked 15 times the button. This means, the staged rollout mechanism cannot be the source for this problem. Ergo I beliebe this is not a duplicate of https://github.com/camunda/camunda-modeler/issues/2263. Let's investigate.

__Steps to Reproduce__

(see above)

__Expected Behavior__

I should get a message that says that a new version is available.

__Environment__

- OS: MacOS 11.4
- Camunda Modeler Version: 4.7.0
- Execution Platform: CP
- Installed plug-ins: none

**Comment by nikku** [comment] 2021-08-25 06:37
This is a duplicate of https://github.com/camunda/camunda-modeler/issues/2263 and will be fixed with the next modeler release.

Thanks for reporting.

**Comment by MaxTru** [comment] 2021-08-25 14:02
Reopening and adjust the description:

The version @Camunda-ChrisAllen used is more than 100days old and he clicked 15 times the button. This means, the staged rollout mechanism cannot be the source for this problem. We need to investigate.

**Comment by MaxTru** [comment] 2022-01-18 12:39
Closed via https://github.com/camunda/camunda-modeler/pull/2684

**Closed by MaxTru** 2022-01-18 12:39 UTC
Labels: bug, needs review, good first issue, spring cleaning
