### ISSUE TITLE
invalid property type "Boolean" for binding type "camunda:inputParameter"

### ISSUE THREAD

**Issue by stphngrtz** [camunda/camunda-modeler#2739] opened 2022-02-10 10:19 UTC
__Describe the Bug__

It is no longer possible to use `Boolean` as type for an input parameter.

__Steps to Reproduce__

1. put the attached element template into `/any/path/.camunda/element-templates`
2. create a new BPMN diagram at `/any/path/diagram_1.bpmn`
3. cannot select template and the following warning is being written to the log window

```
[/any/path/diagram_1.bpmn] template(id: <example>, name: <Example>): invalid property type "Boolean" for binding type "camunda:inputParameter"; must be any of { String, Text, Hidden, Dropdown } [ warning ]
```

__Expected Behavior__

Being able to select the template and a checkbox should be rendered as custom field. See https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates#boolean--checkbox-type

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.10.0 & 4.12.0 (**works in 4.6.0**)
- Execution Platform: Camunda Platform
- Installed plug-ins: None

__Element template__

```
[
    {
        "name": "Example",
        "id": "example",
        "version": 1,
        "appliesTo": [
            "bpmn:ServiceTask"
        ],
        "properties": [
            {
                "label": "Example",
                "type": "Boolean",
                "value": "false",
                "binding": {
                    "type": "camunda:inputParameter",
                    "name": "example"
                }
            }
        ]
    }
]
```

**Comment by pinussilvestrus** [comment] 2022-02-10 11:02
This is intended, I guess: https://github.com/camunda/camunda-modeler/issues/1933#issuecomment-691096643

Also, according to the docs: https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates#camundainputparameter

/cc @MaxTru

**Comment by stphngrtz** [comment] 2022-02-10 12:05
That's what I was afraid of. But why has it been removed? I don't see the downside of being able to pass boolean variables into the context / into service-tasks.

Use-case (just one of many that come to mind): Print receipt (true, false).

**Comment by pinussilvestrus** [comment] 2022-02-10 12:15
Thanks for your input! It seems like we have an open feature request for this: https://github.com/camunda/camunda-modeler/issues/472

The reason why we forbid it (cf. [v4.7](https://github.com/camunda/camunda-modeler/blob/develop/CHANGELOG.md#470)) is that it does not work reliably (cf. https://github.com/camunda/camunda-modeler/issues/1933). 

I'll close this one here since the issue is tracked in the one mentioned above. We are open to contributions that improve the situation, though.

**Closed by pinussilvestrus** 2022-02-10 12:15 UTC
Labels: bug
