### ISSUE TITLE
Mac App misses resources after build

### ISSUE THREAD

**Issue by brain-tec24** [camunda/camunda-modeler#4501] opened 2024-09-04 21:03 UTC
### Describe the bug

When building for windows, the application includes the `resources/element-templates` and `resources/plugins` folder. In contrast those folders are missing, when building for mac. Therefore, it is not possible to include predefined templates in the mac app. Am I missing something or can I somehow fix that by myself?

In general, the files seem to be copied but not included in the app itself. The folder in `/dist` looks the following:
Camunda Modeler.app                     
THIRD_PARTY_NOTICES.camunda-modeler.txt
resources
LICENSE.camunda-modeler.txt             
VERSION

The resources folder contains the other two folders.

### Steps to reproduce

1. npm run build -- --mac
2. Unzip camunda-modeler-5.24.0-mac-arm64.zip
3. Show package content of the Camunda Modeler App
4. The mentioned folders are nowhere

### Expected behavior

Include the mentioned directories in the app itself.

### Environment

When building the application for Mac OS

**Comment by barmac** [comment] 2024-09-17 11:56
Hi,
The way to include custom content on MacOS is via `~/Library/Application Support/...` folder, and not by modifying the application package itself (the .app file). See more at https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/search-paths/#example-macos

I am closing this issue as it's not a bug.

**Closed by barmac** 2024-09-17 11:56 UTC
Labels: bug
