### ISSUE TITLE
Adjust Origin changes label positions & sizes differently than shapes

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#2591] opened 2021-11-26 22:09 UTC
__Describe the Bug__

This issue has been discovered during the dry runs for the upcoming demo of the BPMN Model Interchange Working Group during the OMG Technical Meeting on March 21-25, 2022 in Reston, VA, USA.

Original DI for the start event:

```xml
<bpmndi:BPMNShape bpmnElement="_b1625a52-aaf0-4694-86cb-7af891212ac6" id="Shape__b1625a52-aaf0-4694-86cb-7af891212ac6" color:background-color="#ffffff" color:border-color="#000000">
    <dc:Bounds x="66.9" y="297.35" width="32.03" height="32.03"/>
    <bpmndi:BPMNLabel labelStyle="LabelStyle_0_0" color:color="#000000">
        <dc:Bounds x="28.06" y="338.46" width="109.98" height="30.05"/>
    </bpmndi:BPMNLabel>
</bpmndi:BPMNShape>
```

Start event's DI after changing a task label, i.e. the start event was neither moved nor modified in any other way:

```xml
<bpmndi:BPMNShape id="Shape__b1625a52-aaf0-4694-86cb-7af891212ac6" bpmnElement="_b1625a52-aaf0-4694-86cb-7af891212ac6" color:background-color="#ffffff" color:border-color="#000000">
  <dc:Bounds x="187" y="297" width="32" height="32" />
  <bpmndi:BPMNLabel labelStyle="LabelStyle_0_0" color:color="#000000">
    <dc:Bounds x="160" y="338" width="87" height="27" />
  </bpmndi:BPMNLabel>
</bpmndi:BPMNShape>
```

=> x + 120; label +130; labelwidth -33; labelwidth -3

Complete result file: [4 - Vacation Request Part2- Trisotech-KnowProcess-ARIS-Camunda-just-rename-label.bpmn.txt](https://github.com/camunda/camunda-modeler/files/7610790/4.-.Vacation.Request.Part2-.Trisotech-KnowProcess-ARIS-Camunda-just-rename-label.bpmn.txt)

__Steps to Reproduce__

1. Open the attached BPMN file: [3 - Vacation Request Part2- Trisotech-KnowProcess-ARIS.bpmn.txt](https://github.com/camunda/camunda-modeler/files/7610764/3.-.Vacation.Request.Part2-.Trisotech-KnowProcess-ARIS.bpmn.txt)
2. Change the label of the first task
3. Save the file

__Expected Behavior__

Since the file has no negative DI coordinates it shouldn't need adjustment in the first place. However, if coordinates are being adjusted, all elements and their labels must all be consistently adjusted by the same offset.

__Environment__

 * Version: 4.12.0-nightly.20211125
 * Operating System: Linux x86_64 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform

__Context__

Depends on https://github.com/bpmn-io/bpmn-js/issues/1537

Also reported as https://github.com/camunda/camunda-modeler/issues/2566

**Comment by MaxTru** [comment] 2021-11-27 20:14
Thanks for reporting in such a structured way including example. I can re-produce. However, is this not a duplicate of #2566?

**Comment by falko** [comment] 2021-11-27 23:37
Yes, this is a more detailed analysis of what exactly has happened in #2566. What we still don't understand is why the coordinates were adjusted at all for this model, which doesn't have negative coordinates. If we would understand how it is triggered, we could adjust the source model for the time being and buy ourselves time for the fix of the label handling.

**Comment by falko** [comment] 2021-11-27 23:38
Workaround: start Modeler with `--disable-adjust-origin`

**Comment by MaxTru** [comment] 2021-11-28 07:52
Needs fix via https://github.com/bpmn-io/bpmn-js/issues/1537

**Comment by MaxTru** [comment] 2021-11-28 07:53
Timeline to fix this:
* Camunda Modeler Release required end of February (to be used in March OMG Demo)
  * (Also we will use Camunda Cloud (not Platform))

**Comment by MaxTru** [comment] 2021-11-28 07:54
I am closing #2566 as duplicate since this issue here is more detailled. Added the additional info we already collected to this issue

**Comment by Skaiir** [comment] 2022-02-10 12:29
Fixed upstream in https://github.com/bpmn-io/bpmn-js/pull/1586

**Comment by MaxTru** [comment] 2022-03-18 15:51
Closed via https://github.com/camunda/camunda-modeler/pull/2817

**Closed by MaxTru** 2022-03-18 15:51 UTC
Labels: bug, miwg, fixed upstream
