### ISSUE TITLE
The deployment modal shows up and closes automatically in a blink after saving the diagram for the first time 

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2907] opened 2022-04-08 10:51 UTC
__Describe the Bug__

When the user clicks on the deploy button if the diagram is unsaved it asks for the user to save but after saving the deployment modal is closed automatically and need to be opened up again.

__Steps to Reproduce__

1. Create a new BPMN diagram.
2. Click on the deploy button.
3. It opens to save the diagram and save the diagram.
4. Now we see that the deployment modal is opened and closed in a blink.
5. the user needs to open up the deploy modal again.

__Expected Behavior__

After saving the diagram the user should be re-directed to the deploy modal without the need of clicking the deploy button again.

__Environment__

- OS: [ Windows 10]
- Camunda Modeler Version: [5.0.0]
- Execution Platform: [. Camunda Platform, Camunda Cloud]

https://user-images.githubusercontent.com/85225325/162421657-5930ba68-925a-49c4-a2a0-b62c9bac8851.mp4

**Comment by marstamm** [comment] 2022-04-08 13:06
I can confirm that this is happening. Here is what I found so far:

## Root Cause

- With https://github.com/camunda/camunda-modeler/issues/2762 , we close the Overlay when the active Tab changes
- A Tab change is triggered when we save. This should not happen
- Last time this happened was in https://github.com/camunda/camunda-modeler/issues/2732 and caused by faulty linting callbacks
- When removing linting, no tab change is triggered

I will dig deeper to find out where we can fix it

**Comment by marstamm** [comment] 2022-04-08 13:42
Currently, we always trigger a replace the tab and trigger an `activeTabChanged` event when we lint a tab. At the same time, we have the assumption that `activeTabChanged` is only triggered when we switch to a **different** tab.

I think the best way is to rework the linting state to work similarly to the dirty/unsaved state. See my Proposal below (/cc @philippfromme @nikku @MaxTru)

## Rework Linting State
We already have a pattern for `dirty` and `unsaved` to store additional tab information in an additional Map. As with `dirtyState` and `unsavedState` state, we could have a `lintingState` that get's updated instead of replacing the tab Object.

```
lintingState = {
  tabId: lintingResults,
  ...
}
```

This way, the tab object itself is not touched or replaced and does not trigger an `activeTabChanged` event.

## Alternatives to consider
- Introduce a `navigation` event that triggers when we actually change a tab (e.g. by checking against the ID)
- All components have to use the ID to check if navigation occurred themselves

**Comment by philippfromme** [comment] 2022-04-12 12:19
> * Introduce a `navigation` event that triggers when we actually change a tab (e.g. by checking against the ID)

I was thinking, if we assume that `activeTabChanged` is only fired when a different tab is opened why not compare by tab ID instead? 🤔

**Comment by marstamm** [comment] 2022-04-12 12:24
> I was thinking, if we assume that activeTabChanged is only fired when a different tab is opened why not compare by tab ID instead? thinking

The issue is that we replace the object. So if we don't fire it, components might have an outdated reference and display outdated info. I'm not sure if this is currently an issue, but I would like to avoid having outdated references anywhere. Therefore, we would need 2 events for it

**Comment by marstamm** [comment] 2022-04-12 12:25
Assumption being that we can use this event to propagate the changed tab to components that would not get it via props anyway

**Comment by marstamm** [comment] 2022-04-25 08:42
closed via #2917

**Closed by marstamm** 2022-04-25 08:42 UTC
Labels: bug, needs review
