### ISSUE TITLE
Not allowed method for deploy model

### ISSUE THREAD

**Issue by Bugerman58** [camunda/camunda-modeler#2536] opened 2021-11-01 04:30 UTC
__Describe the Bug__

When i try deployed new model on self hosted Camunda Platform receiving error in the logs block:
```
RESTEASY003650: No resource method found for GET, return 405 with Allow header [ deploy-error ]
```
, and in the access logs on the Camunda Platform:
```
"GET /engine-rest/deployment/create HTTP/1.0" 405 121
```

__Expected Behavior__

Camunda Modeler send request for deploy model via POST method

__Environment__

- OS: macOS 12.0.1
- Camunda Modeler Version: 4.11.1
- Execution Platform: 7.16

**Comment by nikku** [comment] 2021-11-01 07:35
Thanks for opening this bug report. Could you elaborate which version of the self-hosted Camunda Platform you're using? How can I reproduce the issue myself?

**Comment by MaxTru** [comment] 2021-11-01 07:35
Dear @Bugerman58 ,

thanks for reporting.

I cannot re-produce this. To ensure we have the same setting:
* I am running Camunda Platform 7.16.0
![Screenshot_20211101_083303](https://user-images.githubusercontent.com/42800119/139637151-2599722f-19e3-450f-b863-e732b019921b.png)
* I try to deploy a very simple process
![Screenshot_20211101_083345](https://user-images.githubusercontent.com/42800119/139637223-31c84487-3f0e-482f-92f4-8539df55d795.png)
* I deploy via the deploy dialog
![Screenshot_20211101_083412](https://user-images.githubusercontent.com/42800119/139637279-7205ed27-763e-4d92-ad10-313eba45b68a.png)
* The deployment succeeds without issues:
![Screenshot_20211101_083441](https://user-images.githubusercontent.com/42800119/139637328-333e9a02-34a0-430b-b89c-a73ccb96e712.png)


Can you please check what differs in your setup and provide more details?

**Comment by MaxTru** [comment] 2021-11-01 07:35
Ups, @nikku was quicker :-)

**Comment by Bugerman58** [comment] 2021-11-01 09:06
Thanks for fast answer.

I’ve SSL protected instance of Camunda Platform. When I’m deploying model via Camunda Modeler and send request to http endpoint, platform answers that we have to uses HTTPS enpoint and redirects request. And redirect request automacally becomes GET-request which is rejected by Paltform because it accepts POST-requests only.

**Comment by MaxTru** [comment] 2021-11-01 10:31
This is something we currently do not support.

From my understanding this requirement is covered by this feature request: https://github.com/camunda/camunda-modeler/issues/2404. Could you please check whether [#2404](https://github.com/camunda/camunda-modeler/issues/2404) covers your requirement? If that is this case, I would close this bug here.

**Comment by Bugerman58** [comment] 2021-11-01 10:41
Yes, this request #2404 is what I need. Sorry for erroneous report.

**Comment by MaxTru** [comment] 2021-11-01 11:57
> Yes, this request #2404 is what I need. Sorry for erroneous report.

No worries, thanks for confirming. This is helpful, since we know that this is needed from a variety of users.

Closing this as duplicate of #2404

**Closed by MaxTru** 2021-11-01 11:57 UTC
Labels: bug, help wanted
