### ISSUE TITLE
When opening deployed BPMN for C8 via link in operate, version is not selected

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2870] opened 2022-03-30 12:23 UTC
__Describe the Bug__

When opening deployed BPMN for C8 via link in operate, version is not selected

__Steps to Reproduce__

1. Create C8 BPMN
2. Deploy to C8 SaaS
3. Follow link to operate
4. Now this happens =>
![Screenshot_20220330_142100](https://user-images.githubusercontent.com/42800119/160833151-98e64b3a-54f7-4a53-9bb9-cab0b72021df.png)

=> User now needs to manually select  the version from the left side in operate.

__Expected Behavior__

* The instance of the respective deployed version is directly opened
* If there is only 1 version, that version is displayed

__Environment__

Camunda Modeler 5.0.0-alpha.2

**Comment by pinussilvestrus** [comment] 2022-03-31 06:25
Is this maybe a duplicate of https://github.com/camunda/camunda-modeler/issues/2735?

**Closed** 2022-03-31 07:06 UTC
Labels: bug, deploy, Camunda Cloud
