### ISSUE TITLE
Camunda Modeler allows multiple incoming sequence flows for events after an event based gateway

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3984] opened 2023-11-14 14:07 UTC
### Describe the bug

Since Version 5.5.1, the Camunda Modeler breaks the BPMN specification and allows multiple incoming sequence flows to an event that follows an event based gateway:

![grafik](https://github.com/camunda/camunda-modeler/assets/7870843/f15b2b0e-fdf0-4b0d-b0ec-c6bd28acf8f2)

According to the BPMN specification this is not allowed (page 298 Business Process Model and Notation, v2.0):

![grafik](https://github.com/camunda/camunda-modeler/assets/7870843/a21aa161-56e5-4e17-a8e8-40bff168007f)

### Steps to reproduce

Create the model from above in Camunda Modeler 5.4.1 and 5.16.

In 5.4.1, you can not connect the events with an additional sequence flow:

![grafik](https://github.com/camunda/camunda-modeler/assets/7870843/9e2ef757-cc68-4a45-9746-92913cb721e2)

### Expected behavior

It should be impossible to connect both events in the latest version as well.

### Environment

Impossible: 
**Camunda Modeler system information**
 * Version: 5.4.1
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, bpmn-js Token Simulation, Migration, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform 8

Possible:
**Camunda Modeler system information**
 * Version: 5.16.0
 * Operating System: Windows 10 amd64
 * Plugins: bpmn-js Token Simulation, Camunda Property Infos, Tooltip Plugin, Transaction Boundaries, Cloud Connect, Migration
 * Execution Platform: <no active Tab or no execution platform set>

### Additional context

Maybe this issue happens in the BPMN-js library.

**Comment by nikku** [comment] 2023-11-14 16:22
Cannot reproduce in Camunda Modeler v5.17.0: 

![capture WMaKcm_optimized](https://github.com/camunda/camunda-modeler/assets/58601/94b6f821-afe5-4f91-8917-7bc95f1cf3f2)

![capture o6AwzE_optimized](https://github.com/camunda/camunda-modeler/assets/58601/8fa48095-8cfa-446f-b660-f8a8590039ef)

Could you [disable your plug-ins](https://docs.camunda.io/docs/components/modeler/desktop-modeler/flags/#configure-via-cli) to verify these don't interfere?

**Comment by ingorichtsmeier** [comment] 2023-11-14 17:35
It happens in the Web modeler as well. I found it there first.

**Comment by ingorichtsmeier** [comment] 2023-11-14 17:43
In 5.16 without plugins it looks like in your screen movie and works as expected.

What breaks it in web modeler? (version: today). 

Which plugin could influence it? Token simulation is available in both.

**Comment by nikku** [comment] 2023-11-15 07:13
It seems like [token simulation breaks it](https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html?pp=1&diagram=https%3A%2F%2Fraw.githubusercontent.com%2Fbpmn-io%2Fbpmn-js-token-simulation%2Fmaster%2Ftest%2Fspec%2Fbooking.bpmn):

![capture lVY5Xs_optimized](https://github.com/camunda/camunda-modeler/assets/58601/ddf89c51-68d5-4107-acf4-7a22c45e3fbf)

**Comment by marstamm** [comment] 2023-11-21 14:35
I created https://github.com/bpmn-io/bpmn-js-token-simulation/issues/139 in the token simulation repo. As this is not an issue in the desktop modeler itself, I am closing this issue in favor of the plugin issue. 

We can consider opening an issue in the web-modeler for tracking, since we ship it there.

**Closed by marstamm** 2023-11-21 14:35 UTC
Labels: bug, miwg, needs more information
