### ISSUE TITLE
The logs component should not be shared between the tabs.

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2360] opened 2021-07-08 14:47 UTC
__Is your feature request related to a problem? Please describe.__

In the current version the Logs application component is being shared between all the created tabs. But as a user when we open up a new diagram and we already see some logs for it ,it could be sometimes mis-leading to the user.

__Describe the solution you'd like__

Display the logs respective to the diagram where the error occurred and when we create a new diagram the logs should be an empty.

https://user-images.githubusercontent.com/85225325/124942639-19157c80-e00c-11eb-9eca-e89dfe24bed7.mp4

**Comment by andreasgeier** [comment] 2021-07-14 09:31
In the log, we basically have both scopes: file(tab)-related messages but also messages on the app level, for instance, plugin issues.

Making the log view only tab-related would cause the problem of how to communicate tab/file-independent messages.

But we already have (another) concept of how to improve the log view. Currently, the confusion might be caused by having the log view as a panel at the bottom of the tab, similar to the other panel on the right, which is clearly tab-related. In the new concept, the log view will move to an own tab und this might mitigate or even avoid the confusion that you mentioned.

During our work on the [data view](https://github.com/camunda/camunda-modeler-design/issues/25), we might already be able to implement this new approach. So I'll close this issue.

**Closed by andreasgeier** 2021-07-14 09:31 UTC
Labels: enhancement, ux
