### ISSUE TITLE
How to identify the node that will be the base for Alignment?

### ISSUE THREAD

**Issue by rvaneerd** [camunda/camunda-modeler#1056] opened 2018-12-05 12:05 UTC
Hi,

I am aware of the Alignment tools in Camunda Modeler's toolbar.
However, they don't work for me as expected as I cannot seem to figure out which node will be used as the base point (the one that will be used for the alignment of the others) for the alignment.

In other tools (ie. Microsoft Visio), the base node will be identified with a thicker border.
Because of the fact I don't have access to Visio anymore, I cannot provide a screenshot of what I mean.

It would help if this could be implemented in Camunda Modeler as well (as part of the main code or as a plugin).

I've investigated #312 but I cannot figure out to what level that one is related to my request.

I hope the above description is clear enough.

Regards,
Rob.

**Comment by nikku** [comment] 2018-12-06 08:39
Could you provide examples (maybe created using a screen recorder) that illustrate _what_ is not working as expected and what the expected behavior looks like? Depending on whether you file a feature request or bug report, make sure to provide us with all necessary details for the [respective issue type](https://github.com/camunda/camunda-modeler/issues/new/choose).

**Comment by nikku** [comment] 2018-12-06 08:40
> Because of the fact I don't have access to Visio anymore, I cannot provide a screenshot of what I mean.

You could screenshot the Camunda Modeler and "mock" things using Paint. That would help us tremendously to evaluate your issue.

**Comment by nikku** [comment] 2018-12-06 09:55
Is a primary selection indicator the thing you may be missing?

![image](https://user-images.githubusercontent.com/58601/49576419-71141000-f945-11e8-9c4d-63fb847c1d73.png)

**Comment by rvaneerd** [comment] 2018-12-06 11:57
> Is a primary selection indicator the thing you may be missing?
> 
> ![image](https://user-images.githubusercontent.com/58601/49576419-71141000-f945-11e8-9c4d-63fb847c1d73.png)

If in this case, the "choose recipe" is the one that would be the base, then yes, that would do!
If your screenshot would be the result of selecting the "choose recipe" as the first (or last) in the following sample, then that would be exactly what I would like.

![image](https://user-images.githubusercontent.com/4356502/49582772-5eee9d80-f956-11e8-8f42-4b2252737df7.png)

**Comment by nikku** [comment] 2018-12-06 12:40
Thanks for the clarification.

**Comment by nikku** [comment] 2018-12-06 12:57
> How to identify the node that will be the base for Alignment?

Going back to that initial question: Alignment (middle) distinguishes between two scenarios:

* there exists no _common_ line: in this case the elements will be aligned in the middle of the bounding box (vertically or horizontally). The elements won't be aligned to _some particular elements middle_, so to say
* there exists a common line already: That line (horizontally or vertically) will be identified and used. That results in an intuitive alignment experience in most cases.

Both cases are showcased in the following screencast:

![foo](https://user-images.githubusercontent.com/58601/49585186-fc999b00-f95d-11e8-9a6d-c971a73bfc02.gif)

Another more real-world example showcasing the power of that approach in action: 

![foo](https://user-images.githubusercontent.com/58601/49585454-b133bc80-f95e-11e8-9c4a-3eb8eb7e19e6.gif)

I'll close this issue, given that we got no intentions to change that behavior.

**Closed by nikku** 2018-12-06 12:57 UTC
