### ISSUE TITLE
SoapConnector using external freemarker template missing resource attribute

### ISSUE THREAD

**Issue by webcyberrob** [camunda/camunda-modeler#2020] opened 2020-11-13 22:31 UTC
When modelling a service task using the connector approach and an external freemarker template, the ability to define the freemarker resource no longer appears in the properties tab...

Modeller version 4.3.0

**Comment by nikku** [comment] 2020-11-15 15:55
Please use an existing [issue template](https://github.com/camunda/camunda-modeler/issues/new/choose) and provide required context, i.e. screenshots, steps to reproduce. 

We'll otherwise not be able to act on this issue.

**Comment by pinussilvestrus** [comment] 2020-11-15 19:46
This _could_ be a duplicate of https://github.com/camunda/camunda-modeler/issues/2007. @webcyberrob can you verify it?

**Comment by MaxTru** [comment] 2020-11-23 12:43
There was no activity for more than 1 week in this issue. Since we cannot work on this without more information I will close it now.

In case this remains relevant, please do not hesitate to create a new issue using the [issue template](https://github.com/camunda/camunda-modeler/issues/new/choose) and providing more context. Please also consider #2007 (see [pinussilvestrus reply](https://github.com/camunda/camunda-modeler/issues/2020#issuecomment-727625680))

**Closed by MaxTru** 2020-11-23 12:43 UTC
Labels: help wanted
