### ISSUE TITLE
When I color black transition to either color, arrow head disappears

### ISSUE THREAD

**Issue by slizenko** [camunda/camunda-modeler#1400] opened 2019-06-12 13:26 UTC
1. Create diagram Start-Task-End
![image](https://user-images.githubusercontent.com/50139137/59354787-77d57280-8d2e-11e9-8441-3b49ee973cd7.png)
2. Color transitions
![image](https://user-images.githubusercontent.com/50139137/59354853-a18e9980-8d2e-11e9-8d9f-9224d0a4afda.png)
3. Arrow heads disappeared.

__Expected Behavior__
Arrow heads do not disappear.

__Environment__
 - OS: Windows 10, x64
 - Camunda Modeler Version: 3.1.2 x64

**Comment by nikku** [comment] 2019-06-12 13:32
Fixed on master, pending release.

**Comment by nikku** [comment] 2019-06-12 13:32
Cf. https://github.com/camunda/camunda-modeler/commit/eb95b0b5e26e9a44142ab4d9f29014d0d76b0f65.

**Comment by slizenko** [comment] 2019-06-12 13:32
When it will be released?

**Closed by nikku** 2019-06-12 13:32 UTC

**Comment by nikku** [comment] 2019-06-12 13:33
Should be working [in nightly](https://camunda.org/release/camunda-modeler/nightly/).

**Comment by nikku** [comment] 2019-06-12 13:39
Duplicate of https://github.com/camunda/camunda-modeler/issues/1342.
