### ISSUE TITLE
Look into data rejected by ET Elasticsearch due to changed type

### ISSUE THREAD

**Issue by btepe** [camunda/camunda-modeler#2078] opened 2021-01-25 13:34 UTC
__What should we do?__

We have received emails this morning from Google error reporting that the ET production Elasticsearch has rejected some modeler error data, specifically the `json.message.product.internals.deployment.error` field that contained a `string` instead of a `long`.

The reason behind this is that elasticsearch is trained every morning depending on which data comes in first on this day. Today this happens to be the value `20` of type `long`. So today, only values of this type are going to be accepted by elasticsearch for this specific field. Tomorrow, this could change back to a string if the first value that Elasticsearch receives is of type `string` again.

Since you have sent a `string` (mostly `DIAGRAM_PARSE_ERROR`) for this field for 498 of the last 500 records, we want to make you aware of this and suggest you look into whether or not there is anything that needs to be changed in the way the errors are sent to ET.

Here is a link to the [ET production Kiban](https://ui.telemetry.camunda.cloud/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-01-10T02:10:00.000Z',to:'2021-01-25T02:20:00.000Z'))&_a=(columns:!(json.message.product.internals.deployment.error),filters:!(),index:b964e2e0-54e6-11eb-9868-29929da2e48e,interval:auto,query:(language:kuery,query:'json.message.product.internals.deployment.error:%20*%20'),sort:!())) where you can check out what these error messages have looked like in the past weeks up until this morning.

/cc @casulond (Thanks for pointing this out and helping to analyze it!) and @dlavrenuek (Our new/current medic, could you have an eye on this as well?)

__Why should we do it?__

The data that is rejected by Elasticsearch will not show up in Kibana to be analyzed by you and might distort your analysis of the usage data.

**Comment by nikku** [comment] 2021-01-25 13:46
We'll trace back the root cause of this type instability. 

As I understand, it is not possible for you to accept varying types, i.e. `string` and `long` for a specific field?

**Comment by btepe** [comment] 2021-01-25 13:50
Thank you @nikku for looking into it!
You are right, at the moment, we do not accept varying types. But if this is a problem for you longterm, we could look into the possibility of changing this behaviour.

**Comment by nikku** [comment] 2021-01-25 14:01
We'll report back to you. Thanks for opening this issue.

**Comment by casulond** [comment] 2021-01-25 14:56
CC @quentinleroy (just a heads-up, no action required)

**Comment by MaxTru** [comment] 2021-01-25 22:42
Thanks for highlighting and the first analysis. I looked into it from Modeler perspective and so far only have a status update (and no fix yet unfortunately) :

* This behavior was introduced with the 4.5.0 release (12th January). 
* In particular this commit and line of code is relevant: [f52063c](https://github.com/camunda/camunda-modeler/commit/f52063c82a519bc7ab2dd302bf06ec189073bbf7#diff-298625d31e25ea0bf7411d6e45c7ca41ddc98c496e64f91de88bba161b30c233R74). Note that we track `error.code`
  * Note that we introduced the tracking of data in the context of deployments here. So we did not change / introduce a bug into existing behavior, but this tracking was buggy (or at least based on buggy data) from the beginning.
* As @btepe explained, the "weird" thing is that sometimes an error `20` is sent, while mostly a String (`DIAGRAM_PARSE_ERROR`, `FORBIDDEN`, ...) is sent. 
  * First potential approach / point to discuss: one could argue, that an error code `20` is valid (yet we need to find what it means ;-) ). In this case, we might just ensure to stringify it / or E.T. might make sure to allow both types (as @btepe said)
* The `error.code` is extracted from the `deployment.error` event, which is fired by the [DeploymentTool](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js#L205)
  * The DeploymentTool in the concerned cases (implicitly) expects a [DeploymentError](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/camunda-plugin/shared/CamundaAPI.js#L258). However, looking at it, one will find that a real DeploymentError object will always set `error.code` to some string.
    * Ergo => IMO we should aim for fixing the errorHandling [in the DeploymentTool](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js#L141). Currently we assume that all errors thrown, are deployment errors, but in fact they could come from e.g., `saveProcessDefinition`

I will sync with the team about this direction for the solution and follow-up.

**Comment by casulond** [comment] 2021-01-26 08:23
Just to confirm our hypothesis about the impact of this issue: today indexing works again after a new index was created automatically that first saw a string value. (Actually, `deployment.error` values were indexed since yesterday evening around `17:27:27` when the index was rolled over and a new index started detecting field types again.)

**Comment by casulond** [comment] 2021-01-26 08:49
The different data type in that index affects how that field can be analyzed in Kibana. We will take care of that aspect in https://github.com/camunda/et/issues/251

**Comment by MaxTru** [comment] 2021-01-27 15:39
Quick update: we discussed and decided to improve the errorHandling in [DeploymentTool](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js#L141). (See [reasoning ](https://github.com/camunda/camunda-modeler/issues/2078#issuecomment-767160899)). This would be release then next month (09.02.) and we should then
* only send strings to ET
* send other errors properly to our sentry

I will follow-up with a PR, but leave this issue open to track overall progress :+1:

**Comment by nikku** [comment] 2021-01-28 17:13
Closed via https://github.com/camunda/camunda-modeler/pull/2080.

Related fix https://github.com/camunda/camunda-modeler/pull/2081.

**Closed by nikku** 2021-01-28 17:13 UTC
Labels: ET, in progress
