### ISSUE TITLE
Resize label annotations 

### ISSUE THREAD

**Issue by IvanAgafonov** [camunda/camunda-modeler#3007] opened 2022-06-27 10:10 UTC
### Problem you would like to solve

How can i resize labels on sequence flow bpmn? If i do it in xml, text just centralized, the size is the same, and still have wrapes to new lines \n. I use Camunda Modeler 5.0.0

![image](https://user-images.githubusercontent.com/29808839/175916069-e63a9264-3dd9-477d-8d15-d4e97673aaaa.png)
![image](https://user-images.githubusercontent.com/29808839/175916235-43e82b34-4600-4de1-8199-324ab6742719.png)
![image](https://user-images.githubusercontent.com/29808839/175916257-cc139e3a-8f54-49c5-814f-fb7397f2b29f.png)

### Proposed solution

Fix logic in Camunda Modeler

### Alternatives considered

Fix structure of xml bpmn

**Comment by smbea** [comment] 2022-06-28 08:11
Duplicate of https://github.com/bpmn-io/bpmn-js/issues/1513

**Closed by smbea** 2022-06-28 08:11 UTC
Labels: enhancement
