### ISSUE TITLE
DecisionId not editable via PropertyPanel

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-modeler#1774] opened 2020-04-16 13:55 UTC
__Describe the Bug__

When creating a new DMN it is not possible to change the Decision ID in the Property Panel, an exception is thrown. Afterwards no changes are possible also not in the DecisionId field within the DMN table...

__Steps to Reproduce__

1. File --> New... --> DMN Table
2. Change the ID in Property Panel
3. [diagram_1.dmn] Cannot use 'in' operator to search for 'id' in undefined
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/7.7.js:8:187829
    at oldProperties (webpack:///node_modules/dmn-js-shared/lib/features/modeling/behavior/IdChangeBehavior.js:69:25)
    at shouldSkipUpdate (webpack:///node_modules/dmn-js-shared/lib/features/modeling/behavior/IdChangeBehavior.js:50:15)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/1.1.js:1:50614
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:365:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:350:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:311:23)
    at fire (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:346:28)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/1.1.js:1:90220
    at fn (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:367:4) [ error ]

__Expected Behavior__

Editing is able in both places the DMN table and the Property Panel

__Environment__

- OS: MacOS, also Windows
- Camunda Modeler Version:3.7.2

**Comment by nikku** [comment] 2020-04-16 15:58
Duplicate of https://github.com/camunda/camunda-modeler/issues/1769, right?

**Comment by McAlm** [comment] 2020-04-16 16:47
Korrekt!
Ich schließe es als Duplicate!
Beste Grüße, Stefan

Sent from my mobile phone, please excuse typos and briefness.

**Closed** 2020-04-16 18:22 UTC
Labels: bug, duplicate
