### ISSUE TITLE
DMN Properties Panel: Input blurred on commandStack.changed

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1100] opened 2019-01-15 13:32 UTC
![2019-01-15_14-30-45](https://user-images.githubusercontent.com/7633572/51183659-300f0400-18d2-11e9-8b95-e8aaa062f9ee.gif)

# Reproduce

1. Open DMN tab
2. Edit property through properties panel

# Expected Behavior

1. Input stays focussed

# Actual Behavior

1. Input is blurred

**Comment by pinussilvestrus** [comment] 2019-01-16 12:22
Seems to be caused by reattaching the properties panel on every view changed event: https://github.com/camunda/camunda-modeler/blob/next/client/src/app/tabs/dmn/DmnEditor.js#L214

**Comment by barmac** [comment] 2019-01-16 14:48
Closed via https://github.com/camunda/camunda-modeler/pull/1113

**Closed by barmac** 2019-01-16 14:48 UTC
Labels: bug, needs review
