### ISSUE TITLE
Cannot build/run the modeler

### ISSUE THREAD

**Issue by matteopantano** [camunda/camunda-modeler#2023] opened 2020-11-27 07:37 UTC
__Describe the Bug__

I cannot start the camuda-modeler. I get the following error: 

>camunda-modeler-builder@0.0.0 app:dev /home/modeler
> electron ./app/dev.js --force-update-checks resources/diagram/simple.bpmn
[134:1127/072806.341331:FATAL:atom_main_delegate.cc(211)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> camunda-modeler-client@4.4.0 dev /home/modeler/client
> run-s start
> camunda-modeler-client@4.4.0 start /home/modeler/client
> cross-env NODE_ENV=development webpack-dev-server --config ./webpack.config.js --port 3000
sh: 1: cross-env: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn

__Steps to Reproduce__

In order to reproduce, download the release 4.4.0 as a zip and unpack it then run the attached docker file [Dockerfile.txt](https://github.com/camunda/camunda-modeler/files/5606550/Dockerfile.txt) from inside the folder

Then run the container with: `docker run --network=host -it imagename` . Switch to posix enabled terminal `bash --posix` and go in the /modeler folder. Run `npm install` and then `npm start`, you will see the error

__Expected Behavior__
The system should start

__Environment__

- OS: ubuntu:bionic
- Camunda Modeler Version: 4.4.0

**Comment by matteopantano** [comment] 2020-11-27 08:15
So, I was able at least to start the program by going inside the /client folder and perform an `npm install` there. Now, from the /modeler folder if I run `npm start` it works. However, I see just a blank page 
![camuda](https://user-images.githubusercontent.com/26014548/100426426-1b385580-3091-11eb-9d58-158cf61b1b55.png)

**Comment by nikku** [comment] 2020-11-27 11:57
Could you verify the following:

* You are attempting to run the Camunda Modeler development setup from within Docker
* :arrow_forward: That does not work.

**Comment by nikku** [comment] 2020-11-27 12:00
The issue is likely that you run the whole thing as `root` within the docker container, which apparently is not supported:

```
[134:1127/072806.341331:FATAL:atom_main_delegate.cc(211)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
camunda-modeler-client@4.4.0 dev /home/modeler/client
run-s start
camunda-modeler-client@4.4.0 start /home/modeler/client
cross-env NODE_ENV=development webpack-dev-server --config ./webpack.config.js --port 3000
```

As a general best practice working with docker containers, setup a non root user and try to continue from there.

**Comment by matteopantano** [comment] 2020-11-27 14:15
For me it is a requirement to get it running in a docker container. I was already able to dockerize the bpmnjs so this should be just a step-further. Your suggestion would be to for a non-root user?

**Comment by nikku** [comment] 2020-11-27 16:25
The error message is fairly clear about that. I'd suggest you to try it out and report back, yes.

**Comment by matteopantano** [comment] 2020-11-28 11:50
So, I was able to get it running after some time. The sample docker is the following: [DockerfileTest.txt](https://github.com/camunda/camunda-modeler/files/5610524/DockerfileTest.txt).

In order to run it you must do: `docker run --rm --network=host --privileged -e DISPLAY=$DISPLAY -it YOURIMAGE`

However, once inside I encounter the issue that I need to run `npm start` twice. The first one seems is "warming up" everything (I need to wait for output of webpack). The second one, then shows camuda working.

Any help? Why I need to run `npm start `twice? This is not useful if I need to create my final docker app.

**Comment by nikku** [comment] 2020-11-28 19:24
Happy that you got the basics running and shared your solution. It is great how far you got. 

To clarify though we cannot support you in running the development setup of the App inside docker. We do in no way recommend that, too. There is many things wrong about it, including (but not limited to) poor performance and pain to set it up (you experienced it). 

I'll close this issue as you were able to get things running.

> However, once inside I encounter the issue that I need to run npm start twice. The first one seems is "warming up" everything (I need to wait for output of webpack). The second one, then shows camuda working.

This is expected behavior, with or without docker. You'll initially see an empty page and have to `CMD/CTRL + R` in order to refresh the app once the initial webpack bundle completed.

**Closed by nikku** 2020-11-28 19:24 UTC
Labels: bug, help wanted

**Comment by gliptak** [comment] 2024-06-25 18:48
there is now https://hub.docker.com/r/camunda/web-modeler-webapp
