### ISSUE TITLE
Posibility to add custom font style to each element individually 

### ISSUE THREAD

**Issue by DevAutomationInf** [camunda/camunda-modeler#4730] opened 2024-11-27 08:27 UTC
### Problem you would like to solve

It is not possible to add a custom font size to an individual element in the diagram for embedded labels ( such as tasks, lanes, and subprocesses).

### Proposed solution

It should be possible to apply a custom font style inside the custom renderer to embedded labels, as it is possible for external labels.

### Alternatives considered

I considered overriding the renderEmbeddedLabel function inside the BPMNRenderer, but that is not allowed when using typescript.

### Additional context

In this [stackblitz](https://stackblitz.com/~/github.com/DevAutomationInf/custom-font) example, I demonstrate how the **external label** font size can be changed for each element individually. However, if this property is added to the **embed label**, only the stroke takes effect. `{labelStyle: {fontSize: '40', stroke: 'blue'}}`. The cause is that the renderEmbeddedLabel doesn't take other style into consideration. I tried overriding this method but it was not possible when using typescript.

**Comment by barmac** [comment] 2024-12-02 10:43
Hi,
Thanks for opening the issue. This is a duplicate of https://github.com/camunda/camunda-modeler/issues/1026, so I will close it though. Let's keep the discussion in the original issue.

**Closed by barmac** 2024-12-02 10:43 UTC
Labels: enhancement

**Comment by barmac** [comment] 2024-12-02 10:44
The issue description looks a bit like a request for additional API in bpmn-js, but for that we open issues in https://github.com/bpmn-io/bpmn-js. This repo is for Desktop Modeler.

**Comment by DevAutomationInf** [comment] 2024-12-02 12:06
Thank you for your reply. In that case I will open it there.

**Comment by DevAutomationInf** [comment] 2024-12-04 13:51
In the case of embedded labels, they are part of the functions that render the tasks, lanes etc. Having a custom label would mean having all these elements as custom and this is not a path I would like to go. Unless there is something and there is a different solution.
