### ISSUE TITLE
Can attach link catch events to a task by copy-pasting

### ISSUE THREAD

**Issue by hkupitz** [camunda/camunda-modeler#3967] opened 2023-11-07 18:37 UTC
### Describe the bug

It is possible to attach a link event to a task by copy-pasting it, effectively making it a boundary event which is not allowed according to the BPMN specification.

![image](https://github.com/camunda/camunda-modeler/assets/27265759/6cf8782e-e643-47f8-8dab-0c5c994ae03c)

![Modeler_Link_Boundary](https://github.com/camunda/camunda-modeler/assets/27265759/cbbb3e56-416c-4ca8-97e0-dc96e5e0aabc)

Afterwards it becomes intertwined with the task and can only be detached by using the arrow keys.

### Steps to reproduce

1. Place a task on the canvas.
2. Place an intermediate event on the canvas.
3. Make it a link intermediate catch event.
4. Copy it.
5. Paste it.
6. Attach it to the task.

### Expected behavior

Link events should not be able to be attached to a task at all.

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.16.0

### Additional context

This does not work with `bpmn-js@15.1.13`, so it seems to be caused by something Modeler-specific.

**Comment by marstamm** [comment] 2023-11-21 14:23
I can reproduce this. Root cause is the rules for attach rules in camunda-bpmn-js, where we do not consider the spec:
https://github.com/camunda/camunda-bpmn-js/blob/847d4345b6380920c5d9e1fe510ffd50350ba70c/lib/camunda-cloud/features/rules/BpmnRules.js#L87-L90

Moving to ready

**Comment by philippfromme** [comment] 2023-11-28 20:40
I found the original issue that led to the introduction of the current behavior: https://github.com/zeebe-io/zeebe-modeler/issues/31. In the meantime the rules in bpmn-js have been adjusted as well (https://github.com/bpmn-io/bpmn-js/pull/1041) to allow attaching intermediate catch events and replacing them with boundary events, so there is some duplication here. I think we should remove the custom attach rule from camunda-bpmn-js and adjust the rule in bpmn-js to allow attaching both intermediate catch and throw events.

**Comment by nikku** [comment] 2023-11-29 13:00
Fixed upstream via https://github.com/camunda/camunda-bpmn-js/pull/325.

**Closed** 2023-12-05 14:55 UTC
Labels: bug, needs review
