### ISSUE TITLE
Unable to export to PNG file, the file created is reported as too big or not readable

### ISSUE THREAD

**Issue by Ditli** [camunda/camunda-modeler#1407] opened 2019-06-14 08:16 UTC
The file saved a PNG cannot be opened in IRFANview or paint
Error says that the file is not a valid Bitmapfile or the format is not supported.
My colleagu is using Camunda and exporting files without any problem: I did compare the characteristics of the file and realised that my colleague's file have a dimension in it, mine have none
I don't see a way to infuence the file format so that I can open it

thanks for your help
Regards
Edth Gabsa

**Comment by nikku** [comment] 2019-06-14 08:20
Try to reproduce whether this is a general problem on your machine (affecting all diagrams) or only a particular diagram.

If it is only a problem with a particular diagram, share the diagram with us or we won't be able to help you.

**Comment by nikku** [comment] 2019-06-14 08:21
Please update your issue to include the relevant [bug report information](https://github.com/camunda/camunda-modeler/issues/new?template=BUG_REPORT.md).

**Comment by Ditli** [comment] 2019-06-14 11:42
Thanks for the quick feedback
now I will be able to upload the files

1. this happens only on my machine, affecting all diagrams,
the same diagram can be exported by my colleague correctly

2. press the button export as a picture
I have added as file, the bpmn file, followed by a displayable PNG file
created by my colleague on his computer, and a no displayable PNG file
created from my computer

thanks in advance
best regards
Edith


Am Fr., 14. Juni 2019 um 10:20 Uhr schrieb Nico Rehwaldt <
notifications@github.com>:

**Comment by nikku** [comment] 2019-06-14 13:29
Please update the issue and provide all necessary details (cf. [my previous comment](https://github.com/camunda/camunda-modeler/issues/1407#issuecomment-502017061)).

**Comment by nikku** [comment] 2019-06-24 07:37
Closing this due to missing information.

**Closed** 2019-06-24 07:37 UTC
Labels: help wanted
