### ISSUE TITLE
Properties panel resize handle disappears after collapse

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1330] opened 2019-03-25 08:21 UTC
__Describe the Bug__

The resize handle of the collapsed properties panel is missing in the decision table view

__Steps to Reproduce__

// given
Open decision table view

// when
I collapse the properties panel

// then
the resize handle is missing and I cannot expand the properties panel by mouse

__Expected Behavior__

Resize handle is available

**Comment by nikku** [comment] 2019-03-25 08:56
This is the intended behavior: https://github.com/camunda/camunda-modeler/issues/1114.

However, due to the amount of times we get feedback on this, we will consider to somehow bring it back.

Closing this issue as a duplicate.

**Closed by nikku** 2019-03-25 08:56 UTC
Labels: DMN, bug, duplicate

**Comment by philippfromme** [comment] 2019-03-25 08:57
+1 for bringing it back for the sake of consistency.
