### ISSUE TITLE
get plugin directory

### ISSUE THREAD

**Issue by tayfuncelik** [camunda/camunda-modeler#4222] opened 2024-03-28 14:12 UTC
### Problem you would like to solve

getPluginsDirectory method is not working because it is deprecated . how can we get plugin directory ?

var img = document.createElement('img');
img.src = getPluginsDirectory() + '/camunda-modeler-plugin-example/logo.png';

### Proposed solution

non

### Alternatives considered

none

**Comment by philippfromme** [comment] 2024-04-03 08:15
Closed as duplicate of https://github.com/camunda/camunda-modeler/issues/4223.

**Closed by philippfromme** 2024-04-03 08:15 UTC
Labels: enhancement
