### ISSUE TITLE
Modeler does not close when restarting Mac OS

### ISSUE THREAD

**Issue by volkergersabeck** [camunda/camunda-modeler#2230] opened 2021-04-27 09:35 UTC
__Describe the Bug__

When I try to restart my Mac, Camunda Modeler does not act on the "quit" signal and I have to manually quit the app such that the restart can proceed.

__Steps to Reproduce__

1. Trigger a restart of Mac OS (I'm on 11.2.3)
2. Wait for all apps to close and Mac OS to shutdown
3. Camunda Modeler will not be closed

__Expected Behavior__

Mac OS can restart without me closing Camunda Modeler manually

__Environment__

- OS: MacOS 11.2.3
- Camunda Modeler Version: 4.7.0

**Comment by pinussilvestrus** [comment] 2021-04-27 09:55
That's an issue for a while now: https://github.com/camunda/camunda-modeler/issues/1803... And seems to be no quick-fix.

**Comment by nikku** [comment] 2021-04-27 13:14
Closing as a duplicate of https://github.com/camunda/camunda-modeler/issues/1803.

**Closed by nikku** 2021-04-27 13:14 UTC
Labels: bug
