### ISSUE TITLE
Multiple tooltips at once show for FEEL expressions 

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4117] opened 2024-02-07 14:51 UTC
### Describe the bug

I have listed down a few issues related to FEEL pop up editor and FEEL expression tooltip

### Steps to reproduce

1. In the form editor, form output panel: two tooltips overlapping on each other in the Form output panel
    
  https://github.com/camunda/camunda-modeler/assets/85225325/0aec01ce-6fee-4612-bce9-31c6fbdb4fed

2. In the form editor, form input panel: tooltip error shows just on empty state msg and once the output panel is completely emptied along with the default braces throws error where we could not add any input to the output panel to overcome the same
    
  https://github.com/camunda/camunda-modeler/assets/85225325/aefd3008-6039-4f3b-8238-d28b1c224c4a

### Expected behavior

The above UI issue with regards to the tooltips should be resolved

### Environment

- OS: [Windows 10]
- Camunda Modeler Version: [5.20.0]
- Execution Platform: [ Camunda 8]
- Installed plug-ins: [...]

**Comment by nikku** [comment] 2024-02-07 15:12
@GeethaParthasarathy I believe the initial bits of what you supported are related / similar to https://github.com/camunda/camunda-modeler/issues/4106?

**Comment by nikku** [comment] 2024-02-07 15:19
Updated the issue as we have the scrolling aspect captured elsewhere. Please review.

**Comment by nikku** [comment] 2024-02-23 21:20
@vsgoulart Please tag + close accordingly via a dependency upgrade.

**Comment by vsgoulart** [comment] 2024-04-05 18:57
@GeethaParthasarathy  This should be fixed now with the `1.8.3` release of `form-js`. Please reopen if the issue is still there.

**Closed by vsgoulart** 2024-04-05 18:57 UTC
Labels: bug, backlog, Forms
