### ISSUE TITLE
Support templating of `messageEventDefinition` and related message global events for Camunda 8

### ISSUE THREAD

**Issue by chillleader** [camunda/camunda-modeler#3403] opened 2023-01-20 09:41 UTC
### Problem you would like to solve

As a Connectors developer, I would like to be able to template Inbound Connectors as Message Intermediate Catch Events. Currently templating is not supported for message event definitions.

### Proposed solution

- Make it possible to template the configuration of `messageEventDefinitions` in `MessageIntermediateCatchEvent` (and, optionally, also `ReceiveTask` for a seamless UX), so that the user is able to configure message event definition even when a template is applied.
- Allow to configure the global `Message` elements from the properties panel of a templated element.

Requirements:

* [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/890
* [ ] #3573
* [x] [Support message templates in JSON schema](https://github.com/bpmn-io/element-templates-validator/pull/18)
* [ ] https://github.com/camunda/camunda-modeler/issues/3537

Optional:

* https://github.com/bpmn-io/bpmn-js/issues/1872

### Alternatives considered

Make the `Message` property group visible alongside with the Connector properties in the properties panel (as if the `entriesVisible` flag was enabled, but only for `Message` properties.

This would also be a suitable solution, although it would not fully fit into the current templating experience, where everything is defined via templated properties.

### Additional context

Part of the epic: https://github.com/camunda/product-hub/issues/817

Related discussion: [Slack](https://camunda.slack.com/archives/C0350959WG1/p1674124033687259)

**Comment by nikku** [comment] 2023-01-20 10:02
@chillleader Could you share a concrete example what you would like to template? What is a configured diagram (showcasing mappings and additional configuration) that supports this topic?

**Comment by chillleader** [comment] 2023-01-20 10:51
Consider the following example: an element template is applied to an Intermediate Catch Event.

I would like to template a group of inputs very similar to the default Message properties group, where the user can create a global message reference and link it to the Event, i.e. the following fields in the property panel:
- Reference to the global message definition (`<bpmn:messageEventDefinition>` for Catch Events or `messageRef` property for Receive Tasks)
- 2 fields that are mapped directly to the message definition selected in the previous field:
  - Message name
  - Subscription correlation key

Visually I can imagine that it looks like this: 

<img width="1089" alt="Screenshot 2023-01-20 at 11 30 42" src="https://user-images.githubusercontent.com/38818382/213674074-eb49e735-de75-42fc-adae-fb31eccd7eee.png">

Please find the diagram from the screenshot below alongside with the used element template.
[webhook_example.zip](https://github.com/camunda/camunda-modeler/files/10465562/webhook_example.zip)

**Comment by chillleader** [comment] 2023-01-20 12:07
> would be exposing the correlation key enough?

Yes, from the functional perspective it should be enough.
Maybe it makes sense to allow hiding the name input in template, but still support it?

**Comment by nikku** [comment] 2023-01-23 13:14
Moving to `ready` for discussion within the team. It will be a little bit of effort for us to implement it.

**Comment by barmac** [comment] 2023-02-14 16:56
I had an initial look at this and I believe we could re-use the C7 concept of `scopes` here. The template could look then like this:

```json
{
 "$schema": "https://unpkg.com/browse/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "asd",
  "id": "asd",
  "appliesTo": [
    "bpmn:IntermediateCatchEvent",
    "bpmn:IntermediateThrowEvent"
  ],
  "elementType": {
    "value": "bpmn:IntermediateCatchEvent",
    "eventDefinition": "bpmn:MessageEventDefinition"
  },
  "properties": [],
  "scopes": [
    {
      "type": "bpmn:Message",
      "properties": [
        {
          "type": "Hidden",
          "value": "hiddenName",
          "binding": {
            "type": "property",
            "name": "name"
          }
        },
        {
          "type": "Hidden",
          "value": "=myCorrelationKeyVariable",
          "binding": {
            "type": "zeebe:subscription",
            "name": "correlationKey"
          }
        }

      ]
    }
  ]
}
```

Only a single message should be allowed. 

Ideally, the created message should not be available for other elements.

WDYT?

**Comment by barmac** [comment] 2023-02-16 08:43
After some discussion with @nikku and @philippfromme, I will try out an alternative approach. Instead of reintroducing `scopes`, we will use `zeebe:input` binding to map given input to a correlation key. Message name should also be configurable via properties.

**Comment by barmac** [comment] 2023-02-16 10:51
My current experiment is to reuse input binding with some special variables like so:

```json

{
 "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema@0.7.0/resources/schema.json",
  "name": "Message Event Template",
  "id": "messageEventTemplate",
  "appliesTo": [
    "bpmn:IntermediateCatchEvent",
    "bpmn:IntermediateThrowEvent"
  ],
  "elementType": {
    "value": "bpmn:IntermediateCatchEvent",
    "eventDefinition": "bpmn:MessageEventDefinition"
  },
  "properties": [
    {
      "type": "Hidden",
      "value": "hiddenName",
      "binding": {
        "type": "zeebe:input",
        "name": "messageName"
      }
    },
    {
      "type": "Hidden",
      "value": "=myCorrelationKeyVariable",
      "binding": {
        "type": "zeebe:input",
        "name": "correlationKey"
      }
    }
  ]
}
```

`messageName` and `correlationKey` will be internally reused as `bpmn:Message#name` and `zeebe:subscription#correlationKey`.

**Comment by barmac** [comment] 2023-02-17 08:19
The contract is:

> Given I typed `"eventDefinition": "bpmn:MessageEventDefinition"`, I have to add two `zeebe:input` properties:
* with `"name": "correlationKey"`
* with `"name": "messageName"`

This allows me to use other inputs as well, but you have to include these two properties.

**Comment by barmac** [comment] 2023-02-17 08:21
I have a working prototype solution for create mode, but you still cannot apply a template to an existing element.

**Comment by nikku** [comment] 2023-02-17 08:25
Keep in mind that the contract will be different on start events (where no `correlationKey` is supported, but assumed implicitly).

**Comment by barmac** [comment] 2023-02-27 15:25
@chillleader @bastiankoerber @nikku 
I've created a prototypical solution which presents how we could configure messages via `zeebe:input` properties. The template expects that you pass variables called `messageName` and `correlationKey` to the event. Check out the prototype at https://message-templates.netlify.app/

What it supports:
* Create a message template by defining `elementType#eventDefinition='messageEventDefinition'`.
* Use `zeebe:input` properties to configure the message. 

Not included (yet):
* Template validation regarding the required properties.
* Exclude templated message from non-template event available messages list.

The BPMN files created via this editor are deployable to Zeebe so you can already see them in action too.
Please let me know how this solution feels and whether it allows to template what you need.

**Comment by chillleader** [comment] 2023-02-28 10:20
Thanks @barmac! This looks great already, and overall I think it would solve our problem 👍 

I just have one question: I noticed that in the example template it is possible to configure `messageName` as a FEEL expression. Would this behaviour be valid? Please correct me if I'm wrong, I was previously under the impression that message names are static (unlike correlation keys).

Finally, just for our planning purposes, do you think this solution may be ready by our next release on March 14? (it's also perfectly fine for us if it takes more time).

**Comment by barmac** [comment] 2023-02-28 15:59
For intermediate message events, the message name can be evaluated.

However, I've tested if we can reuse the same idea for message start events, and even if we provide a static message name via `zeebe:input`, the deployment is rejected. This can be confirmed with the following BPMN:
[test.bpmn.txt](https://github.com/camunda/camunda-modeler/files/10852286/test.bpmn.txt)

So this means we will probably need to rethink the solution, as it will eventually need to be different once we do the start events.

> Finally, just for our planning purposes, do you think this solution may be ready by our next release on March 14? (it's also perfectly fine for us if it takes more time).

I can't promise anything but this is my priority at the moment.

**Comment by barmac** [comment] 2023-03-01 11:46
I prepared a couple of potential solutions which should work for both intermediate and start events. You can check them out at https://miro.com/app/board/uXjVPn-slXA=/?moveToWidget=3458764547583168187&cot=14 Which one feels the easiest to grasp from a template creator perspective?

**Comment by barmac** [comment] 2023-03-15 12:51
I've added requirements to the issue.

**Comment by barmac** [comment] 2023-03-22 09:31
After today's discussion with @nikku, I decided to try out the following template structure:

```json
{
  "name": "Message Template",
  "id": "com.camunda.example.MessageTemplate",
  "appliesTo": [
    "bpmn:IntermediateCatchEvent"
  ],
  "elementType": {
    "value": "bpmn:IntermediateCatchEvent",
    "eventDefinition": "bpmn:MessageEventDefinition"
  },
  "properties": [
      {
        "label": "Message name",
        "type": "String",
        "generatedValue": "uuid",
        "editable": false,
        "binding": {
          "type": "bpmn:Message#property",
          "name": "name"
        }
      },
      {
        "label": "Correlation Key",
        "type": "String",
        "feel": true,
        "binding": {
          "type": "bpmn:Message#zeebe:subscription#property",
          "name": "correlationKey"
        }
      }
  ]
}
```

What's new:
1. You can choose between `value` and `generatedValue` for your property. In case of the latter, the app will generate a default value according to the given scheme (`uuid` as the only scheme supported initially, but it could be `timestamp` or anything else in the future).
2. `#` as the symbol for nested elements; we also explicitly state that a `zeebe:subscription#property` is modified. This can be reused for `zeebe:taskDefinition`.

**Comment by barmac** [comment] 2023-03-31 13:02
Based on the example above, I built a prototype which you can try out at https://6426d974811c6b217272b9d4--message-templates.netlify.app/
It does not support generated value yet, but it's coming soon.

@chillleader @nikku I am looking forward to your feedback.

**Comment by nikku** [comment] 2023-04-03 08:41
@barmac I found one issue, related to https://github.com/camunda/camunda-modeler/issues/3537.

If I replace the intermediate (or start event) with another message definition I assume that the template is unbound, but it is not:

![capture KKMFvW_optimized](https://user-images.githubusercontent.com/58601/229450734-7c1ed2aa-61e0-4d87-be2d-8ba265d59ae5.gif)

**Comment by barmac** [comment] 2023-04-03 08:47
Thanks for pointing this out. I will add a fix for this to the requirements.

**Comment by chillleader** [comment] 2023-04-04 09:21
@barmac The prototype looks great, thank you!
One thing I noticed upon inspecting the resulting BPMN XML is that the actual message is not present.
i.e. if I use the message element template and configure `messageName = testMsg` - I expect that the resulting diagram contains the `<bpmn:message id="Message_1iin4sv" name="testMsg">` element, but in fact, it's not there. Is it a missing part in the prototype?

**Comment by barmac** [comment] 2023-04-04 09:38
Thanks for sharing. It looks like a bug; the message should be created.

**Comment by barmac** [comment] 2023-04-04 09:50
I've already fixed this via https://github.com/bpmn-io/bpmn-js/commit/54bfb00ec699b7958d4c5c69ac1f55765b0d05f5 but for some reason the prototype does not include the fix.

**Comment by barmac** [comment] 2023-04-14 14:58
I've updated the prototype so that you can try out the latest state. Currently, the only missing feature is copy&paste support. Check out the list for summary: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/890

Link to prototype: https://643968d4456c960ff4080aaf--message-templates.netlify.app/

**Comment by nikku** [comment] 2023-04-17 06:44
Looks promising. One thing I found is that the template message seems to stay around when I replace with a stock message event. Is this what we want to go with?

![capture y7Iig5_optimized](https://user-images.githubusercontent.com/58601/232405142-14163c45-842a-40f6-b92f-30e0f98df808.gif)

**Comment by barmac** [comment] 2023-04-17 07:03
> One thing I found is that the template message seems to stay around when I replace with a stock message event. Is this what we want to go with?

This is to mimic the already existing pattern of "replace with stock element = unlink the template". So we unlink the template from a message but keep the properties. Should we remove the message completely?

I noticed that if I apply a template to an event which already has a reference to a message, the message is reused while my intuition is that the reference should be removed first. Otherwise, the message will be broken for elements which shared that message.

**Comment by nikku** [comment] 2023-04-17 07:05
> Should we remove the message completely?

What is simpler to do? If removing it completely is the simpler version, let's do this and handle "I want to keep it" as a feature request.

**Comment by barmac** [comment] 2023-04-17 07:09
We can do any of the solutions. I guess your notion of the thing is some kind of evidence that we don't want to keep the message around.

**Comment by nikku** [comment] 2023-04-17 09:20
@barmac I further experimented with your prototype. With a little bit of work we can craft an end-to-end use-case to support our intermediate inbound continuation use-cases. I think it is great!



### Screen recording

![capture IefTj2_optimized](https://user-images.githubusercontent.com/58601/232441729-d11f2588-1da7-40b3-b03e-348c385f003d.gif)


### JSON Schema for Kafka inbound (generic + domain specific)

<details>

```json
[
  {
    "$schema": "https://unpkg.com/browse/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
    "name": "Message Template",
    "id": "com.camunda.example.MessageTemplate",
    "appliesTo": [
      "bpmn:IntermediateCatchEvent",
      "bpmn:IntermediateThrowEvent"
    ],
    "elementType": {
      "value": "bpmn:IntermediateCatchEvent",
      "eventDefinition": "bpmn:MessageEventDefinition"
    },
    "properties": [
      {
        "label": "message name",
        "type": "String",
        "binding": {
          "type": "bpmn:Message#property",
          "name": "name"
        }
      },
      {
        "label": "correlation key",
        "type": "String",
        "feel": "required",
        "binding": {
          "type": "bpmn:Message#zeebe:subscription#property",
          "name": "correlationKey"
        }
      }
    ]
  },
  {
    "$schema": "https://unpkg.com/browse/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
    "name": "Message Template - hidden properties",
    "id": "com.camunda.example.MessageTemplateHidden",
    "appliesTo": [
      "bpmn:IntermediateCatchEvent",
      "bpmn:IntermediateThrowEvent"
    ],
    "elementType": {
      "value": "bpmn:IntermediateCatchEvent",
      "eventDefinition": "bpmn:MessageEventDefinition"
    },
    "properties": [
      {
        "label": "message name",
        "type": "Hidden",
        "value": "hardcoded",
        "binding": {
          "type": "bpmn:Message#property",
          "name": "name"
        }
      },
      {
        "label": "correlation key",
        "type": "Hidden",
        "value": "= correlationKey",
        "binding": {
          "type": "bpmn:Message#zeebe:subscription#property",
          "name": "correlationKey"
        }
      }
    ]
  },
  {
    "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
    "documentationRef": "https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/kafka/",
    "id": "com.camunda.example.KafkaInboundIntermediate",
    "name": "Kafka - Message Receive",
    "appliesTo": [
      "bpmn:IntermediateCatchEvent",
      "bpmn:IntermediateThrowEvent"
    ],
    "elementType": {
      "value": "bpmn:IntermediateCatchEvent",
      "eventDefinition": "bpmn:MessageEventDefinition"
    },
    "groups": [
      {
        "id": "authentication",
        "label": "Authentication"
      },
      {
        "id": "kafka",
        "label": "Kafka"
      },
      {
        "id": "subscription",
        "label": "Subscription"
      },
      {
        "id": "activation",
        "label": "Activation"
      },
      {
        "id": "variable-mapping",
        "label": "Variable Mapping"
      }
    ],
    "properties": [
      {
        "type": "Hidden",
        "generatedValue": {
          "type": "uuid"
        },
        "binding": {
          "type": "bpmn:Message#property",
          "name": "name"
        }
      },
      {
        "label": "Correlation key",
        "type": "String",
        "group": "subscription",
        "feel": "optional",
        "description": "Sets up the correlation key from the environment.",
        "binding": {
          "type": "bpmn:Message#zeebe:subscription#property",
          "name": "correlationKey"
        },
        "constraints": {
          "notEmpty": true
        }
      },
      {
        "type": "Hidden",
        "value": "io.camunda:connector-kafka-inbound:1",
        "binding": {
          "type": "zeebe:property",
          "name": "inbound.type"
        }
      },
      {
        "label": "Username",
        "description": "Provide the username (must have permissions to produce message to the topic)",
        "group": "authentication",
        "type": "String",
        "optional": true,
        "binding": {
          "type": "zeebe:property",
          "name": "authentication.username"
        }
      },
      {
        "label": "Password",
        "description": "Provide a password for the user",
        "group": "authentication",
        "type": "String",
        "optional": true,
        "binding": {
          "type": "zeebe:property",
          "name": "authentication.password"
        }
      },
      {
        "label": "Bootstrap Servers",
        "description": "Provide bootstrap server(s), comma-delimited if there are multiple",
        "group": "kafka",
        "type": "String",
        "feel":"optional",
        "binding": {
          "type": "zeebe:property",
          "name": "topic.bootstrapServers"
        },
        "constraints": {
          "notEmpty": true
        }
      },
      {
        "label": "Topic",
        "description": "Provide topic name",
        "group": "kafka",
        "type": "String",
        "feel":"optional",
        "binding": {
          "type": "zeebe:property",
          "name": "topic.topicName"
        },
        "constraints": {
          "notEmpty": true
        }
      },
      {
        "label": "Additional Properties",
        "description": "Provide additional Kafka producer properties in JSON",
        "group": "kafka",
        "type": "String",
        "optional": true,
        "feel":"required",
        "binding": {
          "type": "zeebe:property",
          "name": "additionalProperties"
        }
      },
      {
        "label": "Activation condition",
        "type": "String",
        "group": "activation",
        "feel": "required",
        "optional": true,
        "binding": {
          "type": "zeebe:property",
          "name": "activationCondition"
        },
        "description": "Condition under which the Connector triggers. Leave empty to catch all events"
      },
      {
        "label": "Correlation key",
        "type": "String",
        "group": "activation",
        "feel": "required",
        "binding": {
          "type": "zeebe:property",
          "name": "correlationKey"
        },
        "description": "Extracts the correlation key from the incoming message payload.",
        "constraints": {
          "notEmpty": true
        }
      },
      {
        "label": "Result Variable",
        "type": "String",
        "group": "variable-mapping",
        "optional": true,
        "binding": {
          "type": "zeebe:property",
          "name": "resultVariable"
        },
        "description": "Name of variable to store the result of the Connector in"
      },
      {
        "label": "Result Expression",
        "description": "Expression to map the inbound payload to process variables",
        "group": "variable-mapping",
        "type": "Text",
        "feel": "required",
        "binding": {
          "type": "zeebe:taskHeader",
          "key": "resultExpression"
        }
      },
      {
        "label": "Error Expression",
        "description": "Expression to handle errors. Details in the <a href=\"https://docs.camunda.io/docs/components/connectors/use-connectors/#bpmn-errors\" target=\"_blank\">documentation</a>",
        "group": "errors",
        "type": "Text",
        "feel": "required",
        "binding": {
          "type": "zeebe:taskHeader",
          "key": "errorExpression"
        }
      }
    ]
  },
  {
    "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
    "documentationRef": "https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/kafka/",
    "id": "com.camunda.example.PaymentReceived",
    "name": "Payment Received",
    "appliesTo": [
      "bpmn:IntermediateCatchEvent",
      "bpmn:IntermediateThrowEvent"
    ],
    "elementType": {
      "value": "bpmn:IntermediateCatchEvent",
      "eventDefinition": "bpmn:MessageEventDefinition"
    },
    "groups": [
      {
        "id": "input",
        "label": "Input"
      },
      {
        "id": "authentication",
        "label": "Authentication"
      },
      {
        "id": "kafka",
        "label": "Kafka"
      },
      {
        "id": "subscription",
        "label": "Subscription"
      },
      {
        "id": "activation",
        "label": "Activation"
      },
      {
        "id": "output",
        "label": "Output"
      }
    ],
    "properties": [
      {
        "label": "Payment ID",
        "type": "String",
        "group": "input",
        "feel": "optional",
        "binding": {
          "type": "bpmn:Message#zeebe:subscription#property",
          "name": "correlationKey"
        },
        "constraints": {
          "notEmpty": true
        }
      },
      {
        "type": "Hidden",
        "generatedValue": {
          "type": "uuid"
        },
        "binding": {
          "type": "bpmn:Message#property",
          "name": "name"
        }
      },
      {
        "type": "Hidden",
        "value": "io.camunda:connector-kafka-inbound:1",
        "binding": {
          "type": "zeebe:property",
          "name": "inbound.type"
        }
      },
      {
        "group": "authentication",
        "type": "Hidden",
        "value": "secrets.KAFKA_USERNAME",
        "binding": {
          "type": "zeebe:property",
          "name": "authentication.username"
        }
      },
      {
        "group": "authentication",
        "type": "Hidden",
        "value": "secrets.KAFKA_PASSWORD",
        "binding": {
          "type": "zeebe:property",
          "name": "authentication.password"
        }
      },
      {
        "group": "kafka",
        "type": "Hidden",
        "value": "secrets.KAFKA_BOOTSTRAP_SERVERS",
        "binding": {
          "type": "zeebe:property",
          "name": "topic.bootstrapServers"
        }
      },
      {
        "group": "kafka",
        "type": "Hidden",
        "value": "payment-processed",
        "binding": {
          "type": "zeebe:property",
          "name": "topic.topicName"
        }
      },
      {
        "group": "activation",
        "type": "Hidden",
        "value": "= message.body.payment_id",
        "binding": {
          "type": "zeebe:property",
          "name": "correlationKey"
        }
      },
      {
        "label": "Result Variable",
        "type": "String",
        "group": "output",
        "optional": true,
        "binding": {
          "type": "zeebe:property",
          "name": "resultVariable"
        },
        "description": "Name of variable to store the result of the Connector in"
      },
      {
        "label": "Result Expression",
        "description": "Expression to map the inbound payload to process variables",
        "group": "output",
        "type": "Text",
        "feel": "required",
        "binding": {
          "type": "zeebe:taskHeader",
          "key": "resultExpression"
        }
      },
      {
        "label": "Error Expression",
        "description": "Expression to handle errors. Details in the <a href=\"https://docs.camunda.io/docs/components/connectors/use-connectors/#bpmn-errors\" target=\"_blank\">documentation</a>",
        "group": "errors",
        "type": "Text",
        "feel": "required",
        "binding": {
          "type": "zeebe:taskHeader",
          "key": "errorExpression"
        }
      }
    ]
  }
]
```
</details>

**Comment by barmac** [comment] 2023-04-17 14:27
I updated the prototype with your examples @nikku. New version and all future updates will be available at https://message-templates.netlify.app/

**Comment by barmac** [comment] 2023-04-28 09:41
This is now `fixed upstream`. I moved receive task into a separate issue: https://github.com/camunda/camunda-modeler/issues/3573. We can implement it for the next release.

**Closed** 2023-04-28 13:39 UTC
Labels: needs review, enhancement, element templates
