### ISSUE TITLE
Modeler inline comment plugin does not store the comments if nothing else has been changed in the model

### ISSUE THREAD

**Issue by hjstrauss** [camunda/camunda-modeler#3590] opened 2023-05-03 15:22 UTC
### Describe the bug

As I am not allowed to re-open my bug #3560 I have to create a new issue. 
Please refer to #3560 for reproducibility, I will not copy all here once again. Additionally, please note, that the problem only comes up if **no other changes have been done in the model.**
I can reproduce at any time if the internal note is the ONLY change in the model. If there are other changes that are also reflected in the model's title bar with a blue point (indicator that a save is necessary) then the internal note is saved as well. But if I only add an internal note text, the blue point is not shown and the note's text is not saved. 
I am not sure whether this is related to the model engine or to the internal note plugin.

### Steps to reproduce

please refer to #3560 

### Expected behavior

The internal note shall be saved.

### Environment

please refer to #3560

**Comment by marstamm** [comment] 2023-05-03 15:58
Duplicate of #3560

**Closed by marstamm** 2023-05-03 15:58 UTC
Labels: bug
