### ISSUE TITLE
Cannot save a new form until I click anywhere in the Modeler

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2582] opened 2021-11-23 08:28 UTC
__Describe the Bug__

When I click on "New Form file", I cannot save the form via menu right away. The buttons are inactive.

![image](https://user-images.githubusercontent.com/28307541/142991349-971d0297-6309-435b-af00-74f4b1eeb962.png)

__Steps to Reproduce__

1. Create a new form file
2. Click on the "File" menu button.
3. now this happens

__Expected Behavior__

Buttons should be active. "Save File As..." should always be active.

__Environment__

- OS: MacOS
- Camunda Modeler Version: 4.11
- Execution Platform: -
- Installed plug-ins: none

**Comment by MaxTru** [comment] 2021-12-21 09:39
Closed as duplicate of https://github.com/camunda/camunda-modeler/issues/2635

**Closed by MaxTru** 2021-12-21 09:39 UTC
Labels: bug, backlog
