### ISSUE TITLE
Shortcuts override the search input in template selection modal

### ISSUE THREAD

**Issue by markfarkas-camunda** [camunda/camunda-modeler#3483] opened 2023-03-01 08:18 UTC
### Describe the bug

If you open the template selector popup window the search input field has the focus, and if you press the button "p", everything works as expected. But if you press any button which is a shortcut, for example "n", or "a", it does not search but execute the command bound to that shortcut. The biggest problem is the backspace. Press p, and then backspace. It will remove the Task element, but won't close the Template selector popup window. If you select the template after this, it will throw an error saying : `Cannot read properties of undefined (reading 'children')`

![image](https://user-images.githubusercontent.com/119574841/222082806-887907fc-0feb-4ce2-9bd3-d863e887c617.png)

### Steps to reproduce

1. Open editor
2. Create a new Task
3. Click on template selection button
4. Press "p" to start filtering the templates 
5. Press backspace to delete the letter "p"
6. It will remove the Task

OR

1. Open editor
2. Create a new Task
3. Click on template selection button
4. Press "n" to start filtering the templates 
5. It won't filter the templates as expected but it will open the Create element context menu

### Expected behavior

When the search input field has the focus, we should disable shortcuts.

### Environment

- OS:  Windows 11
- Camunda Modeler Version: 5.9.0-nightly.20230227
- Execution Platform: Camunda Platform
- Installed plug-ins: none

### Additional context

Related to [SUPPORT-21053](https://jira.camunda.com/browse/SUPPORT-21053)

**Comment by barmac** [comment] 2024-03-12 10:43
I can reproduce the issue in 5.21.0 but cannot reproduce the backspace-related error anymore.

**Comment by nikku** [comment] 2024-03-19 17:16
Closed via https://github.com/camunda/camunda-modeler/issues/4195.

**Closed by nikku** 2024-03-19 17:16 UTC
Labels: bug, needs review, channel:support, spring cleaning
