### ISSUE TITLE
Load multiple files causes an exception for some of the items opened

### ISSUE THREAD

**Issue by GmGamez** [camunda/camunda-modeler#3171] opened 2022-09-28 15:34 UTC
### Describe the bug

When I use the Windows explorer to open multiple files at the same time, it causes an error for some of the files opened. The tab reads "Ooops, this should not have happened" and I get this error trace: 

```
`[C:\Users\GustavoMendoza\Documents\Camunda\Clients\Trustly\trustly-sample\customer-segments-facts.dmn] Cannot read properties of undefined (reading 'id')
    at file:///C:/Camunda/Modelers/Modeler%205.3/camunda-modeler-5.3.0-win-x64%20(1)/resources/app.asar/public/770.js:1:6962 (1)/resources/app.asar/public/770.js:1:6962)
    at Array.find (<anonymous>)
    at W.open (1)/resources/app.asar/public/770.js:1:6936)
    at W.checkSheetChange (1)/resources/app.asar/public/770.js:1:11394)
    at W.checkImport (1)/resources/app.asar/public/770.js:1:10313)
    at W.componentDidMount (1)/resources/app.asar/public/770.js:1:9158)
    at Qs (1)/resources/app.asar/public/bundle.js:2:782845)
    at Fs (1)/resources/app.asar/public/bundle.js:2:785739)
    at file:///C:/Camunda/Modelers/Modeler%205.3/camunda-modeler-5.3.0-win-x64%20(1)/resources/app.asar/public/bundle.js:2:803376 (1)/resources/app.asar/public/bundle.js:2:803376)
    at t.unstable_runWithPriority (1)/resources/app.asar/public/bundle.js:2:825846)
    at Ba (1)/resources/app.asar/public/bundle.js:2:803310)
    at xa (1)/resources/app.asar/public/bundle.js:2:803086)
    at wa (1)/resources/app.asar/public/bundle.js:2:802431)
    at ga (1)/resources/app.asar/public/bundle.js:2:801452)
    at Hs (1)/resources/app.asar/public/bundle.js:2:800321)
    at Object.enqueueSetState (1)/resources/app.asar/public/bundle.js:2:750133)
    at w.setState (1)/resources/app.asar/public/bundle.js:2:817771)
    at wc.showTab (1)/resources/app.asar/public/bundle.js:2:2348591)
    at file:///C:/Camunda/Modelers/Modeler%205.3/camunda-modeler-5.3.0-win-x64%20(1)/resources/app.asar/public/bundle.js:2:2337779 (1)/resources/app.asar/public/bundle.js:2:2337779) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]`
```

### Steps to reproduce

1. do this: Navigate to a directory with multiple DMN or BPMN files. 
2. do that: Select multiple files (can be two or more) and press enter to open them (or double click)
3. now this happens: in the modeler, I see all the tabs opened, but when I click on them to see the contents, most times I get one that has the error message from the attached images.
![3 - Error on one of the tabs](https://user-images.githubusercontent.com/81256346/192822057-2d79e911-97b1-4a7c-a1e7-c4f3cd94d417.JPG)
![1 - Selection of files to open](https://user-images.githubusercontent.com/81256346/192822060-9e3d50ea-4301-4f78-b41b-96b357612771.JPG)
![2 - Opened tabs in Modeler](https://user-images.githubusercontent.com/81256346/192822063-56663676-1947-4a0a-be21-4ff2bc99a44a.JPG)

### Expected behavior

All file should open without any errors

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.3.0
- Execution Platform: Camunda 8 models
- Installed plug-ins: token simulator and excel import

**Comment by nikku** [comment] 2022-09-28 16:31
Can you verify that each individual file opens just fine?

**Comment by GmGamez** [comment] 2022-09-28 18:08
Hi, 

I confirmed that individually opening them works fine. It's only when trying to bulk open them

cheers

**Comment by nikku** [comment] 2022-10-17 22:04
Closing this due to missing feedback. We'd need a reproducible test set to be able to follow up on this.

**Closed by nikku** 2022-10-17 22:04 UTC
Labels: bug, help wanted
